Text_SwordsDanceTeach::
    .string "LEARN SWORDS DANCE? Y/N$"

Text_SwordsDanceDeclined::
    .string "YOU ENTER A DARK CAVE.$"

Text_SwordsDanceWhichMon::
    .string "Squirtle Helps to Heal$"

Text_SwordsDanceTaught::
    .string "'STRENGTH IS KEY TO VICTORY!'$"

SevenIsland_Text_IslandSign::
    .string "Embark on a journey through the VI\p"
    .string "of Eternity!$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "'The truth is, these islands are\p"
    .string "so named...'$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "'CAUTION: Dense Jungle Ahead'$"

