OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "'What's cookin', buddy?'$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "BILL: Ah, Celio, I've come to put\p"
    .string "a stop to your treasure huntin'!$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "ERROR: SYSTEM INTERUPT RECEIVED.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "You get a fax from CELIO: 'Greet\p"
    .string "Marle, bring WLK Card'$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "You've got the gold badge on your\p"
    .string "hat!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "THE CROWD CHEERS!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "'Let's focus on strategy, huh?'$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string " Cygnus-IV systems online, Chief.\p"
    .string "Should be ready to roll.$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "LINK DEFECT DETECTED. TRY\p"
    .string "REBOOTING PC UPHEAVAL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: Gotcha!$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "Deliver METEORITE to TWO ISLAND's\p"
    .string "GAME CORNER$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "WEIRD CHUNK OF SPACE STUFF IN\p"
    .string "STOCK$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "'A parcel of supplies for the\p"
    .string "journey'$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "FERRY SCHEDULE:$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "MAP UPGRADED!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "MAP UPDATED$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "SEE YA, PAL!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string " LEVEL NOT LOADED : buffering...$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Let's go grab some air, shall we?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "Sorry to intrude, but crucial esp\p"
    .string "agendas awaits.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "'POWER RESTORED?'$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "What brings ya to town, partner?$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "GALAX: Heh, partying with the\p"
    .string "troops. Mission accomplished, sir!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "'THANKS, BILL! QUICK PAYDAY?'$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "'Your training is complete,\p"
    .string "Celio!'$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "'Think again, pal!'$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "JOB COMPLETE.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "Sorry, sent ye on yer own lonesome\p"
    .string "fate!$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "What's the machine do, CELIO?$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "Need help with those POKeMON, eh?$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Systems updated!$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "Find gemstone on ONE ISLAND?$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "You should really focus.p$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "UNIDENTIFIED ENERGY SIGNATURE\p"
    .string "DETECTED$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "'Well done, hero!'$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Save the princess and I'm yours.$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "STRANGER'S PLEA$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Get Ferry Pass  Town Map, and sail\p"
    .string "to Sevii Islands!$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "'You've earned the Rainbow Pass!'$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "New Territory Unlocked!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "'Steer clear, danger lurks ahead!'$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "'Well done, hero! Fate's balance\p"
    .string "shifts once more.'$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "You're a tough nut to crack, eh?$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "'Enemies ahead! Fight or flee?'$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "Finally reunited with the rebel\p"
    .string "leader!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "PLAYER, I did it!$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "Time to catch some 'MON!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "You're the one they call Savior of\p"
    .string "Atlas?$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "CHOOSE RESPONSE$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "What a coincidence! You know\p"
    .string "GOLDENROD CITY quite well?$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "You: Cow udderly disgusting!$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "What do you know about Pallet\p"
    .string "Town?$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string " Volcano Summit ApproachDanger of\p"
    .string "Lava Flows$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Please contact Professor Oak to\p"
    .string "discuss possible solutions.$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "THOSE 2 REALLY CARE ABOUT US!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string " SYSTEM UPDATE NEEDED$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Connection Authenticated. Proceed\p"
    .string "with Caution.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Connection established. Ready to\p"
    .string "transmit data.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "'POWER LEVEL INCREASED!'$"

