SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Don't blow my cover!$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "'ta da! Goldenrod Tower\p"
    .string "liberated!'$"

SilphCo_4F_Text_Grunt1Intro::
    .string "saretasaretaPUT BACK THE MOOLAH!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "SHIP SINKING!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "'Condemned to Destruction...!'$"

SilphCo_4F_Text_RodneyIntro::
    .string "'Servant no more, by dawn's early\p"
    .string "light!'$"

SilphCo_4F_Text_RodneyDefeat::
    .string "'Total Defeat! Your weak PKMN\p"
    .string "unable to withstand the attack!'$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "'Enter CARD KEY to proceed.'$"

SilphCo_4F_Text_Grunt2Intro::
    .string "8888 BETRAYED!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "RONIN WARRIOR$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "'BOSSES' OFFICE, 11F:  IMPERIAL\p"
    .string "FACTORIES UNDER SIEGE!'$"

SilphCo_4F_Text_FloorSign::
    .string "'Welcome, Agent. Please report to\p"
    .string "reception.'$"

