PokemonMansion_1F_Text_TedIntro::
    .string "'You are lone wanderer, Eira\p"
    .string "Shadowglow.'$"

PokemonMansion_1F_Text_TedDefeat::
    .string "You've taken 3 damage!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "You found a rusty old KEY!$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "Whoa, easy there! I'm no phantasm!$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "'UNLUCKY BREAK! TRY AGAIN,\p"
    .string "CAPTAIN!'$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "CREATURES SEEN LURKING IN SHADOWS!$"

