SixIsland_GreenPath_Text_JaclynIntro::
    .string "ERROR 556: UNEXPECTED\p"
    .string "TELEPORTATION$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "You stumble upon a broken bridge.\p"
    .string "Careful, it's a long way down!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "WARNING: TELEPORT SEQUENCE\p"
    .string "INTERRUPTED!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "'Beware deceitful vines!'$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "USE SPECIAL TOXIN-LESS SPRAY TO\p"
    .string "CLEAN UP OIL SPILLS!$"

