FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "Here is a snippet of text to be\p"
    .string "used in the given context:  '\n"
    .string "Warning: Approach with caution!'$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "'Moonlight gnomes lurk near\p"
    .string "ancient shrine'$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "MY PRECIOUS BOSS BAAB!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "Keys collected: 5$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "'You're goin' down, jailbird!'$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "You receive 50 Galleon Reward$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "You receive: 10 Shins$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "'Controller abilities unlocked!'$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "Find HM04, discover STRENGTH!$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "GET READY FOR A FIGHT!$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "'A TREASURE TROVE AWAITS!'$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string " Rare finds await!$"

