RockTunnel_B1F_Text_SofiaIntro::
    .string "'BEND TWIGS FOR TRAIL MARKER'$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string ".Standard.Standard Allowance\p"
    .string "Acquired!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "HOME IS WEST OF HERE$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "CHRGR UNLESHED!$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "YOU MUST STRENGTHEN YOUR MUSCLES!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "You've chosen POWER OVER WISDOM.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Acquiring POKeDEX in progress...$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "'source code security breach!\p"
    .string "seeking new access codes'$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "'GRAA! MY LIFE'S WORK!'$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Pikachu's Power Surged!$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "'CONTINUE?'$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "You're a fashionista Fairy, eh?$"

RockTunnel_B1F_Text_AllenIntro::
    .string "GALVANTINE: 100 DAMAGE!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "'System Reboot Initializing...'$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "'Traversing the rocky terrain, you\p"
    .string "spot a GRONPEA!'$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "THE SNOWY MOUNTAINS AWAIT!$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "GAME OVER!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "FOUND: Pidgey!$"

RockTunnel_B1F_Text_EricIntro::
    .string "'ENEMY ALIEN APPROACHING!'$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Explosion 20/20 Crit hitsguards!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "Bring it on!$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "You've been doodling Pikachu all\p"
    .string "evening...$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Resting...$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "'Returning to humble abode'$"

