CeladonCity_Condominiums_1F_Text_Meowth::
    .string "'Ah, a sneaky Meowth! Watch out,\p"
    .string "adventurer!'$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "BARTENDER SAYS: 'SIP ON THIS: 5\p"
    .string "GOLD COINS'.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "'TESSEL'S TEA: RESTORES THIRST'$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "MEOWTH'S PURR-FECT CATCH: 500\p"
    .string "JULIES$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "'A PALLET TOWN native, eh?'$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "Catching a Poke Ball!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "'Gleaming Scale Rush!'$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "You've made it to the top floor.\p"
    .string "The door creaks open.$"

