Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "'Caution: Maintenance tunnel\p"
    .string "ahead!'$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "'Pedals spinning, wind in hair!\p"
    .string "Whoa, look out for thatROOT!$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "! Surveilling... !: A few\p"
    .string "Trainers, Cleffa and Pidgey\n"
    .string "roaming around$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "A distant island, shrouded inn\p"
    .string "mist. Buildings visible, but non\n"
    .string "sign of life.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Delete Pokedex data already\p"
    .string "stored.-conf Boolean$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "WOOHOO!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "New Power at Ur-Hand!$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "Found AMULET COIN!$"

