FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Grab freq ID: 135$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "Welcome to SAFARI ZONE!$"

FuchsiaCity_Text_WheresSara::
    .string "'USUAL SPOT EMPTY. FEELS LIKE\p"
    .string "WE'VE BEEN DOUBLE-CROSSED.'$"

FuchsiaCity_Text_ItemBallInThere::
    .string " WAIT WAIT WAIT! YOU CAN'T HAVE\p"
    .string "IT!$"

FuchsiaCity_Text_CitySign::
    .string "Arrival in Fuchsia City!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "'WELCOME TO SAFARI ZONE'$"

FuchsiaCity_Text_SafariGameSign::
    .string "Capture Escaped POKEMON!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "You approach the Warden's Home.$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "'food alert!'$"

FuchsiaCity_Text_GymSign::
    .string "'Defeat the Poisonous Ninja!'$"

FuchsiaCity_Text_ChanseySign::
    .string "Rolling... Result: 1$"

FuchsiaCity_Text_VoltorbSign::
    .string "'Ready for a shock...?'$"

FuchsiaCity_Text_KangaskhanSign::
    .string "'FED UP, READY TO FIGHT!'$"

FuchsiaCity_Text_SlowpokeSign::
    .string "'Ahh, so slow...'$"

FuchsiaCity_Text_LaprasSign::
    .string "'Ahoy, you're in its sights!'$"

FuchsiaCity_Text_OmanyteSign::
    .string "'Ahoy sailor, spotted an Omanyte\p"
    .string "washed up on the shore!'$"

FuchsiaCity_Text_KabutoSign::
    .string "URGENT: Fossil Alert! Kabuto\p"
    .string "Nearby!$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "'YOU FIND IT'$"

Text_SubstituteTeach::
    .string "Teach Battle POKemon SUB fikir$"

Text_SubstituteDeclined::
    .string "'BEWARE THE DRAGON WARRIOR!'$"

Text_SubstituteWhichMon::
    .string "Charmander, Jolteon, and Clefairy.$"

Text_SubstituteTaught::
    .string "The primal urge grips you!$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "You approach your father, Gary, in\p"
    .string "the Vermilion City Gym.$"

