ThreeIsland_Text_IslandSign::
    .string "'Ah, finally! A refuge from the\p"
    .string "stormy seas!'$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "VICTORY IS OURS!$"

ThreeIsland_Text_GoBackToKanto::
    .string "'Fool, leave now or face the\p"
    .string "wrath!'$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "YOU GOT A PROBLEM, BUDDY?$"

ThreeIsland_Text_GetOffIslandNow::
    .string "You can't escape the island so\p"
    .string "easily!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "'Baron Von Miserich steps forth,\p"
    .string "challenging your honor!'$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "YOU BETTER NOT IGNORE MY ORDER!$"

ThreeIsland_Text_JustGotHerePal::
    .string "You're that new explorer, eh?$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Those rebels have gone haywire!$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string " Talk trash$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "'FACING 3 WOLVES. WHAT DO YOU DO?'$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "PROPROT-type, leave it be!$"

ThreeIsland_Text_ThatsSmart::
    .string "'Mind Your Own Biz'$"

ThreeIsland_Text_Biker1Intro::
    .string "'Yer dearly acquired assets, dat\p"
    .string "is!'$"

ThreeIsland_Text_Biker1Defeat::
    .string "Mysterious Juvenile Encountered!$"

ThreeIsland_Text_Biker1PostBattle::
    .string "'Your Rucksack's gone missing!'$"

ThreeIsland_Text_Biker2Intro::
    .string "'I'VE GOT NO LOYALTIES IN KANTO!'$"

ThreeIsland_Text_Biker2Defeat::
    .string "You've made a grave mistake!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "Who's callin' the shots here?$"

ThreeIsland_Text_Biker3Intro::
    .string "'BETTER RUN WHILE YOU STILL CAN'$"

ThreeIsland_Text_Biker3Defeat::
    .string "You stumble upon a dusty old\p"
    .string "chest.contents unknown$"

ThreeIsland_Text_Biker3PostBattle::
    .string "'TRouble in the Trenches'$"

ThreeIsland_Text_PaxtonIntro::
    .string "You're a fake?!$"

ThreeIsland_Text_PaxtonDefeat::
    .string "'You cocksuckers just wait!'$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "'LEAVE NOW, TENDERFOOT! WORST IS\p"
    .string "YET TO COME!'$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "Your Pikachu took 12 points of\p"
    .string "damage!$"

ThreeIsland_Text_GivenFullRestore::
    .string "HP FULL!$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "'Can't fit another thing in here!'$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "'Who dares challenge?'$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "WELCOME TRAVELER!$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "'Maybe the townspeople know\p"
    .string "something...'$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "You find a RARE PEARL in the\p"
    .string "underbrush!$"

ThreeIsland_Text_Doduo::
    .string "'DUU-DUU! The wild Doudou\p"
    .string "appears!'$"

