CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "'Taking a break with Fuji!'$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "EXAMINE RARE POKeMON$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "FOUND!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "Professor Oak awaits.$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "'Experiment Alpha-67 Initiated. Be\p"
    .string "cautious, trainers!'$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "EXPERIMENTAL DATA CONTAINED\p"
    .string "WITHIN. PROCEED WITH CAUTION.$"

