MtMoon_1F_Text_MarcosIntro::
    .string "'Who ya lookin' for, little\p"
    .string "whippersnapper?'$"

MtMoon_1F_Text_MarcosDefeat::
    .string "UNBELIEVABLE!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "What are you looking for?$"

MtMoon_1F_Text_JoshIntro::
    .string "You approach the dark entrance.$"

MtMoon_1F_Text_JoshDefeat::
    .string "'Oh no, game over!'$"

MtMoon_1F_Text_JoshPostBattle::
    .string "'OOOH, HEY LASSES! LOOK AT ME!'$"

MtMoon_1F_Text_MiriamIntro::
    .string "'Cavern ahead!629 ft deep'$"

MtMoon_1F_Text_MiriamDefeat::
    .string "You have dropped your Backpack.\p"
    .string "What do you do?$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "'SEEK MIRAGE MOUNTAIN PATH'$"

MtMoon_1F_Text_JovanIntro::
    .string "WHOOSH!$"

MtMoon_1F_Text_JovanDefeat::
    .string "YOUR PIKACHU LOOKS SICK!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "'Try the Dark Cave, they say...'$"

MtMoon_1F_Text_IrisIntro::
    .string "'Lost in the Wastes...'$"

MtMoon_1F_Text_IrisDefeat::
    .string "'Game Over: 'Achilles Heel'\p"
    .string "defeated by 'Dark Invader'!'$"

MtMoon_1F_Text_IrisPostBattle::
    .string "'Rare Claws of Relic Wyrm Found: 3\p"
    .string "remaining'$"

MtMoon_1F_Text_KentIntro::
    .string "Stranger appears, eyeing you\p"
    .string "coolly.$"

MtMoon_1F_Text_KentDefeat::
    .string "YOU'RE IN MY TRAP!$"

MtMoon_1F_Text_KentPostBattle::
    .string "ROCKETS ON THE LOOSE!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Bright lights! Danger lurks ahead!$"

MtMoon_1F_Text_RobbyDefeat::
    .string "50 GOLD COINS$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "'You got it! Good luck!'$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "WITCH CREST AHEAD$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "'Whoa! Got something big here,\p"
    .string "CHZZT!'$"

