PokemonMansion_B1F_Text_LewisIntro::
    .string "UNKNOWN REALM$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "WANTED: GOLDEN CHICKEN$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "'Old Lunchbox'$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "LAB FACILITIES FOUND$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "'Strange energy signature\p"
    .string "discovered!'$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "You've found the Abandoned\p"
    .string "Monastery Library.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Experiment Containment Breach\p"
    .string "Imminent$"

