SevenIsland_TrainerTower_Text_DarioIntro::
    .string "'Uh-oh, danger lurks nearby...'$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "QUIT WHILE YOU'RE AHEAD!$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "POWER AWAKENS. STRANGE ENERGY\p"
    .string "DETECTED.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "'WAKE UP, SLEEPING MON!'$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "WILL YOU FACE MY ULRITH?!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "'I REST HERE'$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "APPROACHING ENTRANCE DOOR...$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "'Beware, rival trainers protect\p"
    .string "the tower's secrets'$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "ACCESS DENIED BY TRAINER TOWER$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "'1F: Trainer Tower Entrance'$"

