VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "'Ah, it's CUTE, all right!'$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "YOU DARE TO QUESTION MY PIKACHU'S\p"
    .string "CUTENESS?!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "SEEL'S CUTE NOISE: Kyuuuh!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "'A WORLDLY CREATURE LIKE\p"
    .string "YOURSELF?'$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "'R U READY?'$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "'Seel uses Water Gun!'$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Welcome to the POKeMON Fan Club!\p"
    .string "Meet the Chairperson:$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Meet my little RAPIDASH, ain't it\p"
    .string "lovely?Y$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "'You're all set!'$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "BIKE VOUCHER$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "'Stranger in the night...'$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "What is this?!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "CREEPING CACTUS APPROACHES!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "'Chairman's obsession with POKEMON\p"
    .string "grows stronger by the day...'$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "'MAINTENANCE SHUTTLE EN ROUTE TO\p"
    .string "STATION. RESUME TRAINING IN 5.'$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "'Ha! You think you're tough, huh?'$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "CHAIRMAN'S FAVE POKE FRIENDantium\p"
    .string "WILD POKE SEARCH...$"

