PokemonTower_7F_Text_Grunt1Intro::
    .string "STRANGE PILGRIM, WHAT BRINGS YOU\p"
    .string "TO THIS forsaken MOOR?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "YOU GIVE UP TOO EASY!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "Beware the Shadow Beasts roaming\p"
    .string "the Lost City!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "'You're just a foolish old man!'$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "SILENCE! NO MORE!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "You can't shake off Team Rocket\p"
    .string "that easily!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "BETRAYED!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "'ROCKETS APPROACHING! GET OUT\p"
    .string "WHILE YOU STILL CAN!'$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "'YOU DARE DEFY THE AUTHORITY!'$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "Follow Mr. Fuji to Pokemon House!$"

