PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "CONFIRM/p$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "WELCOME BACK TO THE FRAY!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "ITEM PURCHASED: ENERGY BOOST$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "Not enough clams!$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "You're having a blast at the\p"
    .string "arcade!$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "AMBER stands for Authorized\p"
    .string "Mainframe Access By\n"
    .string "EncryptionRoutine. It's a high-\p"
    .string "level clearance clearance! Not for\n"
    .string "the likes of you!$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "CLASSIFIED DATA FOUND$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "Amber forma$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "' OFFICERS DESIRED THIS DIRECTION\p"
    .string "'$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "'Legend says this beast oncen\p"
    .string "breathed fire that lit the land'$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "'Seek lab utmost haste, Pokemon\p"
    .string "DNA integrity assured!'$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "3 Hit Points restored.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "SEARCHING FOR OLD AMBER... FOUND!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "Not enough room, danger lurks\p"
    .string "ahead!$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "'Dust off the secrets of the\p"
    .string "ancient ones'$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "GOLDEN AMBER FOUND!$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "FOUND INicia's CAVERN$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "YOU FOUND A Fossil!$"

