SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "THUNDEROUS APPLAUSE!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "STRUT YOUR STUFF! Y/ES N/O$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "DANCE FEVER TIME!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "WOOHOO!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "YOU GOT THE ITEM!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "'Ahahah, Welcome to my cave,\p"
    .string "adventurer!'$"

