VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "Packages loaded, flying to SAFFRON$"

VermilionCity_House3_Text_Pidgey::
    .string "TRY TO CATCH ME!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "'INFO: SAFFRON TRouble, TEAM\p"
    .string "ROCKET seen'$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Received 3 pieces of MAIL from\p"
    .string "other trainers.$"

