Route18_Text_WiltonIntro::
    .string "You spot a wild Rabbit Pokemon!$"

Route18_Text_WiltonDefeat::
    .string "'ARGH! SHARP ROCK AHEAD!'$"

Route18_Text_WiltonPostBattle::
    .string "CRUMPLED FRAME LIES IN RUINS$"

Route18_Text_RamiroIntro::
    .string "'HONK HONK! Flooblopx gets\p"
    .string "restless!'$"

Route18_Text_RamiroDefeat::
    .string "LIKE A BEE IN YOUR BONNET?!$"

Route18_Text_RamiroPostBattle::
    .string "'Diving near the coast, found a\p"
    .string "MAGIKARP!'$"

Route18_Text_JacobIntro::
    .string "YOU DONT BELONG HERE$"

Route18_Text_JacobDefeat::
    .string "'Game Over!'$"

Route18_Text_JacobPostBattle::
    .string "Shiny magikarp, but careful!$"

Route18_Text_RouteSign::
    .string "'Turn left at the first fork!'$"

Route18_Text_CyclingRoadSign::
    .string "WARNING: cyclists beware of\p"
    .string "oncoming traffic!$"

