Text_SeismicTossTeach::
    .string "STAUNCHLY PREPARE FOR SEISMIC\p"
    .string "TOSS!$"

Text_SeismicTossDeclined::
    .string "You bet your life it is!$"

Text_SeismicTossWhichMon::
    .string "Snivy$"

Text_SeismicTossTaught::
    .string "'YOU'VE GOT THIS! STAY FOCUSED!'$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "'Power of Nature: Adds 5 HP'$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "'YOUR MISSION: DECODE THE MESSAGE\p"
    .string "OF THE MUMBLING HOST'$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "'BLAST OFF  EXPLORE THE COSMOS!'$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string " DATABASE malfunc   ERR:\p"
    .string "UNEXPECTED Wildlife Encounter!\n"
    .string "CATCH: PIKACHU SURFER!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "'RUMBLINGS OF A HIDDEN POKEMON\p"
    .string "DETECTED'$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "'Approach the Shuttle... Critical\p"
    .string "Systems Online'$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "MOON STONE FOUND ON MT. MOON!$"

