Route19_Text_RichardIntro::
    .string "WARM UP COMPLETE!$"

Route19_Text_RichardDefeat::
    .string "LET'S GET READY TO RUMBLE!$"

Route19_Text_RichardPostBattle::
    .string "SURF'S UP!$"

Route19_Text_ReeceIntro::
    .string "Hold up, hero!$"

Route19_Text_ReeceDefeat::
    .string "Frostbite beckons... BRRR!$"

Route19_Text_ReecePostBattle::
    .string "CAUTION: TENTACOOL SPOTTED!$"

Route19_Text_MatthewIntro::
    .string "SURF'S UP!$"

Route19_Text_MatthewDefeat::
    .string "'OOOOOF!'$"

Route19_Text_MatthewPostBattle::
    .string "You've caught a Magikarp!$"

Route19_Text_DouglasIntro::
    .string "'Mysterious Isles beckon, whispers\p"
    .string "of ancient ruins echo through the\n"
    .string "mist.'$"

Route19_Text_DouglasDefeat::
    .string "'Abandon all hope, ye who enter\p"
    .string "the Abyssal Depths!'$"

Route19_Text_DouglasPostBattle::
    .string "'Exotic Oasis Islands, approx. 5\p"
    .string "miles distant. Explore at your own\n"
    .string "peril!'$"

Route19_Text_DavidIntro::
    .string "'Diving too deep for now...'$"

Route19_Text_DavidDefeat::
    .string "LOST IN THE DEPTHS OF ELDORIA?!$"

Route19_Text_DavidPostBattle::
    .string "LOBSTER catches!$"

Route19_Text_TonyIntro::
    .string "You gaze out at the endless\p"
    .string "blue...$"

Route19_Text_TonyDefeat::
    .string "DAMAGED ALARMS DETECTED$"

Route19_Text_TonyPostBattle::
    .string "MISTYMBProgressHUD bereg$"

Route19_Text_AnyaIntro::
    .string "'RIDE FOR SALE! 1000 BulletsKey?'$"

Route19_Text_AnyaDefeat::
    .string "GAME OVER!$"

Route19_Text_AnyaPostBattle::
    .string "ERR: UNABLE TO SET COURSE. SEAFOAM\p"
    .string "SIGNAL WEAK.$"

Route19_Text_AliceIntro::
    .string "'Careful, you're getting cooked!'$"

Route19_Text_AliceDefeat::
    .string "'ELECTROCUTION ATTEMPTED!'$"

Route19_Text_AlicePostBattle::
    .string "'SEAS ROUGH. CAUTION ADVISED.'$"

Route19_Text_AxleIntro::
    .string " Warning: Sea Serpents Ahead!$"

Route19_Text_AxleDefeat::
    .string "WATERFALL OF DOOM AHEAD!$"

Route19_Text_AxlePostBattle::
    .string "' drowning; help detect'$"

Route19_Text_ConnieIntro::
    .string "YOU'RE AT THE BEACH...$"

Route19_Text_ConnieDefeat::
    .string "You rest for a moment, regaining\p"
    .string "some strength...$"

Route19_Text_ConniePostBattle::
    .string "'Dreams of aquatic adventures!'$"

Route19_Text_RouteSign::
    .string " Chart: F512647$"

Route19_Text_LiaIntro::
    .string "Trainer James has awakened!$"

Route19_Text_LiaDefeat::
    .string "YOU'LL PAY FOR THAT, KID!$"

Route19_Text_LiaPostBattle::
    .string "'Yeah, he's a sprout. I'm tryin'!'$"

Route19_Text_LiaNotEnoughMons::
    .string "'Ah, sibling spunk, eh? I've got\p"
    .string "just the pair! Let's do this!'$"

Route19_Text_LucIntro::
    .string "'Remembering Sis's wise words, I\p"
    .string "set off into the water, POKeMON by\n"
    .string "my side!'$"

Route19_Text_LucDefeat::
    .string "A GRIZZLED VETERAN APPROACHES!$"

Route19_Text_LucPostBattle::
    .string "YOU SAY YOUR SISTER IS AWESOME?$"

Route19_Text_LucNotEnoughMons::
    .string "'Go, now!'$"

