VictoryRoad_1F_Text_NaomiIntro::
    .string "ARE YOU READY FOR THE CHALLENGE?!$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "-500 CREDITS$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "'Can't let pride crush me!'$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "BRING. IT. ON!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "'MISSED!'$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "'HA! YOU MAY HAVE WON THIS BATTLE,\p"
    .string "BUT THE WAR IS FAR FROM OVER!'$"

