SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "OLD RUINS LIE BENEATH$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "'It seems you've stirred up some\p"
    .string "trouble...'$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "'Hidden temples await your\p"
    .string "discovery...'$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "'Sleeping Beast Encounters'$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "'Guard your flanks, the Elemental\p"
    .string "Beasts are closing in!'$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "'Gnawtki Ruin, 500 meters east'$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "'BRUSH STROKES RUFFLED, YOUR\p"
    .string "ARTISTIC SKILL LEVEL INCREASED!'$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "SHHH! Mind the noise detector!$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "A LONELY STRUCTURE STANDS BEFORE\p"
    .string "YOU$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "YNAMIC SENTINEL ALERT$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "STRANGE AURA DETECTED IN IMCLUDING\p"
    .string "FOREST$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "A wild Pidgey appears!$"

