CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "DO YOU HAVE berries TO SELL?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string " secret passage ahead$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "CRUSH BERRIES INTO POWDER AT\p"
    .string "DIRECT CORNER!$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "YOU MAKE ME SADPrints no berries\p"
    .string "on inventory$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "Huh? Berries okay, I guess!$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "Yeah! Fresh from the Mystic\p"
    .string "Forest!$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "Gold Coins 5$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "Y/N$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "'Return to Cache Cave to stock\p"
    .string "up!'$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "Trade what for BERRY POWDER?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "SEE YOU, SPACE SIGNS!$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "'OLD MAN'S SHACK'$"

