Route20_Text_BarryIntro::
    .string "'Warm waters await... Hmmswap'$"

Route20_Text_BarryDefeat::
    .string "WET FEET!$"

Route20_Text_BarryPostBattle::
    .string "You can't ride wild Pokemon,\p"
    .string "trainer!$"

Route20_Text_ShirleyIntro::
    .string "'Coastal breeze, salty air,\p"
    .string "relaxation calls!'$"

Route20_Text_ShirleyDefeat::
    .string "click$"

Route20_Text_ShirleyPostBattle::
    .string "'BEWARE THE TREADMILL OF DOOM!'$"

Route20_Text_TiffanyIntro::
    .string "DEEP WATER SAFARI BET autistic$"

Route20_Text_TiffanyDefeat::
    .string "WARNING: ROCKslides ahead!$"

Route20_Text_TiffanyPostBattle::
    .string "YOYOBOING$"

Route20_Text_IreneIntro::
    .string "Error 404: No signal detected.\p"
    .string "Please report to the nearest\n"
    .string "Miguel's Quest HQ.$"

Route20_Text_IreneDefeat::
    .string "'TARGET IN SIGHT. ENGAGE.'$"

Route20_Text_IrenePostBattle::
    .string "TREACHEROUS SHORELINES NOW CRUMBLE\p"
    .string "INTO THE BRINE.$"

Route20_Text_DeanIntro::
    .string "You flex your muscular arms,\p"
    .string "grinning proudly.$"

Route20_Text_DeanDefeat::
    .string "'Your scare is showing!'$"

Route20_Text_DeanPostBattle::
    .string "ANGUISH!$"

Route20_Text_DarrinIntro::
    .string "'FOLLOW LANE, CAPTAIN!'$"

Route20_Text_DarrinDefeat::
    .string "ENEMY TORPEDO INCOMING!$"

Route20_Text_DarrinPostBattle::
    .string "HOP ON RIDA'S SQUIRTLE!$"

Route20_Text_RogerIntro::
    .string "Terrain: Volcano$"

Route20_Text_RogerDefeat::
    .string "'Main BriggsIMPLANTED BY THE\p"
    .string "ENEMY! RETURN TO BriggsIMPLANTED\n"
    .string "BY THE ENEMY! RETURN TO LAB!'$"

Route20_Text_RogerPostBattle::
    .string "'Stranded on distant isle. Search\p"
    .string "for alternate retreat.'$"

Route20_Text_NoraIntro::
    .string "You Received: Pearl Necklace$"

Route20_Text_NoraDefeat::
    .string "STOLEN BY THIEF!$"

Route20_Text_NoraPostBattle::
    .string "Collection message 'Pearls already\p"
    .string "at maximum size.'$"

Route20_Text_MissyIntro::
    .string "'Exhausted from the long journey'$"

Route20_Text_MissyDefeat::
    .string " FAILED Quest Goal: Relic of\p"
    .string "Ancients$"

Route20_Text_MissyPostBattle::
    .string "You approach the creaky mansion\p"
    .string "gates. What do you do?$"

Route20_Text_MelissaIntro::
    .string "'Join me, grandson? Assist daddy\p"
    .string "in Poke research!'$"

Route20_Text_MelissaDefeat::
    .string "WAIT...$"

Route20_Text_MelissaPostBattle::
    .string "Welcome to CINNABAR...$"

Route20_Text_SeafoamIslands::
    .string "'EXPERIENCING STRANGE ENERGY\p"
    .string "SIGNATURES'$"

Route20_Text_MistyTrainsHere::
    .string "'A Trainer with a Squirtle\p"
    .string "approaches!'$"

