SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "MOBSPART.PNG!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "UNIDENTIFIED BERRIES CONTAIN\p"
    .string "MYSTICAL PROPERTIES. PROCEED WITH\n"
    .string "CAUTION.$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "'Sorry, no time to chat! Gotta\p"
    .string "move!'$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "SPUD SLAYER APPROACHING!$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "'SNORLAX DEMANDS YOUR FOOD!'$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "'Trapped in the Kitchen. Escape?!'$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "'TOURNEED TURMERIC TOFU!'$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "'TODAY'S CATCH! FRESH SALMON\p"
    .string "BALLS'$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "' Ere now, good sir, no more\p"
    .string "sauces!'$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Only 3 fillets left!$"

