SilphCo_2F_Text_ConnorIntro::
    .string "'ALERT: Infiltration Imminent.\p"
    .string "Head to Tork's Research Lab, NOW!'$"

SilphCo_2F_Text_ConnorDefeat::
    .string "' Munitions of fate delivered!'$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "'Rumors of traitor plot revealed!'$"

SilphCo_2F_Text_JerryIntro::
    .string "ACCESS DENIED$"

SilphCo_2F_Text_JerryDefeat::
    .string "Well Done!$"

SilphCo_2F_Text_JerryPostBattle::
    .string "SCARCE PATHnds ahead.$"

SilphCo_2F_Text_Grunt1Intro::
    .string "BARGAIN HOLE CLOSED$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Crushing Block!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "'BEEP BOOP: TELEPORTING IN\p"
    .string "PROGRESS...'$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Lost in the Wastes, ain't ya?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "ERROR:'' fstloe says: 'OOPS, TRY\p"
    .string "AGAIN!'$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "DATABASE CORRUPTED$"

Text_ThunderWaveTeach::
    .string "'Ralsei says: Teach you Thunder\p"
    .string "Wave? Hmm...'$"

Text_ThunderWaveDeclined::
    .string " ENEMY WEAKNESSES DETECTED$"

Text_ThunderWaveWhichMon::
    .string "'RizXygon or Weavile?'$"

Text_ThunderWaveTaught::
    .string "Use THUNDER WAVE!$"

SilphCo_2F_Text_FloorSign::
    .string "'Authorization required. What is\p"
    .string "your purpose?'$"

