Route21_South_Text_JackIntro::
    .string "'GOTCHA! MAGIKARP'$"

Route21_South_Text_JackDefeat::
    .string "Warning: Airlock Malfunction$"

Route21_South_Text_JackPostBattle::
    .string "WILD PIDGEY SPOTTED!$"

Route21_South_Text_JeromeIntro::
    .string "SWIM LAP 3 OF 5...$"

Route21_South_Text_JeromeDefeat::
    .string "'Oxygen depleted... dying...'$"

Route21_South_Text_JeromePostBattle::
    .string "YOYO IS WAITIN!$"

Route21_South_Text_RolandIntro::
    .string "'JOURNEY BEGINS! SET SAIL FOR THE\p"
    .string "ISLANDS!'$"

Route21_South_Text_RolandDefeat::
    .string "GAME OVER!$"

Route21_South_Text_RolandPostBattle::
    .string "'Your Skin's on Fire!'$"

Route21_South_Text_ClaudeIntro::
    .string "FISH FLEE IN FEAR$"

Route21_South_Text_ClaudeDefeat::
    .string "'Fishin' Frenzy: 0/5'$"

Route21_South_Text_ClaudePostBattle::
    .string "'Wild Tuna nearby!'$"

Route21_South_Text_NolanIntro::
    .string "'Fishing for luck... Come on,\p"
    .string "buddy!'$"

Route21_South_Text_NolanDefeat::
    .string "FLAMES NICKED BY ROCKET FLYBY$"

Route21_South_Text_NolanPostBattle::
    .string "'WONDERFUL CATCH! 10 XP'$"

Route21_North_Text_LilIntro::
    .string "NO WAY! IANA LONER.$"

Route21_North_Text_LilDefeat::
    .string "'You're tellin' me!'$"

Route21_North_Text_LilPostBattle::
    .string "'Are ye sure ye can't handle a\p"
    .string "little more adventurin', LIL?'$"

Route21_North_Text_LilNotEnoughMons::
    .string "'Two strong friends, eh? Want me\p"
    .string "to bring Larry and Lola.'$"

Route21_North_Text_IanIntro::
    .string "You: 'Gotcha! Now she's fit and\p"
    .string "fierce!'$"

Route21_North_Text_IanDefeat::
    .string "'Focus! Not now, Sis!'$"

Route21_North_Text_IanPostBattle::
    .string "'RUN FASTER, IAN! LOSE THE\p"
    .string "PORKCHOPS!'$"

Route21_North_Text_IanNotEnoughMons::
    .string "ATALATAL! CHOOSE 2 POKEMON,\p"
    .string "Trainer!$"

