FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "'Ha! Those POKeMON must be tired!'$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "' Ancient treasures await within'$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "A STONE OF LIGHT!$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "You now have Egg 1 in your\p"
    .string "inventory!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "'Party full, come back later'$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "'Egg sis says thanks!'$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "'bundle found: power egg'$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "CITY OF GOLD APPROACHING!$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "'Welcome to PETALBURG FOREST'$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "'Level 5: Charmander's Fire Fang!'$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "'The FURRY FUTURE IS YOURS!'$"

