FuchsiaCity_Gym_Text_KogaIntro::
    .string "You must be JOKING!$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "YOU GOT IT!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "TOXIC ADJUSTS!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Congratulations! Defense boosted!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "'Teach point: Learned Hyper Beam!'$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Utilize TM06: TOXIC!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "GYM'S NEW FLOOR IS READY$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "'You've gotta think two moves\p"
    .string "ahead!'$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "STRANGE PORTAL APPEARS!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "'Time to test your mettle in the\p"
    .string "Arena!'$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "'Newfangled Skills Unlocked: Sneak\p"
    .string "Attack'$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "'Critical damage inflicted! You've\p"
    .string "been defeated!'$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "'Hmmm, my skills still lacking...'$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "BRING IT ON!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "'Ah-ha! You shoulda watched your\p"
    .string "back!'$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "POISON MEINSTI$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "BANZAI PRESS!$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "CONGRATS! YOU'VE GOT THE STAR!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "WIPE WALL'S TRAP GATE OPENS!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "'Whispers of the Forest: Master\p"
    .string "Koga's wisdom unfolds...'$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "'YOU HEAR A RUSTLING IN THE\p"
    .string "THICKET.'$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "'A long road ahead awaits...'$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "'Shadow of the Ancients'$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "'Well done adventurer!'$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Casts outlining words...$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Need gapfind'r now!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "'Shadows watch yours slowly\p"
    .string "vanish'$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "Gotta Beat Koga!$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "'Defeat Rival to claim the Badge!'$"

