#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokedex order
enum {
    NATIONAL_DEX_NONE,
    NATIONAL_DEX_TEST,
    NATIONAL_DEX_TESTTWO,

};

#define KANTO_DEX_COUNT     NATIONAL_DEX_TESTTWO
#define JOHTO_DEX_COUNT     NATIONAL_DEX_TESTTWO
#define NATIONAL_DEX_COUNT  NATIONAL_DEX_TESTTWO

// Hoenn Pokedex order
enum {
    HOENN_DEX_NONE,
    HOENN_DEX_TEST,
    HOENN_DEX_TESTTWO,

};

#define HOENN_DEX_COUNT HOENN_DEX_TESTTWO

#endif // GUARD_CONSTANTS_POKEDEX_H
