#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_TEST 1
#define SPECIES_TESTTWO 2

#define KANTO_SPECIES_END TESTTWO
#define SPECIES_EGG 3

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
