#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define ${SPECIES_PLACEHOLDER} 1
#define ${SPECIES_PLACEHOLDER}TWO 2

#define KANTO_SPECIES_END ${SPECIES_PLACEHOLDER}TWO
#define SPECIES_EGG 3

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
