SafariZone_West_Text_RestHouse::
    .string "'Welcome weary traveler! Rest\p"
    .string "well, but beware the whispers in\n"
    .string "the night...'$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "WARDEN FOUND663$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "Explore the west woods for clues\p"
    .string "to uncover the SECRET HOUSE!$"

SafariZone_West_Text_AreaSign::
    .string "'You're getting closer to the\p"
    .string "secret!'$"

