VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Yappity yaps! I FISH ALL DAY!$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "You've got a gift from me, a wise\p"
    .string "old hermit! Use the fishin' lure\n"
    .string "to hook a nice catch!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "'Time to catch some biguns!'$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "'New waters ahead! Fish temp:\p"
    .string "65.0. Good luck, angler!'$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "'Item missed!'$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "FLOUNDER SWARMING!$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "'TREEHOUSE IS FULL!'$"

