SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "Rest YES/NO$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "Town's Vigor seems to be buoyed by\p"
    .string "your strong convictions.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "'BROTHER?! WHO ARE YOU CALLING\p"
    .string "BROTHER?!'$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "'Watch it, pal. I'm not your\p"
    .string "sibling!'$"

