CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "Choose wisely, trainer!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "'Exploring Cavern near Cerulean\p"
    .string "sought. Desperate clues needed.'$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "WADE CAUTION: AMBER LYRICS LOOM\p"
    .string "AHEAD!$"

