Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Poke Balls at the ready!$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "'WATCH YOUR STEP, CERULEAN!'$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "WANT MAGIKARP FOR Y500?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "Yeah! Buy MAGIKARP for Y500?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "'That fish won't even notice\p"
    .string "you're gone!'$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "WHO DO YOU THINK YOU ARE?$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Your party is full!$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "YOU DONT HAVE ENOUGH GOLD COINS!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "'PAY UP, PAL!'$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "INSERT FIGHTING POISON$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "EXTRA! EXTRA! Read all about it!\p"
    .string "BETELGEUSE BOMBED: Alien\n"
    .string "scoundrels wreak havoc on city\p"
    .string "centre!$"

