PokemonLeague_BrunosRoom_Text_Intro::
    .string "'Prepare to face destruction,\p"
    .string "PLAYER!'$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "'Prepare to face destruction,\p"
    .string "PLAYER!'$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "'Game Over: The Darkness Consumes\p"
    .string "You!'$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "'Mission accomplished!'$"

