SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "'Take a stabilizer, matey!'$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "YOUR CREW'S CHEER SHOOTS UP!$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "You got the Hidden Machine!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "HARDENED FLESH SEIZED!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "PRESS START TO START CHOPPING!$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "Farewell, until our return to\p"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "INSUFFICIENT SPACE!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "GAZING INTO THE ABYSS...$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Ask for Dramamine, matey!$"

