PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "Gotta stop rival's plans!$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "You want to process the request\p"
    .string "and deliver the required snippet,\n"
    .string "right? Here's your snippet:   WISH\p"
    .string "I COULD HEAR MORE!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Whaddaya mean he's lazy?$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "Got Map!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Oversized Cargo!$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "You are in FOREST clearance.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "You find a weary POKeMON.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "MAP: KANTO REGIONS PARTIAL\p"
    .string "CREATED.$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "'Rare Volume Found: 'Pokemon\p"
    .string "Evolution Secrets''$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "'Professor's Pooch Polishin' 500'$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "GRANNY'S IN YOUR HOTEL ROOM$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "PAMpered PUP 'Bingo', Loyal LYNX\p"
    .string "'Whiskers', or Cunning CAT\n"
    .string "'Midnight'?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "'Polishing up... objectives:\p"
    .string "COMPLETED!'$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} looks dreamily content…\p"
    .string "{COLOR RED}DAISY: There you go! All done.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} looks dreamily content…\p"
    .string "{FONT_FEMALE}DAISY: There you go! All done.\n"
#endif
    .string "See? Doesn't it look nice?\p"
    .string "Giggle…\n"
    .string "It's such a cute POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "EGG NOT GROOMED$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "IT'S ME, Pika!$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "POKeMON LOVE SHINES BRIGHT!$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "'Your Joy is Contagious!'$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "PET POLICE APPROVE!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "'Hearts warm with each new dawn.'$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "It's gonna take some time.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "PITY THE BEAST!$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "THUNDER SHOCK USER!$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "You find a rare CLEFAIRY!$"

