SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "REPUTATION FELLspd Limit: 1000pt$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "'Rely on comrades, always!'$"

SilphCo_8F_Text_Grunt1Intro::
    .string "TIME'S UP, TRAVELER!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "'GROUT!'$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "You don't think I'm alone out\p"
    .string "here, do you?$"

SilphCo_8F_Text_ParkerIntro::
    .string "NOT ON MY WATCH!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "DEFEAT OFFICIAL! TRY AGAIN?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "'BEWARE: TRAPS LURK!'$"

SilphCo_8F_Text_Grunt2Intro::
    .string "'Meet me in Joe's Garage, bro!'$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "WELCOME TO CASTLE CADENZIO!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "'Mediocre siblings ahead!'$"

SilphCo_8F_Text_FloorSign::
    .string "ERROR: AUTHORIZATION REQUIRED$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "'A dark future looms ahead...'$"

