SSAnne_2F_Room4_Text_LamarIntro::
    .string "'A rare POKeMON's power!'$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "'Welcome, Hero! Press Enter to\p"
    .string "proceed.'$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "You've caught a rare Mew!$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "WHO ARE YOU?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "CHILLIN' TIME APPROACHING$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "WANT TO TRADE?$"

