OneIsland_KindleRoad_Text_MariaIntro::
    .string "Clear skies ahead! Ready for\p"
    .string "takeoff!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "' ';  ;$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "'BABE'S CAREFULLY PREPARED FACE\p"
    .string "UNDER THREAT!'$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "'Ouch! Shade is a luxury, not a\p"
    .string "right!'$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "'GET IT TOGETHER, WARRIOR!'$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "'' Try one on, i dare ya!$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Climb slow, burning winds strong!$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "'BRING IT ON, GRUDGE!'$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "You See Nothing But Endless Blue$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "'Ready for some relaxation? Think\p"
    .string "again!'$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "'Congrats, JOATnik! You survive\p"
    .string "initial blast wave!'$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "'DIVE INTO ACTION!'$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "GIT IT IN, FISH!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "'GOLDEN CHIPS: 0, LIVES: 3'$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "'AH! FISH 'N' RAGE!'$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "Potions available: HP 5, STR 2$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "'Ha! You think you can take me\p"
    .string "down?'$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "'Wise words from the elderly\p"
    .string "sage!'$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "Train regimen updated.$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "'RUN! THE MONSTER CHASES THEE!'$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "' THE PATH TO GLORY AWAITS!'$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "'WARM SAND BETWEEN TOES... COCONUT\p"
    .string "TREES SWAYING GENTLY'$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "'Whispers echo through the\p"
    .string "void...'$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "You're feeling a bit worn out...\p"
    .string "Zzz...$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "Equip Warrior Garb$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "'ANCHOR'S AWAY! THE ISLAND'S CURSE\p"
    .string "HOUNDS YOU.'$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "Kimono Shop: 'New arrivals!$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "'TIME TO GRILL!'$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "Karma! Your ship's outta fuel!\p"
    .string "Grab some at nearest outpost!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "WARNING: Toxins Ahead!$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "'GOT 'EM! CHALLENGE ACCEPTED!'$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "'YOU FINALLY SUMMONED THE COURAGE\p"
    .string "TO ENTER THE CAVE'$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "'Food Urizen: NEARBY CABIN'$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "'Unstoppable duo awakens!'$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "'WHAT IN THE WORLD...?!'$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "'WAIT TILL YOU SEE THEODORE IN\p"
    .string "ACTION!'$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "'The challenge awaits, trainer!'$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "'Bring it on, punks!'$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "'TOO HOT!'$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "'Impossible! Your partnership is\p"
    .string "DOOMED!'$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "Yeah, bring it on!$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Descend into the Canyon!$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "INTEGERITY TEST: PREPARE THYSELF!$"

