PokemonTower_4F_Text_PaulaIntro::
    .string "You scream as the ghostly\p"
    .string "apparition disappears!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "'Haunting the Basement'$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Suddenly, a figure looms ahead...$"

PokemonTower_4F_Text_LaurelIntro::
    .string "FATE IS SEALED!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "'GRAIL UNDER ATTACK!'$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "'Mystery aeros'$"

PokemonTower_4F_Text_JodyIntro::
    .string "KOING TO HELL!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "'WELCOME, TRAVELER'$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "'In perpetual slumber, their\p"
    .string "essencesn bound to these dread\n"
    .string "waters.'$"

