CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "'A must-use against those pesky\p"
    .string "Rattata!'$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "BUY REVIVE!$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "'Rare: Lucky Pills! 500G EACH'$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "YOU WONDER...$"

