SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "You're the infamous one they're\p"
    .string "talkin' about?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "YOU FOIL THEIR PLANS AGAIN!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "'A lone tot, aimlessly strolling.'$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "EXPLOSION INVOLVED!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Banzai Bill has its sights on you!$"

SilphCo_5F_Text_BeauIntro::
    .string "'Research: mog away!'$"

SilphCo_5F_Text_BeauDefeat::
    .string "'OOF! You've been hit!'$"

SilphCo_5F_Text_BeauPostBattle::
    .string "'POKe TRIED, BUT IT WON'T GO!'$"

SilphCo_5F_Text_DaltonIntro::
    .string "WELCOME TO CREEPY CREECH!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "INCOMING ATTACK smlouassistant\p"
    .string "WATER JET STREAM APPROACHING\n"
    .string "PLEASE DUCK$"

SilphCo_5F_Text_DaltonPostBattle::
    .string " Carefully climb upwards$"

SilphCo_5F_Text_Grunt2Intro::
    .string "'globally recognized gang, at your\p"
    .string "service!'$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "'Ah-choo!'$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Gotcha!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "PROGRESS REPORT lz  Porygon, the\p"
    .string "Digital Type, successfully\n"
    .string "birthed!$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "POKEMON DOCTORS NEEDED!$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "NEW EVOLUTION CHAIN DISCOVERED!$"

SilphCo_5F_Text_FloorSign::
    .string "'Enter for meeting with Director\p"
    .string "Monday.'$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "'Be careful, I hear his\p"
    .string "RuffiannGang is hiding nearby...'$"

