LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Items like those can be found in\p"
    .string "caves.p$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "REVIVES: 3 - 500 Poke$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "'Prepare for dual battle!'$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "Found! Rare Golden Orb worth\p"
    .string "5000Y!$"

