SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "YOU DARE TO CHALLENGE THE KARATE\p"
    .string "MASTER?$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "'Game Over... Try Again?'$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Pikachu or Charmander?$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "'Discipline and Honor Await!'$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "'Remove footwear to proceed, brave\p"
    .string "adventurer!'$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "YOU GIVE UP TOO EASY!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "Faceless minions beware!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "BRING IT ON, CHAMP!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "YOU SCORED A BLOkish SHOT!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "YOU'VE BEEN ISSUED A CHALLENGE!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "BRUTE FORCE ENGAGED!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "'Fatigued Miner'$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "'Gravekeeper: Beware its curse!'$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "BRUH,DATS ITCHY FIST!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "GAME OVER!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "WARRIOR'S GROVE$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "YOU JUST MET YOUR MATCH!$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "You received the Golden Belt!$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "WANT BATTLE?!$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "The Way of the Karate Master\p"
    .string "grants you... Spirit Energy!$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "'Treasure chest ahead! Watch yer\p"
    .string "back!'$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "CREEPING HORDES OF DOOMambreeds\p"
    .string "ahead!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "A mysterious stranger lurks in the\p"
    .string "shadows, seeking revenge...$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "Furious ninja sense revving!$"

