Aide_Text_HaventCaughtEnoughMonsForItem::
    .string "Whoops! You've got only 5 kinds of\p"
    .string "POKeMON! You need 8 kinds if you\n"
    .string "want the Master Badge.$"

Aide_Text_GetEnoughMonsComeBackForItem::
    .string "When you get fire, water kinds of\p"
    .string "POKeMON, come back for the\n"
    .string "Professor.$"

Aide_Text_DontHaveAnyRoomForItem::
    .string "'Make some space, stat!'$"

