@ The text here is a copy/paste from Hoenn's various berry NPCs, all unused and untranslated

PetalburgCity_Gym_Text_GiveEnigmaBerry::
    .string "'A rare fruit! Enjoy it, PLAYER!'$"

Route104_Text_PlantBerriesInSoilTakeThis::
    .string " Gather three rare seeds in one\p"
    .string "place!$"

Route104_Text_TrainersOftenMakeMonHoldBerries::
    .string "NEED TRAINER APPROVAL$"

Route111_Text_WateredPlantsEveryDayTakeBerry::
    .string "Fresh water does the trick! Many\p"
    .string "fish poured in!$"

Route111_Text_TryToMakeRedPokeblock::
    .string "FILLING UP THE RED POLOVCK!$"

Route111_Text_WhatColorBerriesToLookForToday::
    .string "'Seek Colorful Ki Fruit today!'$"

Route114_Text_GatheringBerriesForContest::
    .string "Gather Berry prize!$"

Route114_Text_GoodLuckToYouToo::
    .string "COME ON, FIGHTER!$"

Route114_Text_WhatBerriesShouldIPlantToday::
    .string "Choose wisely, adventurer...$"

Route120_Text_PokeblocksExpressionOfLove::
    .string "Pika! Toss box, arise Wild Pollock\p"
    .string "appears! CATCH IT!$"

Route120_Text_YouUnderstandTakeThis::
    .string "GIFT APPEARS!$"

Route120_Text_OwnImpressionsImportantTakeThis::
    .string "'Leave it to me! Got it!'$"

Route120_Text_BerryIsRareRaiseItWithCare::
    .string "Cultivate rare fruit!$"

Route120_Text_IllGetMoreBerriesFromBerryMaster::
    .string "'GOT IT, THANKS OAK dwrIE!'$"

LilycoveCity_Text_BerrySuitsYou::
    .string "SUIT FITS Me PERFECTLY.$"

LilycoveCity_Text_BecauseYoureTrainer::
    .string "'HOLD THE LINE, CHAMPION!'$"

LilycoveCity_Text_PokeblocksSuitPokemon::
    .string "SIMPLE POKENIC FOR YOU, BUT NOT\p"
    .string "FOR POKE'MON$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry::
    .string "'Come, adventurer, and behold my\p"
    .string "world-fine flora!'$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother::
    .string "ONE MORE SHOT!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop::
    .string "Meet Sakura-san at Sunflower Shop\p"
    .string "near Kanazumi!$"

Route123_BerryMastersHouse_Text_DoneForToday::
    .string "FINISH LINE AHEAD!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately::
    .string "Gramps' breezewood skills top-\p"
    .string "notch!$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis::
    .string "FINALLY! YOU'VE OBTAINED THE\p"
    .string "ANCIENT scroll!$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis::
    .string "WAKE UP, CHUMP! GRAB THAT AND GET\p"
    .string "MOVING!$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife::
    .string "You've caught 'em, 4 old men!$"

Route123_BerryMastersHouse_Text_Ah::
    .string "'Treasure Chest Ahead!'$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop::
    .string "Welcome to Sun Toka Florist!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries::
    .string "WANT WATERFRUIT?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries::
    .string "Taro Kun! Nice one!$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation::
    .string "Got a rare Bug Fruit!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness::
    .string "THE MIRTHFUL GIGGLE ENSUES$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis::
    .string "TRY YOUR BEST!$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation::
    .string "GEDDON WITH CARE! WATER IT, OR\p"
    .string "IT'LL WITHER AWAY!$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers::
    .string "You earn 500 Omocha!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries::
    .string "Mix berries well to make a\p"
    .string "Pokemon's face appear!$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese::
    .string "Wonderful! Here's your nickname!\p"
    .string "It's Kiri!$"

SootopolisCity_Text_GiveYouThisBerryToo::
    .string "'WHOA, THANKS FOR THE\p"
    .string "STRAWBERRIES!'$"

SootopolisCity_Text_WhatKindOfWishInYourName::
    .string "MYSTERY ENSHRODS MY CLIENT'S\p"
    .string "DESIRED NAME$"

SootopolisCity_Text_LikeSeasonBornIn::
    .string "SEASONAL SURPRISE  WHAT LIES\p"
    .string "WITHIN SPRING'S BIRTH$"

SootopolisCity_Text_ThenILoveAutumn::
    .string "P Art seems smitten! What about\p"
    .string "you, friend?$"

SootopolisCity_Text_OhDoesntMatter::
    .string "WHAT WOULD YOU LIKE TO DO?$"

