@ The text here is a copy/paste from Hoenn's competitive brothers, the NPCs in Sootopolis who request to see big Barboach/Shroomish (Seedot/Lotad in Emerald). It's all unused and untranslated

SootopolisCity_Text_PleaseShowMeBigMon::
    .string "Want STRVAR1! Really curious! You\p"
    .string "got STRVAR1 too? Wait, show oji-\n"
    .string "san!$"

SootopolisCity_Text_GrandMonThanksForShowingMe::
    .string "NICELY DONE, STRONG GUY!$"

SootopolisCity_Text_ReceivedOneItem::
    .string "Aliceha Swordwo moratsuta!$"

SootopolisCity_Text_HuhBagIsCrammedFull::
    .string "' Looks like you're carryin' a\p"
    .string "heavy load!'$"

SootopolisCity_Text_IveSeenBiggerMonThanThisOne::
    .string "Familiars sneak up behind!$"

SootopolisCity_Text_QuiteSomethingButNotMon::
    .string "This nasty beast ain't no STRVAR1!$"

SootopolisCity_Text_TooBadDontHaveBigMon::
    .string "You've got none of those big\p"
    .string "STRVAR1s, eh?ApplicationUser\n"
    .string "laughs. Problem is, there ain't no\p"
    .string "such thing! Try showing us what's\n"
    .string "in store for next time!$"

SootopolisCity_Text_BiggestMonPlayersXCmColossus::
    .string "Dragonbeard's mighty !ATTACKER!!\p"
    .string "A ferocious creature 507cm in\n"
    .string "length has emerged!$"

