@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
    .string "Need a Pokemon raised, partner?$"

DayCare_Text_DoYouWantEgg::
    .string "Y: TAKE EGG$"

DayCare_Text_YourMonIsDoingFine::
    .string "STRVAR1: HUNGRY$"

DayCare_Text_IllKeepIt::
    .string "YOU RETRIEVED THE ITEM!$"

DayCare_Text_YouHaveNoRoomForIt::
    .string "'Too cluttered! Come back later!'$"

DayCare_Text_ReceivedEgg::
    .string "'Ah,A precious find!'$"

DayCare_Text_TakeGoodCareOfIt::
    .string "'Your precious clutch is yours\p"
    .string "alone.'$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
    .string "Get Poke Balls at Poke Mart!$"

DayCare_Text_YourMonsAreDoingFine::
    .string "You old pal! Your sword arm and\p"
    .string "quick reflexes are doing fine.$"

DayCare_Text_IWillKeepDoYouWantIt::
    .string "DO YOU REALLY THINK SO,\p"
    .string "ADVENTURER?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
    .string "TRAINER YOUR POKEMON HERE?$"

DayCare_Text_WhichMonShouldWeRaise::
    .string "'Choose wisely, young trainer...$"

DayCare_Text_WellRaiseYourMon::
    .string "Your Strength has increased! 5$"

DayCare_Text_WeCanRaiseOneMore::
    .string "Y/N$"

DayCare_Text_HusbandWasLookingForYou::
    .string "'MISSING IN ACTION. REWARD FOR\p"
    .string "INFO LEADING TO SAFE RETURN.'$"

DayCare_Text_FineThenComeAgain::
    .string "WHAT DO YOU WANT, STRANGER?$"

DayCare_Text_NotEnoughMoney::
    .string "You need 500 gold coins more!$"

DayCare_Text_TakeOtherOneBackToo::
    .string "LIES THEY BEG FOR NOTHING$"

DayCare_Text_ComeAgain::
    .string "You've made a bad gamble...$"

DayCare_Text_GoodToSeeYou::
    .string "'Ready for battle, I assume?'$"

DayCare_Text_YourMonHasGrownXLevels::
    .string "Your Strength has grown by 3.$"

DayCare_Text_YourPartyIsFull::
    .string "'PARDON THE DELAY, SIR'$"

DayCare_Text_TakeBackWhichMon::
    .string "Choose wisely, trainer!$"

DayCare_Text_ItWillCostX::
    .string "You can redeem it at\p"
    .string "theprepareiano in Hiron$"

DayCare_Text_HeresYourMon::
    .string "Pikachu, Level 5$"

DayCare_Text_TookBackMon::
    .string "Johnny reclaimed Billy's ball.$"

DayCare_Text_YouHaveJustOneMon::
    .string "'Sorry, no Pokemon to heal here!'$"

DayCare_Text_TakeYourMonBack::
    .string "NO WAY!$"

DayCare_Text_WhatWillYouBattleWith::
    .string "You'll be in position.$"

DayCare_Text_Huh::
    .string "'Flicker enters the game!'$"

