@ The text here is a copy/paste from Hoenn's Eon Ticket event, all unused and untranslated

Text_DadLetterArrivedForYouPlayer::
    .string "'You've got mail!'$"

Text_DadPassForShipNeverSeenBefore::
    .string "You stumble upon a mysterious\p"
    .string "ticket... dojo?$"

Text_FerryToSlateportOhThatPass::
    .string "ALIEN ALARM UPON YOU!$"

Text_YoureOneWhoBroughtOddPass::
    .string "Who dares arrive with whacky\p"
    .string "ticket?$"

Text_NothingHereSailBackToLilycove::
    .string "What's your move?  Left or Right?$"

Text_SailHomeWeWill::
    .string "'Returning? Ha! Not today!'$"

Text_AsYouLikeThen::
    .string "'It's up to you, kid.'$"

SouthernIsland_Interior_Text_Sign::
    .string "'FALSE THOUGHTS HAUNT YOUR\p"
    .string "DREAMS...'$"

SouthernIsland_Exterior_Text_Sign::
    .string "Your heart be bound by shadows.$"

