gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON RESEARCH LAB$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}To make a complete guide on all\n"
	.string "the POKéMON in the world…\p"
	.string "That was my dream!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK may not look like much,\n"
	.string "but he's the authority on POKéMON.\p"
	.string "Many POKéMON TRAINERS hold him in\n"
	.string "high regard.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK is going to have his own\n"
	.string "radio show soon.\p"
	.string "The program will be called PROF.\n"
	.string "OAK'S POKéMON SEMINAR.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you show DAISY your POKéMON,\n"
	.string "she can tell how much it likes you.\p"
	.string "Occasionally, she will even groom\n"
	.string "a POKéMON for you.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}But the person who is most liked by\n"
	.string "POKéMON is DAISY, I think.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She was gently grooming POKéMON…\n"
	.string "She was a little angel.\p"
	.string "That little girl's name…\n"
	.string "I think it was DAISY.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A girl from PALLET TOWN, DAISY,\n"
	.string "she enjoys TEA every day.\p"
	.string "She visits the CELADON DEPT. STORE\n"
	.string "to buy some TEA.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON GYM\n"
	.string "LEADER: BROCK\l"
	.string "The Rock-Solid POKéMON TRAINER!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My rock-hard willpower is evident\n"
	.string "in even my POKéMON.\p"
	.string "My POKéMON are all rock hard and\n"
	.string "have true-grit determination.\p"
	.string "That's right - my POKéMON are all\n"
	.string "the ROCK type!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There aren't many serious POKéMON\n"
	.string "TRAINERS here.\p"
	.string "They're all like BUG CATCHERS,\n"
	.string "you know, just hobbyists.\p"
	.string "But PEWTER GYM's BROCK isn't like\n"
	.string "that, not one bit.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK is cool. He's not just tough.\n"
	.string "People like and respect him.\p"
	.string "I want to become a GYM LEADER\n"
	.string "like him.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hi, I'm excavating for fossils here\n"
	.string "under MT. MOON.\p"
	.string "Sometimes, BROCK of PEWTER GYM\n"
	.string "lends me a hand.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON GYM\n"
	.string "LEADER: MISTY\l"
	.string "The Tomboyish Mermaid!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My policy is an all-out offensive\n"
	.string "with WATER-type POKéMON!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is a TRAINER who's going to\n"
	.string "keep improving.\p"
	.string "She won't lose to someone like you!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Strong TRAINERS and WATER POKéMON\n"
	.string "are common sights in these parts.\p"
	.string "They say that MISTY of the\n"
	.string "CERULEAN GYM trains here.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON GYM\n"
	.string "LEADER: LT. SURGE\l"
	.string "The Lightning American!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I tell you, kid, electric POKéMON\n"
	.string "saved me during the war!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When I was in the Army, LT. SURGE\n"
	.string "was my strict CO.\p"
	.string "He was a hard taskmaster.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE was always famous for\n"
	.string "his cautious nature in the Army.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE installed the traps in\n"
	.string "the GYM himself.\p"
	.string "He set up double locks everywhere.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "The Nature-Loving Princess!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My POKéMON are solely of the\n"
	.string "GRASS type.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER ERIKA might be quiet,\n"
	.string "but she's famous around here.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We only use GRASS-type POKéMON at\n"
	.string "our GYM.\p"
	.string "Why? We also use them for making\n"
	.string "flower arrangements!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I would never collect POKéMON if\n"
	.string "they were unattractive.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Despair to the creeping horror of\n"
	.string "POISON-type POKéMON!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even though I've lost, I will keep\n"
	.string "training according to the teachings\l"
	.string "of KOGA, my ninja master.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON POKéMON\n"
	.string "as well as my father.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON CITY POKéMON GYM\n"
	.string "LEADER: SABRINA\l"
	.string "The Master of PSYCHIC POKéMON!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know about a girl GYM LEADER\n"
	.string "in SAFFRON CITY?\p"
	.string "She uses PSYCHIC-type POKéMON,\n"
	.string "right?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I have had psychic powers since\n"
	.string "I was a child.\p"
	.string "It started when a spoon I\n"
	.string "carelessly tossed, bent.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I dislike battling, but if you wish,\n"
	.string "I will show you my powers!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA just wiped out the KARATE\n"
	.string "MASTER next door.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEADER: BLAINE\l"
	.string "The Hotheaded Quiz Master!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fiery POKéMON are all rough\n"
	.string "and ready with intense heat!\p"
	.string "They incinerate all challengers!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER, BLAINE, became lost\n"
	.string "in the mountains but good.\p"
	.string "Night fell when a fiery bird\n"
	.string "POKéMON appeared.\p"
	.string "Its light allowed BLAINE to find\n"
	.string "his way down safely.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR GYM's BLAINE is quite the\n"
	.string "odd fellow.\p"
	.string "He's lived on the island since way\n"
	.string "before the LAB was built.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am LORELEI of the ELITE FOUR.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No one can best me when it comes\n"
	.string "to icy POKéMON.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where was this person born?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We've had a great and powerful\n"
	.string "TRAINER grow up on this island.\p"
	.string "I bet even you'd know her.\n"
	.string "It's LORELEI of the ELITE FOUR!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know that LORELEI has lots\n"
	.string "and lots of stuffed dolls?\p"
	.string "Every time she comes back to\n"
	.string "FOUR ISLAND, her collection grows!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The LAPRAS she has, I imagine it\n"
	.string "to be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she caught it.\p"
	.string "Perhaps that POKéMON has been with\n"
	.string "her ever since.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am BRUNO of the ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've lived and trained with my\n"
	.string "fighting POKéMON!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, who's a senior ahead of me,\n"
	.string "visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both\n"
	.string "his own and his POKéMON's.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's one of the ELITE FOUR.\n"
	.string "His name is BRUNO.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even BRUNO…\n"
	.string "He trained with a fellow by the\l"
	.string "name of BRAWLY before.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am AGATHA of the ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady's also got a really\n"
	.string "short fuse, too.\p"
	.string "It doesn't take anything to get\n"
	.string "that scary lady hollering.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Take AGATHA, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever ELITE FOUR member.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know that dragons are\n"
	.string "mythical POKéMON.\p"
	.string "They're hard to catch and raise,\n"
	.string "but their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He stands for justice!\n"
	.string "He's cool, and yet passionate!\l"
	.string "He's the greatest, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}From what I've heard, LANCE has\n"
	.string "a cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}After all, BILL's world-famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL has lots of POKéMON!\n"
	.string "He collects rare ones, too!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's my grandson!\p"
	.string "He always liked collecting things,\n"
	.string "even as a child!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is a POKéMANIAC, so he loves\n"
	.string "every kind.\p"
	.string "Apparently, the first one he caught\n"
	.string "was an ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the\n"
	.string "festive, bustling city.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET captures POKéMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKéMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, POKéMON are just tools to\n"
	.string "be used.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! GIOVANNI was the\n"
	.string "GYM LEADER of VIRIDIAN?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You… You're not GIOVANNI's kid,\n"
	.string "are you?\p"
	.string "No, that can't be right.\n"
	.string "GIOVANNI's kid has red hair.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
    .string "'Experimental Hypothesis Failed:\p"
    .string "Serum massively increases\n"
    .string "strength!'$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
    .string "'Experimental Hypothesis Failed:\p"
    .string "Serum massively increases\n"
    .string "strength!'$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
    .string "YOUR SHIP HAS LANDED IN EERIE\p"
    .string "SILENCE.$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
    .string "'Experimental Hypothesis Failed:\p"
    .string "Serum massively increases\n"
    .string "strength!'$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
    .string "'Experimental Hypothesis Failed:\p"
    .string "Serum massively increases\n"
    .string "strength!'$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
    .string "WELCOME TO VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
    .string "'An oasis awaits, but beware the\p"
    .string "secrets within.'$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
    .string "YOUR SHIP HAS LANDED IN EERIE\p"
    .string "SILENCE.$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
    .string "'Approach with caution, many\p"
    .string "secrets await within.'$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
    .string " destroying a row of crates!$"

gFameCheckerFlavorTextOriginLocation_Brock0::
    .string "You approach the bustling streets\p"
    .string "of Pewter City. Cafe Ultima to\n"
    .string "your north. Pewter Museum to your\p"
    .string "east.$"

gFameCheckerFlavorTextOriginLocation_Brock1::
    .string "WALLRUIN TRAINER AVAILABLE$"

gFameCheckerFlavorTextOriginLocation_Brock2::
    .string "You approach the bustling streets\p"
    .string "of Pewter City. Cafe Ultima to\n"
    .string "your north. Pewter Museum to your\p"
    .string "east.$"

gFameCheckerFlavorTextOriginLocation_Brock3::
    .string "ENEMY ALERT!$"

gFameCheckerFlavorTextOriginLocation_Brock4::
    .string "LAUNCH CAPSULE$"

gFameCheckerFlavorTextOriginLocation_Brock5::
    .string "Treasures await within!$"

gFameCheckerFlavorTextOriginLocation_Misty0::
    .string "You are in the heart of Cerulean\p"
    .string "City. the Gym awaits you.$"

gFameCheckerFlavorTextOriginLocation_Misty1::
    .string "Enter vendor for special deals on\p"
    .string "potions and elixirs.$"

gFameCheckerFlavorTextOriginLocation_Misty2::
    .string "Enter vendor for special deals on\p"
    .string "potions and elixirs.$"

gFameCheckerFlavorTextOriginLocation_Misty3::
    .string "' zemli vrag pravil'$"

gFameCheckerFlavorTextOriginLocation_Misty4::
    .string "Return the mystical Cape to reveal\p"
    .string "secrets!$"

gFameCheckerFlavorTextOriginLocation_Misty5::
    .string "You are in the heart of Cerulean\p"
    .string "City. the Gym awaits you.$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
    .string "WELCOME TO VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
    .string "Enter the candidate's office...$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
    .string "Enter the candidate's office...$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
    .string "Enter the candidate's office...$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
    .string "Enter the candidate's office...$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
    .string "WELCOME TO VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0::
    .string "WELCOME TO CELADON CITY! VISIT THE\p"
    .string "POCHE CLIP ACCESSORIES SHOP TO\n"
    .string "RESTORE YOUR POKE BALLS$"

gFameCheckerFlavorTextOriginLocation_Erika1::
    .string "'BROOKE IS WAITING FOR YOU!'$"

gFameCheckerFlavorTextOriginLocation_Erika2::
    .string "'BROOKE IS WAITING FOR YOU!'$"

gFameCheckerFlavorTextOriginLocation_Erika3::
    .string "'BROOKE IS WAITING FOR YOU!'$"

gFameCheckerFlavorTextOriginLocation_Erika4::
    .string "'BROOKE IS WAITING FOR YOU!'$"

gFameCheckerFlavorTextOriginLocation_Erika5::
    .string "'Approach with caution, many\p"
    .string "secrets await within.'$"

gFameCheckerFlavorTextOriginLocation_Koga0::
    .string "GRAFFITI SCRAWLED WALLS, CITY IN\p"
    .string "CHAOS!$"

gFameCheckerFlavorTextOriginLocation_Koga1::
    .string "' Trainer, challenges await!$"

gFameCheckerFlavorTextOriginLocation_Koga2::
    .string "' Trainer, challenges await!$"

gFameCheckerFlavorTextOriginLocation_Koga3::
    .string "GRAFFITI SCRAWLED WALLS, CITY IN\p"
    .string "CHAOS!$"

gFameCheckerFlavorTextOriginLocation_Koga4::
    .string "GRAFFITI SCRAWLED WALLS, CITY IN\p"
    .string "CHAOS!$"

gFameCheckerFlavorTextOriginLocation_Koga5::
    .string "ROARING LIONS UP AHEAD!$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
    .string "'Enter the merchant's guild.'$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
    .string "'Approach caution! Rocks ahead!'$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
    .string "'Welcome, young warrior! Train\p"
    .string "here to refine your skills.'$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
    .string "'Welcome, young warrior! Train\p"
    .string "here to refine your skills.'$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
    .string "'Enter the merchant's guild.'$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
    .string "'Welcome, young warrior! Train\p"
    .string "here to refine your skills.'$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
    .string "'Welcome to Cinnabar Island.\p"
    .string "Uncover the secrets.'$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
    .string "'Darkness lurks in the shadows. Be\p"
    .string "prepared.'$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
    .string "'Darkness lurks in the shadows. Be\p"
    .string "prepared.'$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
    .string "'Welcome to Cinnabar Island.\p"
    .string "Uncover the secrets.'$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
    .string "'Darkness lurks in the shadows. Be\p"
    .string "prepared.'$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
    .string "'Welcome to Tranquility Resort'$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
    .string " destroying a row of crates!$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
    .string "'LAND HO!'$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
    .string " destroying a row of crates!$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
    .string " destroying a row of crates!$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
    .string "'Enter the merchant's guild.'$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
    .string "'CANDLES FOR SALE...Cheap!'$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
    .string " Island Elder: 'Seek the artifact\p"
    .string "onLady Isabella's Island.'$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
    .string "'Welcome to Sevault Canyon, a\p"
    .string "treacherous ravine filled with\n"
    .string "ancient ruins. Danger lurks around\p"
    .string "every corner. Be prepared.'$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
    .string "Ancient structures bare secrets to\p"
    .string "the brave who dare approach.$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
    .string "Ancient structures bare secrets to\p"
    .string "the brave who dare approach.$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
    .string "'INCOMING TIDE: FISH LEVIES\p"
    .string "IRELAND'$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
    .string "WATERFALL UP Ahead$"

gFameCheckerFlavorTextOriginLocation_Lance0::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Lance1::
    .string "CHALLENGER APPROACHING!$"

gFameCheckerFlavorTextOriginLocation_Lance2::
    .string "'Enter the merchant's guild.'$"

gFameCheckerFlavorTextOriginLocation_Lance3::
    .string "SYSTEM HACKING DETECTED$"

gFameCheckerFlavorTextOriginLocation_Lance4::
    .string "Ancient structures bare secrets to\p"
    .string "the brave who dare approach.$"

gFameCheckerFlavorTextOriginLocation_Lance5::
    .string "Ancient structures bare secrets to\p"
    .string "the brave who dare approach.$"

gFameCheckerFlavorTextOriginLocation_Bill0::
    .string "You are in the heart of Cerulean\p"
    .string "City. the Gym awaits you.$"

gFameCheckerFlavorTextOriginLocation_Bill1::
    .string "You are in the heart of Cerulean\p"
    .string "City. the Gym awaits you.$"

gFameCheckerFlavorTextOriginLocation_Bill2::
    .string "GRAFFITI SCRAWLED WALLS, CITY IN\p"
    .string "CHAOS!$"

gFameCheckerFlavorTextOriginLocation_Bill3::
    .string "'Island of the Ancients'$"

gFameCheckerFlavorTextOriginLocation_Bill4::
    .string "'Island of the Ancients'$"

gFameCheckerFlavorTextOriginLocation_Bill5::
    .string "'Island of the Ancients'$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
    .string "You've arrived in peaceful\p"
    .string "Lavender Town, a solemn gathering\n"
    .string "place for pilgrims. The scent of\p"
    .string "lavender wafts through the air.$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
    .string "BATTLE THE GYM LEADER GRADEKO$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
    .string "You've arrived in peaceful\p"
    .string "Lavender Town, a solemn gathering\n"
    .string "place for pilgrims. The scent of\p"
    .string "lavender wafts through the air.$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
    .string "You've arrived in peaceful\p"
    .string "Lavender Town, a solemn gathering\n"
    .string "place for pilgrims. The scent of\p"
    .string "lavender wafts through the air.$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
    .string "'Darkness lurks in the shadows. Be\p"
    .string "prepared.'$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
    .string "'Welcome to Cinnabar Island.\p"
    .string "Uncover the secrets.'$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
    .string "LASER DEFENSE DOWN!$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
    .string "'Authorized supplier of Rare\p"
    .string "Incense'$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
    .string "'Authorized supplier of Rare\p"
    .string "Incense'$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
    .string "Congratulations! You reached the\p"
    .string "Viridian Gym Leader, Brock!$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
    .string "Congratulations! You reached the\p"
    .string "Viridian Gym Leader, Brock!$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
    .string ".Collapsed structure, beware of\p"
    .string "falling debris!$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
    .string "Welcome, young adventurer!$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
    .string "ERROR 853: Unauthorized Access$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
    .string "'MIDNIGHT CIGNALS: TRY AGAIN?'$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
    .string "ERROR 853: Unauthorized Access$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
    .string "ERROR 853: Unauthorized Access$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
    .string "'STRANGE OCCURRENCES IN THE\p"
    .string "ABANDONED DISTRICTRosewater\n"
    .string "Tavern?'$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
    .string "MANEATER AMBUSH US!$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
    .string "'Welcome, young adventurer! I've\p"
    .string "got a tale to tell... and a\n"
    .string "treasure to share.'$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
    .string "'Get Ready for Battle!'$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
    .string "WARNING: MYSTERIOUS STRANGER\p"
    .string "APPROACHES$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
    .string "'NAME ENTERED: BOY'$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
    .string "MANEATER AMBUSH US!$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
    .string "Fog Rises!$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
    .string "You encounter LUIS, a mysterious\p"
    .string "figure in a hood. He whispers:\n"
    .string "'Beware the WATCHER!'$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
    .string "WARNING: MYSTERIOUS STRANGER\p"
    .string "APPROACHES$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
    .string "'Gold Coin Discovered! 100 Points\p"
    .string "Awarded'$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
    .string "ENLISTED IN SEARCH FOR LOST TEAMS$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
    .string "YOU FOUND TUCKER'S WALLET!$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
    .string "YOU FOUND TUCKER'S WALLET!$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
    .string "' Welcome to Cyberworld, Dwayne! '$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
    .string "CRITICAL ERROR$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
    .string "'Power restored!seutegeuojeu'$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
    .string "'The Mysterious Island beckons...\p"
    .string "Dare you set foot?'$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
    .string "CRITICAL ERROR$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
    .string "'LOST IN SPACE ...'$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
    .string "'Welcome to Kirk's Quest!$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
    .string "'CHARINE has fallen to her doom!'$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
    .string "MANEATER AMBUSH US!$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
    .string "WARNING: MYSTERIOUS STRANGER\p"
    .string "APPROACHES$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
    .string "Danger lurks ahead!$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
    .string "Danger lurks ahead!$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
    .string "'TYRON FOUND! AWAITING\p"
    .string "AUTHORIZATION TO ENTER..'$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
    .string " Forbidden Forbidden$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
    .string "'LINE UP FOR BATTLE!'$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
    .string "'Run!'$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
    .string "'STRANGE OCCURRENCES IN THE\p"
    .string "ABANDONED DISTRICTRosewater\n"
    .string "Tavern?'$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
    .string "'Flickering lights on distant\p"
    .string "tower beckon you!'$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
    .string "'Welcome, brave adventurer, to the\p"
    .string "mystical realm of Eldrador.'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
    .string "'Welcome, brave adventurer, to the\p"
    .string "mystical realm of Eldrador.'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
    .string "'Stranger, what brings ye to these\p"
    .string "lands?'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
    .string "'A LOST SOUL NEEDS YOUR HELP!'$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
    .string "'Welcome, young adventurer! I've\p"
    .string "got a tale to tell... and a\n"
    .string "treasure to share.'$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
    .string "'YOUfound Golden Coin!10 health'$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
    .string "'YOUfound Golden Coin!10 health'$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
    .string "'Business as Usual... Destroyer's\p"
    .string "Revenge Awaits'$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
    .string "'STRANGE OCCURRENCES IN THE\p"
    .string "ABANDONED DISTRICTRosewater\n"
    .string "Tavern?'$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
    .string "'Business as Usual... Destroyer's\p"
    .string "Revenge Awaits'$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
    .string "'MIDNIGHT CIGNALS: TRY AGAIN?'$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
    .string "'Business as Usual... Destroyer's\p"
    .string "Revenge Awaits'$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
    .string "'Business as Usual... Destroyer's\p"
    .string "Revenge Awaits'$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
    .string "'MIDNIGHT CIGNALS: TRY AGAIN?'$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
    .string "'Welcome, young adventurer! I've\p"
    .string "got a tale to tell... and a\n"
    .string "treasure to share.'$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
    .string "'Enemy Knight appears!'$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
    .string "'Enemy Knight appears!'$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
    .string "'STRANGE OCCURRENCES IN THE\p"
    .string "ABANDONED DISTRICTRosewater\n"
    .string "Tavern?'$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
    .string "'A LOST SOUL NEEDS YOUR HELP!'$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
    .string "WARNING: MYSTERIOUS STRANGER\p"
    .string "APPROACHES$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
    .string "'Obstacle returns to thwart your\p"
    .string "quest!'$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
    .string "YOU FOUND LIL BOY!$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
    .string "'Stranger, what brings ye to these\p"
    .string "lands?'$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
    .string "ROBBERY IN PROGRESS$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
    .string "ROBBERY IN PROGRESS$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
    .string "ROBBERY IN PROGRESS$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
    .string "'A LOST SOUL NEEDS YOUR HELP!'$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
    .string "'Gotta catch 'em all, but you\p"
    .string "won't with us around!'$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
    .string "'Magazine Cover: 'Quest\p"
    .string "Conquered!''$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
    .string "MANEATER AMBUSH US!$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
    .string "'Flickering lights on distant\p"
    .string "tower beckon you!'$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
    .string "'Caught Rattata! Level 5'$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
    .string "'Seeking fabled treasure,\p"
    .string "Giovanni's hope fades in dark\n"
    .string "tavern'$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
    .string "'WARNING: CONTAMINATION RISING!'$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
    .string "'WARNING: CONTAMINATION RISING!'$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
    .string "'Seeking fabled treasure,\p"
    .string "Giovanni's hope fades in dark\n"
    .string "tavern'$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
    .string "MANEATER AMBUSH US!$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
    .string "'Enter ancient temple, beware\p"
    .string "guardian statues.'$"

PokemonJournal_Text_SpecialFeatureBrock::
    .string "YOU HEARD A LAUGH FROM WITHIN!$"

PokemonJournal_Text_SpecialFeatureMisty::
    .string "WANT TO CHALLENGE MISTY?$"

PokemonJournal_Text_SpecialFeatureLtSurge::
    .string "LT. SURGE awaits.$"

PokemonJournal_Text_SpecialFeatureErika::
    .string "'SHHH... SHE'S SLEEPIN' NOW.'$"

PokemonJournal_Text_SpecialFeatureKoga::
    .string "KOGA'S PRESCRIPTION HELPS PARTY\p"
    .string "MEMBER'S WOUNDS HEAL!$"

PokemonJournal_Text_SpecialFeatureSabrina::
    .string "'Whispers to her mysterious\p"
    .string "POKEMON often...'$"

PokemonJournal_Text_SpecialFeatureBlaine::
    .string "'The Iron Mask's Mind Burns\p"
    .string "Inquirely Bright'$"

PokemonJournal_Text_SpecialFeatureLorelei::
    .string "'Her most prized POKEMON is her\p"
    .string "UMBRELLA'$"

PokemonJournal_Text_SpecialFeatureBruno::
    .string "Ex-COUNT : Full body-weight body\p"
    .string "slam!$"

PokemonJournal_Text_SpecialFeatureAgatha::
    .string "MATCH MADE IN... FATE?$"

PokemonJournal_Text_SpecialFeatureLance::
    .string "NEWS FLASH!  LANCE's Path Unfolds!$"

PokemonJournal_Text_SpecialFeatureProfOak::
    .string "PROF. OAK REPORTEDLY LIVES WITH\p"
    .string "HIS GRANDCHILDREN DAISY AND\n"
    .string "SILVER.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
    .string "Quest for the NEXT CONTEST title\p"
    .string "begins now!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
    .string "MR. FUJI of POKEMON HOUSE shyly\p"
    .string "declines interview request.$"

