@ Flavor text for interacting with various background objects

Text_Bookshelf::
    .string "LIBRARY ROOM: 'Books... and... OH\p"
    .string "NO! Ministop's Combo Deck!'$"

Text_NothingButPokemonBooks::
    .string "Unknown trainee lurking in\p"
    .string "shadows...$"

Text_ATownMap::
    .string "TOWN MAP  1. INN: Rest and recover\p"
    .string "2. MARKET: Buy supplies 3. TOWER:\n"
    .string "Explore the skies$"

Text_PokeMartShelf::
    .string "YOU FOUND THE POKEMON LAB!$"

Text_DishesPlatesNeatlyLinedUp::
    .string "'A CLEAN TABLE AWAITS!'$"

Text_Kitchen::
    .string "A RICH AROMA FEASTS THE EYES!$"

Text_Dresser::
    .string "'Examined: Dusty Dresser'$"

Text_Snacks::
    .string "'Grade-A Snax: 5 left'$"

Text_PokemartSign::
    .string "ITEMS  SUPPLIES INNERZhen$"

Text_PokecenterSign::
    .string "TRAINER, YOUR POKEMON RECOVERS\p"
    .string "HEALTH!$"

Text_Indigo_UltimateGoal::
    .string "'YOUR DEMISE IMMINENT!'$"

Text_Indigo_HighestAuthority::
    .string "'Authorization needed. Enter\p"
    .string "password or challenge Champion.'$"

Text_Food::
    .string "'MUNCHY BUFFET COMING UP!'$"

Text_Blueprints::
    .string "Technical Specifications\p"
    .string "deviceBOLT-3000 Schematic$"

Text_Painting::
    .string "The Pidgey looks radiant!$"

Text_PowerPlantMachine::
    .string "'ELECTRIC ENIGMA'$"

Text_Telephone::
    .string "'Voltage Failure: Do Not Connect'$"

Text_Computer::
    .string "Warning: Experimental Energy Surge\p"
    .string "Detected$"

Text_AdvertisingPoster::
    .string "VITAL VITAMINS: Revitalize your\p"
    .string "character with our potency-packed\n"
    .string "pills! SNAPSTICK SUPPLIES: Vital\p"
    .string "snacks for the modern adventurer!$"

Text_TastyFood::
    .string "'Mysterious Meat Medley'$"

Text_TrashBin::
    .string "'You're lost in the void...'$"

Text_Cup::
    .string "Pokecup Found!$"

Text_PolishedWindow::
    .string "Pristine Glass Ahead$"

Text_BeautifulSkyWindow::
    .string "'A radiant blue stretches'$"

Text_BlinkingLights::
    .string "WIDEBAND ALERT!$"

Text_NeatlyLinedUpTools::
    .string "GADGET WORKBENCH$"

Text_ImpressiveMachine::
    .string "'CYBERNETIC GIZMO: Operational'$"

Text_VideoGame::
    .string "FOREST APPROACHES. WARNING:\p"
    .string "SNAKES!$"

Text_Burglary::
    .string "VALUABLES MISSING!$"

Text_PlayerFacingTVScreen::
    .string "ZAP!$"

