Help_Text_WhatShouldIDo::
    .string "'DEFUSE THE BOMB IN 3 MINUTES.\p"
    .string "GOOD LUCK, SOLDIER!'$"

Help_Text_HowDoIDoThis::
    .string "Ancient Temple Ahead.$"

Help_Text_WhatDoesThisTermMean::
    .string "'GAME OVER: TRY AGAIN'$"

Help_Text_AboutThisGame::
    .string "'Area 4: Ancient Ruins. Watch out\p"
    .string "for lurking Shadow Beasts.'$"

Help_Text_TypeMatchupList::
    .string "Lightblade 4 vs Darkwyrm 6$"

Help_Text_Exit::
    .string "'NEXT ROOM?'$"

Help_Text_Cancel::
    .string "CANCELED.$"

Help_Text_TryDoingItOnYourOwn::
    .string "USING YOUR OWN STRENGTH, GENJI!$"

Help_Text_DescWhatShouldIDo::
    .string "'Tip: Use nearby objects to aid\p"
    .string "your escape!'$"

Help_Text_DescHowDoIDoThis::
    .string "'REFER TO GUIDE BOOK FOR DETAILS'$"

Help_Text_DescWhatDoesThisTermMean::
    .string "? Wahoo!$"

Help_Text_DescAboutThisGame::
    .string " Xian Jie sukiyana-akuteibu$"

Help_Text_DescTypeMatchupList::
    .string "PKMN TYPE viw: p. 3$"

Help_Text_DescExit::
    .string "CES: CONTINUE GAME$"

Help_Text_Greetings::
    .string "SYSTEM FAILURE IMMINENT. SEEK\p"
    .string "SHELTER IMMEDIATELY.$"

Help_Text_PlayingForFirstTime::
    .string "'Welcome, adventurer! The land of\p"
    .string "Eridoria awaits. Explore, battle,\n"
    .string "and claim greatness!'$"

Help_Text_WhatShouldIBeDoing::
    .string "'Recover ancient artifact from\p"
    .string "dusty ruins.'$"

Help_Text_CantGetOutOfRoom::
    .string "'Stuck in Cell Block 3. Find\p"
    .string "Keycard or Die Trying.'$"

Help_Text_CantFindPersonIWant::
    .string "People density: 25$"

Help_Text_TalkedToEveryoneNowWhat::
    .string "'Front doors of Mansion creak\p"
    .string "open. Investigate?'$"

Help_Text_SomeoneBlockingMyWay::
    .string "GRIZZLED WARRIOR STANDS IN YOUR\p"
    .string "PATH!$"

Help_Text_ICantGoOn::
    .string "'Flee from danger! You can't stay\p"
    .string "here!'$"

Help_Text_OutOfThingsToDo::
    .string "'The local blacksmith is in need\p"
    .string "of iron ore.'$"

Help_Text_WhatHappenedToItemIGot::
    .string "'Treasure pocketed successfully!'$"

Help_Text_WhatAreMyAdventureBasics::
    .string "'RogerYi Wei Yin Bi Liao Ni De Ke\p"
    .string "Ting aac! Quest: Find hidden items\n"
    .string "in the Will-o'-Wisp's Cove'$"

Help_Text_HowAreRoadsForestsDifferent::
    .string "'RUINS AHEAD! FOES LURK IN\p"
    .string "SHADOWED GLADES, WHILE SMOOTH\n"
    .string "ROADS LEAD TO NEW VICTORIES.'$"

Help_Text_HowAreCavesDifferent::
    .string "'Cautious explorer, beware: eerie\p"
    .string "silence  treacherous terrain lurk\n"
    .string "here!'$"

Help_Text_HowDoIProgress::
    .string "REETEQ STATION 3: DEFUSE DEVICE IN\p"
    .string "5 MINUTES$"

Help_Text_WhenCanIUseItem::
    .string "Item usage: Space Item Number$"

Help_Text_WhatsABattle::
    .string "'Face feral felines in Fierce\p"
    .string "Feline Frenzy!'$"

Help_Text_HowDoIPrepareForBattle::
    .string "'Equip armor, gather potions, and\p"
    .string "psyche up for the fray!'$"

Help_Text_WhatIsAMonsVitality::
    .string "'VIT: 100'$"

Help_Text_MyMonsAreHurt::
    .string "HEAL THEM AT Poke CENTER!$"

Help_Text_WhatIsStatusProblem::
    .string "'FATAL ERROR: CONNECTOR DAMAGED.\p"
    .string "REPAIR REQUIRED.'$"

Help_Text_WhatHappensIfAllMyMonsFaint::
    .string "'TRAINER HAS FALLEN! YOU LOSE YOUR\p"
    .string "BATTLE'$"

Help_Text_CantCatchMons::
    .string "'GET ME THAT POKEMON!'$"

Help_Text_RanOutOfPotions::
    .string "You're a bit drained!$"

Help_Text_CanIBuyPokeBalls::
    .string "BALL BOUTIQUE$"

Help_Text_WhatsATrainer::
    .string "MYSTICAL BEAST OF CASTLE WALLS$"

Help_Text_HowDoIWinAgainstTrainer::
    .string "'WEAR HIM DOWN WITH QUICK JABS,\p"
    .string "THEN FINISH WITH A POWER PUNCH!'$"

Help_Text_WhereDoMonsAppear::
    .string "IN TALL GRASS AND DARK CAVES.$"

Help_Text_WhatAreMoves::
    .string "'MASTER COPIES OF POKeMON SKILLS!'$"

Help_Text_WhatAreHiddenMoves::
    .string "'Shhh... few know, but masters\p"
    .string "possess. Unlocked with secret\n"
    .string "combos, unleash hidden fury!'$"

Help_Text_WhatMovesShouldIUse::
    .string "'Beatdown: Punch-Stun Combo. Dash\p"
    .string "Slash: Quick fast strike.'$"

Help_Text_WantToAddMoreMoves::
    .string "NEW MOVE UNLOCKED!  'Wall\p"
    .string "Whirlwind' - A swift kick that\n"
    .string "sends opponents flying back,\p"
    .string "leaving them open to attack!$"

Help_Text_WantToMakeMonStronger::
    .string "'HUNT FOR RARE POKE BERRIES IN THE\p"
    .string "CAVE NEARBY'$"

Help_Text_FoeMonsTooStrong::
    .string "'Flee while you still can!'$"

Help_Text_WhatDoIDoInCave::
    .string "'FIND TREASURE, ESCAPE SHADOWY\p"
    .string "CREATURES'$"

Help_Text_NothingIWantToKnow::
    .string "You sense a strange energy\p"
    .string "emanating from the ancient ruins\n"
    .string "ahead...$"

Help_Text_WhatsPokemonCenter::
    .string "'Restore weary POKeMON at this\p"
    .string "tranquil haven!'$"

Help_Text_WhatsPokemonMart::
    .string "'A specialized shop for all your\p"
    .string "POKeMON needs: supplies, gear, and\n"
    .string "tasty snacks!'$"

Help_Text_WantToEndGame::
    .string "'GAME OVER. lastName, would you\p"
    .string "like to continue?'$"

Help_Text_WhatsAMon::
    .string "Mysterious Creatures$"

Help_Text_WhatIsThatPersonLike::
    .string "'Tall, pale, and sinister.\p"
    .string "Wakewell, the village killer.'$"

Help_Text_WhatDoesHiddenMoveDo::
    .string "'UNVEILS UN EXPECTED STRENGTH!'$"

Help_Text_WhatDoIDoInSafari::
    .string "'FEED THE CUBS! COLLECT BANANAS\p"
    .string "FOR ENERGY'$"

Help_Text_WhatAreSafariRules::
    .string "'BEWARE! SAFARI GAME RULES:'$"

Help_Text_WantToEndSafari::
    .string "UH-OH! TANK ROAMING FREE!$"

Help_Text_WhatIsAGym::
    .string "'Fitness Facility. Protect\p"
    .string "Yourself!'$"

Help_Text_AnswerPlayingForFirstTime::
    .string "'Ready for adventure?'$"

Help_Text_AnswerWhatShouldIBeDoing::
    .string " TALK TO MORT WHO IS STANDING BY\p"
    .string "THE TREE.$"

Help_Text_AnswerCantGetOutOfRoom::
    .string "'Stand on red mat to proceed'$"

Help_Text_AnswerCantFindPersonIWant::
    .string "Strange occurrences on the rise$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
    .string "rere! Next exit: Desert Oasis\p"
    .string "ahead!$"

Help_Text_AnswerSomeoneBlockingMyWay::
    .string "Investigate town or buildings\p"
    .string "further.$"

Help_Text_AnswerICantGoOn::
    .string "People won't respond if u\p"
    .string "don'tulturah$"

Help_Text_AnswerOutOfThingsToDo::
    .string "EXPLORE UNKNOWN AREAS$"

Help_Text_AnswerWhatHappenedToItemIGot::
    .string "Press B AG to view contents.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
    .string " bndy zhur nomeuru pob yu!$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
    .string "'Venture carefully, young\p"
    .string "adventurer!'$"

Help_Text_AnswerHowAreCavesDifferent::
    .string "CAVE SYSTEM: BEWARE OF WILD\p"
    .string "POKEMON!$"

Help_Text_AnswerHowDoIProgress::
    .string "'Find path stone or pushy Psymon!'$"

Help_Text_AnswerWhenCanIUseItem::
    .string "Use Item...$"

Help_Text_AnswerWhatsABattle::
    .string "'FIGHT!'$"

Help_Text_AnswerHowDoIPrepareForBattle::
    .string "Heal party POKEMON at POKEMON\p"
    .string "CENTER$"

Help_Text_AnswerWhatIsAMonsVitality::
    .string "Your POKeMON's HP: 65/100$"

Help_Text_AnswerMyMonsAreHurt::
    .string "Healed Pokemon fully restored.$"

Help_Text_AnswerWhatIsStatusProblem::
    .string "'Status Problem: Defeat foes  seek\p"
    .string "aid at POKeMON CENTER!'$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
    .string "Save often, young trainer!$"

Help_Text_AnswerCantCatchMons::
    .string "Try reducing its HP some more...$"

Help_Text_AnswerRanOutOfPotions::
    .string "'POKEMON MART - Stock up here!'$"

Help_Text_AnswerCanIBuyPokeBalls::
    .string "Buy POKe BALLS at POKeMON MART!$"

Help_Text_AnswerWhatsATrainer::
    .string "'TRAINER: Kohl! You ain't no\p"
    .string "rookie, but I'll still kick your\n"
    .string "Pokes around!'$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
    .string "'OUTSMART THE FOE'S POKEMON TYPE!'$"

Help_Text_AnswerWhereDoMonsAppear::
    .string "Enter TALL GRASS carefully...$"

Help_Text_AnswerWhatAreMoves::
    .string "'REMEMBER TO CHECK YOUR POKEMON'S\p"
    .string "MOVE LIST'$"

Help_Text_AnswerWhatAreHiddenMoves::
    .string "USE HIDDEN MOVE WITHbove POKeMON\p"
    .string "MENU$"

Help_Text_AnswerWhatMovesShouldIUse::
    .string "FIGHT$"

Help_Text_AnswerWantToAddMoreMoves::
    .string "Level up to learn 4 moves. TMs\p"
    .string "HMs too!$"

Help_Text_AnswerWantToMakeMonStronger::
    .string "BATTLE WILD POKEMON OFTEN TO LEVEL\p"
    .string "UP!$"

Help_Text_AnswerFoeMonsTooStrong::
    .string "Level up your POKeMON more!$"

Help_Text_AnswerWhatDoIDoInCave::
    .string "Beware cave hazards!$"

Help_Text_AnswerNothingIWantToKnow::
    .string "'TOUCH YOUR TRUE STRENGTH!'$"

Help_Text_AnswerWhatsPokemonCenter::
    .string "RESTORE YOUR POKEMON'S POTENTIAL.$"

Help_Text_AnswerWhatsPokemonMart::
    .string ".sparkling eyes in the MART window$"

Help_Text_AnswerWantToEndGame::
    .string "'SELECT SAVE ON MENU'$"

Help_Text_AnswerWhatsAMon::
    .string "Catch wild POKeMON in grass!$"

Help_Text_AnswerWhatIsThatPersonLike::
    .string "YOU NEED MORE FAME TO USE FAME\p"
    .string "CHECKER!$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
    .string "'Learn Hidden Move: HM Master'$"

Help_Text_AnswerWhatDoIDoInSafari::
    .string "WILD PIDGEY APPEARS!$"

Help_Text_AnswerWhatAreSafariRules::
    .string "nEnter password to unlock NEXT\p"
    .string "LEVEL.$"

Help_Text_AnswerWantToEndSafari::
    .string "You find a hidden TREE STUMP\p"
    .string "nearby.$"

Help_Text_AnswerWhatIsAGym::
    .string "'Welcome to the  Pokemon Gym!'$"

Help_Text_UsingPokedex::
    .string "PIDO, PWRCHN: 150 HP$"

Help_Text_UsingPokemon::
    .string "Trainer, you found POKeMONwire...$"

Help_Text_UsingSummary::
    .string "You've found a mysterious artifact\p"
    .string "in the ancient temple. Will it aid\n"
    .string "or hinder your quest?$"

Help_Text_UsingSwitch::
    .string "INCOMING TRANSMISSION FROM HQ...$"

Help_Text_UsingItem::
    .string "You found a rare GLOWING MUSHROOM!$"

Help_Text_UsingBag::
    .string "You found an old Sack containing a\p"
    .string "few Coins and a rusty Key.$"

Help_Text_UsingAnItem::
    .string "'Conserve Energy Device Activated'$"

Help_Text_UsingKeyItem::
    .string "'Crystal Shards found!'$"

Help_Text_UsingPokeBall::
    .string "USE OK!$"

Help_Text_UsingPlayer::
    .string "You have found the Ancient\p"
    .string "Temple's entrance.$"

Help_Text_UsingSave::
    .string "SARIA'S STRONGHOLD UNDER ATTACK!$"

Help_Text_UsingOption::
    .string "LOAD OPTION SELECTOR$"

Help_Text_UsingPotion::
    .string "Health increased by 50 points.$"

Help_Text_UsingTownMap::
    .string "YOU SEE: MAIN STAGE pari$"

Help_Text_UsingTM::
    .string "Congratulations on reaching the\p"
    .string "hidden cave.$"

Help_Text_UsingHM::
    .string "'The mysterious old man hands you\p"
    .string "a rusty key.'$"

Help_Text_UsingMoveOutsideOfBattle::
    .string "'Use move wisely!'$"

Help_Text_RidingBicycle::
    .string "'WOOHOO! Level 3-2: CIRCUIT\p"
    .string "COURSE'$"

Help_Text_EnteringName::
    .string "ENTER YOUR NAME UP TO 8 CHARACTERS$"

Help_Text_UsingPC::
    .string " Resource Diskspace Low$"

Help_Text_UsingBillsPC::
    .string "Welcome to 'Labyrinth of Legends'!\p"
    .string "You find yourself in front of\n"
    .string "'STRVAR1'S PC', a dusty old\p"
    .string "terminal with a flickering screen.$"

Help_Text_UsingWithdraw::
    .string "CREDITS: 500$"

Help_Text_UsingDeposit::
    .string "500 GOLD COINS DEPOSITED$"

Help_Text_UsingMove::
    .string "Move South$"

Help_Text_MovingItems::
    .string "Press SPACE to swap.$"

Help_Text_UsingPlayersPC::
    .string "'Malfunction detected!Screen\p"
    .string "flickering badly.'$"

Help_Text_UsingWithdrawItem::
    .string "YOU RETRIEVE ITEM 1.$"

Help_Text_UsingDepositItem::
    .string "You insert the item. Achilles Key\p"
    .string "acquired.$"

Help_Text_UsingMailbox::
    .string "Urgent! 25 Gold Coins Waiting$"

Help_Text_UsingProfOaksPC::
    .string "'A MYSTERIOUS FILE HAS APPEARED ON\p"
    .string "OUR COMPUTER!'$"

Help_Text_OpeningMenu::
    .string "SELECT OPTIONS: NEW GAME, LOAD\p"
    .string "GAME, OPTIONS$"

Help_Text_UsingFight::
    .string "'FIGHT ENEMY ENCLOSURE-guard 3,000\p"
    .string "HP'$"

Help_Text_UsingPokemon2::
    .string "Trainer, you found POKeMONwire...$"

Help_Text_UsingShift::
    .string "UNLOCKING ADVANCED THRUST - SYSTEM\p"
    .string "ONLINE$"

Help_Text_UsingSummary2::
    .string "You've found a mysterious artifact\p"
    .string "in the ancient temple. Will it aid\n"
    .string "or hinder your quest?$"

Help_Text_UsingBag2::
    .string "You found an old Sack containing a\p"
    .string "few Coins and a rusty Key.$"

Help_Text_ReadingPokedex::
    .string "'Pikachu 27/151'$"

Help_Text_UsingHomePC::
    .string "'ACTIVATING HOME PC'$"

Help_Text_UsingItemStorage::
    .string "'Container full. Remove items to\p"
    .string "free space.'$"

Help_Text_UsingWithdrawItem2::
    .string "YOU RETRIEVE ITEM 1.$"

Help_Text_UsingDepositItem2::
    .string "You insert the item. Achilles Key\p"
    .string "acquired.$"

Help_Text_UsingMailbox2::
    .string "'MONEY ORDER INSIDE'$"

Help_Text_UsingRun::
    .string "'GOLDEN TICKET FOUND! KEEP MOVING\p"
    .string "TO ESCAPE THE PIT!'$"

Help_Text_RegisterKeyItem::
    .string "KEY FOUND: README$"

Help_Text_UsingBall::
    .string "'Power-Up Ball Detected!'$"

Help_Text_UsingBait::
    .string "Hooked! Worth 50 EXP$"

Help_Text_UsingRock::
    .string "Crude Boulder Ahead$"

Help_Text_UsingHallOfFame::
    .string "Congratulations! You've Made it to\p"
    .string "the Hall of Fame!$"

Help_Text_HowToUsePokedex::
    .string "SEEK POKEMON INFO.$"

Help_Text_HowToUsePokemon::
    .string "SELECT POKeMON NOW!$"

Help_Text_HowToUseSummary::
    .string "SELECT SUMMARY.$"

Help_Text_HowToUseSwitch::
    .string "SELECT SWAP POKEMON$"

Help_Text_HowToUseItem::
    .string "SELECT ITEM$"

Help_Text_HowToUseBag::
    .string "SELECT 'BAG' ON MENU.$"

Help_Text_HowToUseAnItem::
    .string "SELECT ITEM POCKET$"

Help_Text_HowToUseKeyItem::
    .string "USE SPROUTUserDefaults!$"

Help_Text_HowToUsePokeBall::
    .string "USE POKEBALL$"

Help_Text_HowToUsePlayer::
    .string "SELECT 'LEX' ON MENU.$"

Help_Text_HowToUseSave::
    .string "SELECT 'SAVE' ON MENU.$"

Help_Text_HowToUseOption::
    .string "SELECT OPTION ON MENU.$"

Help_Text_HowToUsePotion::
    .string "SELECT POTION TO HEAL POKEMON.$"

Help_Text_HowToUseTownMap::
    .string "CONTROLS: USE TOWN MAP IN KEY\p"
    .string "ITEMS POCKET$"

Help_Text_HowToUseTM::
    .string "USE TM CASE.$"

Help_Text_HowToUseHM::
    .string "USE HM TOGETHER!$"

Help_Text_HowToUseMoveOutsideOfBattle::
    .string "SELECT HM MOVE TO PROCEED$"

Help_Text_HowToRideBicycle::
    .string "SELECT BROCHURE TO REGISTER$"

Help_Text_HowToEnterName::
    .string "USE CURSOR PAD WITH A BUTTON TO\p"
    .string "TYPESetting options to YES.$"

Help_Text_HowToUsePC::
    .string " transpoiforna your POKeTEMPLATE\p"
    .string "obdobno!$"

Help_Text_HowToUseBillsPC::
    .string " Select 'Lily's PC' on the PC.$"

Help_Text_HowToUseWithdraw::
    .string "SELECT POKEMON IN BOX WITH PLUS\p"
    .string "CONTROL PAD.$"

Help_Text_HowToUseDeposit::
    .string "STORE POKEMON IN BOX$"

Help_Text_HowToUseMove::
    .string "MOVE POKeMON TO BOX WITH...$"

Help_Text_HowToMoveItems::
    .string "SELECT POKeMON THEN A TO\p"
    .string "GIVE/RETURN ITEM$"

Help_Text_HowToUsePlayersPC::
    .string "SELECT PLAYER'S PC$"

Help_Text_HowToUseWithdrawItem::
    .string "WITHDRAW ITEM?$"

Help_Text_HowToUseDepositItem::
    .string "DEPOSIT ITEM? Y/N$"

Help_Text_HowToUseMailbox::
    .string "SELECT 'PLAYER'S PC'.$"

Help_Text_HowToUseProfOaksPC::
    .string "SELECT PROJ. OAK'S PC$"

Help_Text_HowToOpenMenu::
    .string "PRESS START$"

Help_Text_HowToUseFight::
    .string "FIGHT$"

Help_Text_HowToUsePokemon2::
    .string "SELECT POKeMON:$"

Help_Text_HowToUseShift::
    .string "Select POKeMON to swap?$"

Help_Text_HowToUseSummary2::
    .string "SELECT SUMMARY.$"

Help_Text_HowToUseBag2::
    .string "SELECT BAG.$"

Help_Text_HowToReadPokedex::
    .string "POKE BALL mark on POKEDEX list.$"

.if REVISION < 1
	.string "{CIRCLE_3} Select “AREA” to display the TOWN\n"
	.string "   MAP with the POKéMON's habitat(s).$"
	.else
	.string "{CIRCLE_3} Select “NEXT DATA” to display the\n"
	.string "   TOWN MAP with its habitat(s).$"
	.endif

Help_Text_HowToUseHomePC::
    .string "SELECT ITEM STORAGE$"

Help_Text_HowToUseItemStorage::
    .string "WITHDRAW ITEM$"

Help_Text_HowToUseWithdrawItem2::
    .string "WITHDRAW ITEM?$"

Help_Text_HowToUseDepositItem2::
    .string "DEPOSIT ITEM.$"

Help_Text_HowToUseMailbox2::
    .string "SELECT MAIL BY NAME TO READ IT OR\p"
    .string "MAKE A POKEMON HOLD IT$"

Help_Text_HowToUseRun::
    .string "RUN AWAY FROM THIS TRAINER!$"

Help_Text_HowToRegisterKeyItem::
    .string "REGISTER?$"

Help_Text_HowToUseBall::
    .string "SELECT TO THROW$"

Help_Text_HowToUseBait::
    .string " THROW BAIT?$"

Help_Text_HowToUseRock::
    .string "THROW ROCK$"

Help_Text_HowToUseHallOfFame::
    .string "HALL OF FAME ENTERED!$"

Help_Text_HP::
    .string "300$"

Help_Text_EXP::
    .string "50$"

Help_Text_Moves::
    .string "Use ASDW keys to move.$"

Help_Text_Attack::
    .string "'ATTACK NOW!'$"

Help_Text_Defense::
    .string "Rumble 'Incoming Missile!'$"

Help_Text_SpAtk::
    .string "ATTACK! STRIKE NOW!$"

Help_Text_SpDef::
    .string "STRONG POINT DEFENSES$"

Help_Text_Speed::
    .string "'Turbo Boost Activated! 20 MPH'$"

Help_Text_Level::
    .string "You enter the cave...$"

Help_Text_Type::
    .string "SYSTEM FAILURE Detected.$"

Help_Text_OT::
    .string "'Out of the shadows, a mysterious\p"
    .string "figure approaches...'$"

Help_Text_Item::
    .string "'Shiny Key Found'$"

Help_Text_Ability::
    .string "'SPARK FIST: 3 hits, 300 HP'$"

Help_Text_Money::
    .string "You have 1010 Bucks!$"

Help_Text_MoveType::
    .string "'SNEAKY FORAY'$"

Help_Text_Nature::
    .string "A gentle breeze rustles the\p"
    .string "leaves, a saber-toothed tiger's\n"
    .string "roar echoes in the distance.$"

Help_Text_IDNo::
    .string "'Security clearance granted.\p"
    .string "Access granted.'$"

Help_Text_PP::
    .string "Welcome to the Pound Palace!$"

Help_Text_Power::
    .string "'You've found a POST-NUK POWER\p"
    .string "DEVICE! NHS 300'$"

Help_Text_Accuracy::
    .string "'GRAVITY DEFIED!'$"

Help_Text_FNT::
    .string "FNT FOUND!$"

Help_Text_Items::
    .string "You found a rusty key!$"

Help_Text_KeyItems::
    .string "TREASURE MAP$"

Help_Text_PokeBalls::
    .string "5 LEFT$"

Help_Text_Pokedex::
    .string "'Coder is detected in the wild!\p"
    .string "Level: 5'$"

Help_Text_PlayTime::
    .string "09:45$"

Help_Text_Badges::
    .string "FOUND 5 OF 10$"

Help_Text_TextSpeed::
    .string "'GLITCH DETECTED. SYSTEM\p"
    .string "OVERLOADING.'$"

Help_Text_BattleScene::
    .string "ENEMY WIZARD APPEARS!$"

Help_Text_BattleStyle::
    .string "ENEMY APPEARS! GOBLIN WARRIOR 12\p"
    .string "HP$"

Help_Text_Sound::
    .string "What a strange noise...$"

Help_Text_ButtonMode::
    .string "LVL 1 ACTIVATED$"

Help_Text_Frame::
    .string "THE FOREST IS DARK AND FULL OF\p"
    .string "TREES$"

Help_Text_Cancel2::
    .string "CANCELED.$"

Help_Text_TM::
    .string "YOU'VE FOUND A HIDDEN KEY!$"

Help_Text_HM::
    .string "'Hidden Message Unlocked!'$"

Help_Text_HMMove::
    .string "You found a hidden move!$"

Help_Text_Evolution::
    .string "'Canny's Claw Get ready to unleash\p"
    .string "its fury!'$"

Help_Text_StatusProblem::
    .string "SYSTEM FAILURE DETECTED$"

Help_Text_Pokemon::
    .string "Wild Pidgey appears!$"

Help_Text_IDNo2::
    .string "'Security clearance granted.\p"
    .string "Access granted.'$"

Help_Text_Money2::
    .string "You have 1010 Bucks!$"

Help_Text_Badges2::
    .string "FOUND 5 OF 10$"

Help_Text_DefineHP::
    .string " Warning: Low HP$"

Help_Text_DefineEXP::
    .string "EXP POINTS Anchored at 120/500$"

Help_Text_DefineMoves::
    .string "'Study POKeMON moves to master\p"
    .string "them all!'$"

Help_Text_DefineAttack::
    .string "ATT 12$"

Help_Text_DefineDefense::
    .string "POKetroduction: 100$"

Help_Text_DefineSpAtk::
    .string "spd atk: 120$"

Help_Text_DefineSpDef::
    .string "DEFENSE BOOST TEMPS LIFTED, SP.\p"
    .string "DEF 10!$"

Help_Text_DefineSpeed::
    .string "AGILITY CRUCIAL IN BATTLE TACTICS!$"

Help_Text_DefineLevel::
    .string "Lv. up and get stronger!$"

Help_Text_DefineType::
    .string "'Battle Strategy: Know thy type!'$"

Help_Text_DefineOT::
    .string "'Trainer: player name OT'$"

Help_Text_DefineItem::
    .string "'GIVE IT TO ME!'$"

Help_Text_DefineAbility::
    .string "FOUND: POKEMON ABILITIES shaping\p"
    .string "itsTRAINING!$"

Help_Text_DefineMoney::
    .string "You earned 500 PokeDollars!$"

Help_Text_DefineMoveType::
    .string "SYNERGY BOOSTED!$"

Help_Text_DefineNature::
    .string "Nature: Adventurous$"

Help_Text_DefineIDNo::
    .string "ID NO. 54321: svychcolumn9$"

Help_Text_DefinePP::
    .string "PP: 3$"

Help_Text_DefinePower::
    .string "YOUR POWER: 120$"

Help_Text_DefineAccuracy::
    .string "Accuracy: 87$"

Help_Text_DefineFNT::
    .string "'Fainted Pokemon unable to battle,\p"
    .string "revive at CENTER or use item.'$"

Help_Text_DefineItems::
    .string "Items stored: Poke Balls x3,\p"
    .string "Antidote x1$"

Help_Text_DefineKeyItems::
    .string "KEY ITEM POCKET: NEW ITEM$"

Help_Text_DefinePokeBalls::
    .string "Catch more Pokemon with POKe\p"
    .string "BALLS!$"

Help_Text_DefinePokedex::
    .string "'12 species in your dex!'$"

Help_Text_DefinePlayTime::
    .string "TIME PLAYED: 02:14:52$"

Help_Text_DefineBadges::
    .string "Badges: 0/8$"

Help_Text_DefineTextSpeed::
    .string "Choose your tempo wisely... FAST.$"

Help_Text_DefineBattleScene::
    .string "BATTLE ANIM OFF? Y/N$"

Help_Text_DefineBattleStyle::
    .string "SHIFT$"

Help_Text_DefineSound::
    .string "SELECT SOUND OPTION...$"

Help_Text_DefineButtonMode::
    .string "SET to 'LR' to switch POKeDEX and\p"
    .string "BAG POCKETS.$"

Help_Text_DefineFrame::
    .string "SELECT FRAMEDESIGN$"

Help_Text_DefineCancel2::
    .string "SELECT DIFFICULTY$"

Help_Text_DefineTM::
    .string "TM: Learned Water Gun on Poke\p"
    .string "Ball.$"

Help_Text_DefineHM::
    .string "USE HM TO TEACH POKEMON NEW MOVE!$"

Help_Text_DefineHMMove::
    .string "USE HIDDEN MOVE WITHbove POKeMON\p"
    .string "MENU$"

Help_Text_DefineEvolution::
    .string "Pokemon evolve beyond level 10!$"

Help_Text_DefineStatusProblem::
    .string "Heed this warning, brave\p"
    .string "adventurer!$"

Help_Text_DefinePokemon::
    .string "'Get Ready for Adventure!'$"

Help_Text_DefineIDNo2::
    .string "ID NO. 54321: svychcolumn9$"

Help_Text_DefineMoney2::
    .string "You earned 500 PokeDollars!$"

Help_Text_DefineBadges2::
    .string "6 BADGES$"

Help_Text_TheHelpSystem::
    .string "'Press? for help menu. Push square\p"
    .string "to pause game.'$"

Help_Text_TheGame::
    .string "'WELCOME TO ECHOKEEPER TERRITORY!'$"

Help_Text_WirelessAdapter::
    .string "MALFUNCTION ALERT!$"

Help_Text_GameFundamentals1::
    .string "GET READY FOR LAUNCH!$"

Help_Text_GameFundamentals2::
    .string "Lives: 3$"

Help_Text_GameFundamentals3::
    .string "' Sao Paulo Stadium: 3,000,000'$"

Help_Text_WhatArePokemon::
    .string "Mysterious creatures with hidden\p"
    .string "powers...$"

Help_Text_DescTheHelpSystem::
    .string "HELP SYSTEM ACCESSIBLE$"

Help_Text_DescTheGame::
    .string "'Embark on a journey to\p"
    .string "Calistoga!'$"

Help_Text_DescWirelessAdapter::
    .string "CONNECTION ESTABLISHED$"

Help_Text_DescGameFundamentals1::
    .string "'Your Journey Begins Now'$"

Help_Text_DescGameFundamentals2::
    .string "'Defeat the dark sorcerer to liftn\p"
    .string "the shadowy curse on the land.'$"

Help_Text_DescGameFundamentals3::
    .string "'Try teaching Ember to a Pawn!'$"

Help_Text_DescWhatArePokemon::
    .string "Catch 'em all, young trainer!$"

Help_Text_UsingTypeMatchupList::
    .string "Pokemon Robo vs. Gengar, advantage\p"
    .string "Pokemon Robo.$"

Help_Text_OwnMoveDark::
    .string "'''flickers in darkness''$"

Help_Text_OwnPokemonDark::
    .string "'Ominous amulet detected!'$"

Help_Text_OwnMoveRock::
    .string "STEADY THE GROUND$"

Help_Text_OwnPokemonRock::
    .string "You: Graveler Level 10$"

Help_Text_OwnMovePsychic::
    .string "PSYSTRIKE! THE FORCE IS WITH YOU!$"

Help_Text_OwnPokemonPsychic::
    .string "'Psychic Power Flares On!'$"

Help_Text_OwnMoveFighting::
    .string "'Your special move: HEADBUTT! Use\p"
    .string "wisely...'$"

Help_Text_OwnPokemonFighting::
    .string "'FURY MONKEY DEFEATED'$"

Help_Text_OwnMoveGrass::
    .string "Shi Su  ileed!$"

Help_Text_OwnPokemonGrass::
    .string "UNYUR, your trusty Venusaur!$"

Help_Text_OwnMoveGhost::
    .string "'Furtive slide ahead!'$"

Help_Text_OwnPokemonGhost::
    .string "'Haunt or Faint, friend?'$"

Help_Text_OwnMoveIce::
    .string " FREEZE SHOT!$"

Help_Text_OwnPokemonIce::
    .string "Cryo, the Icicle Icesquirrel!$"

Help_Text_OwnMoveGround::
    .string "'Gritty Frenzy: Slam\p"
    .string "uncontrollable rage'$"

Help_Text_OwnPokemonGround::
    .string "You carry: Sandslash, Total HP: 60$"

Help_Text_OwnMoveElectric::
    .string "ZAP!$"

Help_Text_OwnPokemonElectric::
    .string "You have a Pikachu!$"

Help_Text_OwnMovePoison::
    .string "'Deadly Venom: Auto-Curse foe with\p"
    .string "Toxin!'$"

Help_Text_OwnPokemonPoison::
    .string "KOFFING UNCONSCIOUS$"

Help_Text_OwnMoveDragon::
    .string "'UNLEASH YOUR INNER BEAST!'$"

Help_Text_OwnPokemonDragon::
    .string "You've got a rare one, indeed!$"

Help_Text_OwnMoveNormal::
    .string "CITALOt YOUR MONSTER!$"

Help_Text_OwnPokemonNormal::
    .string "YOU SUSPECT AWARE WILD POKeMON!$"

Help_Text_OwnMoveSteel::
    .string "METAL MITE!$"

Help_Text_OwnPokemonSteel::
    .string "'Steelbird, Level 15'$"

Help_Text_OwnMoveFlying::
    .string "'FLEW South'$"

Help_Text_OwnPokemonFlying::
    .string "'WINGED WONDER'$"

Help_Text_OwnMoveFire::
    .string "''$"

Help_Text_OwnPokemonFire::
    .string "MEET FLARE THE MAGMAR!$"

Help_Text_OwnMoveWater::
    .string "Divekick license acquired!$"

Help_Text_OwnPokemonWater::
    .string "YOU BATTLE WITH... MAGIKARP$"

Help_Text_OwnMoveBug::
    .string "POISON PANDEMONIUM APPROACHES!$"

Help_Text_OwnPokemonBug::
    .string "You're carrying a lone Metapod.$"

Help_Text_HowToUseTypeMatchupList::
    .string "Move Type: Fire, Target Type:\p"
    .string "Grass$"

Help_Text_TypeMatchupOwnMoveDark::
    .string "POISONOUS!$"

Help_Text_TypeMatchupOwnPokemonDark::
    .string "Foe's strike weakens bug-type\p"
    .string "POKeMON!$"

Help_Text_TypeMatchupOwnMoveRock::
    .string "Pokemon immune to flames.$"

Help_Text_TypeMatchupOwnPokemonRock::
    .string "IMMUNE!$"

Help_Text_TypeMatchupOwnMovePsychic::
    .string "Type advantage unfolded!$"

Help_Text_TypeMatchupOwnPokemonPsychic::
    .string "BUG, GHOST, DARK immune!$"

Help_Text_TypeMatchupOwnMoveFighting::
    .string "Immune to 4 types!$"

Help_Text_TypeMatchupOwnPokemonFighting::
    .string "CIRCLEDOT... resistor to Psychic!$"

Help_Text_TypeMatchupOwnMoveGrass::
    .string "Resistant to Water, Ground, Rock.\p"
    .string "Weak to Fire, Grass, Poison,\n"
    .string "Flying, Bug, Dragon, Steel.$"

Help_Text_TypeMatchupOwnPokemonGrass::
    .string "-NO EFFECT-$"

Help_Text_TypeMatchupOwnMoveGhost::
    .string "Type advantages confuse me!$"

Help_Text_TypeMatchupOwnPokemonGhost::
    .string "GRAVEL GHOST WEAKEN!$"

Help_Text_TypeMatchupOwnMoveIce::
    .string " WEAKNESS NOTED$"

Help_Text_TypeMatchupOwnPokemonIce::
    .string "Weak against!$"

Help_Text_TypeMatchupOwnMoveGround::
    .string "Double your damage to FLYING-\p"
    .string "types!$"

Help_Text_TypeMatchupOwnPokemonGround::
    .string "Got some bad news: Lightning\p"
    .string "struck, Paralyze!$"

Help_Text_TypeMatchupOwnMoveElectric::
    .string "Water- and Flying-types weak!\p"
    .string "Electric-, Grass-, and Dragon-\n"
    .string "types strong!$"

Help_Text_TypeMatchupOwnPokemonElectric::
    .string "? GROUND.$"

Help_Text_TypeMatchupOwnMovePoison::
    .string "Steel immune to Poison, Ground,\p"
    .string "Rock, Ghost.$"

Help_Text_TypeMatchupOwnPokemonPoison::
    .string "CIRCLEDOT Trieffect!$"

Help_Text_TypeMatchupOwnMoveDragon::
    .string "WEAK to Dragon-type, IMMUNE to\p"
    .string "Steel-type!$"

Help_Text_TypeMatchupOwnPokemonDragon::
    .string "Inverse weakness detected!$"

Help_Text_TypeMatchupOwnMoveNormal::
    .string "'Resistance to Rock and Steel\p"
    .string "types. Ghost-type moves increase\n"
    .string "in power.'$"

Help_Text_TypeMatchupOwnPokemonNormal::
    .string "KO'd by Ghost-type attack!$"

Help_Text_TypeMatchupOwnMoveSteel::
    .string "WEAKENED Obrimos to ICE and ROCK!$"

Help_Text_TypeMatchupOwnPokemonSteel::
    .string "/CIRCLEDOT/:$"

Help_Text_TypeMatchupOwnMoveFlying::
    .string "Weak to GRASS, FIGHTING, BUG!$"

Help_Text_TypeMatchupOwnPokemonFlying::
    .string "Weak!$"

Help_Text_TypeMatchupOwnMoveFire::
    .string "Weaknesses detected!$"

Help_Text_TypeMatchupOwnPokemonFire::
    .string "weak against fire$"

Help_Text_TypeMatchupOwnMoveWater::
    .string "Weak to Fire, Ground, Rock. Super\p"
    .string "effective on Water, Grass, Dragon.$"

Help_Text_TypeMatchupOwnPokemonWater::
    .string "Deflects fire, water, and steel\p"
    .string "attacks!$"

Help_Text_TypeMatchupOwnMoveBug::
    .string "Immune to Grass, Psychic, Dark and\p"
    .string "resistant to Fire, Fighting,\n"
    .string "Poison, Flying, Ghost, Steel!$"

Help_Text_TypeMatchupOwnPokemonBug::
    .string "They took aim at you!$"

