Trade_Text_LookingForMonWannaTradeForMon::
    .string "PIKACHU!$"

Trade_Text_AwwOhWell::
    .string "Hope next time is more lucky!$"

Trade_Text_WhatThatsNoMon::
    .string "What sorcery is this?!$"

Trade_Text_HeyThanks::
    .string "WARNING: Danger ahead!$"

Trade_Text_IsntMyOldMonGreat::
    .string "That STRVAR2 has won me 10 golden\p"
    .string "acorns!$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
    .string "Need a Golden Apple and willing to\p"
    .string "part with my rusty old Sword.$"

Trade_Text_WellIfYouDontWantTo::
    .string "...risk it all, flee now!$"

Trade_Text_ThisIsntMon::
    .string "'Secret hasn't surfaced yet'$"

Trade_Text_Thanks::
    .string "GRAVEYARD OF THE DAMNED$"

Trade_Text_HasTradedMonGrownStronger::
    .string "YES, IT DRAWS NEAR STRONG!/ male$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
    .string "DO YOU HAVE THE ANCIENT SWORD?$"

Trade_Text_ThatsTooBad::
    .string "'Uh oh, looks like you're in a bit\p"
    .string "of trouble!'$"

Trade_Text_ThisIsNoMon::
    .string "Rarity Badge of Zeal$"

Trade_Text_ThanksYoureAPal::
    .string " flattened ridgeline ahead,\p"
    .string "beware!$"

Trade_Text_HowIsMyOldMon::
    .string "How is my old sword?n My brother\p"
    .string "is doing great!$"

