gOtherText_NewName::
    .string "Enter a name for your adventurer:$"

gNameChoice_Green::
    .string "'You find a small pile of\p"
    .string "emeralds!'$"

gNameChoice_Red::
    .string "CAUTION: ROBOT ENEMY AHEAD!$"

gNameChoice_Leaf::
    .string "'Golden Leaf Found!'$"

gNameChoice_Fire::
    .string "'BONFIRE AHEAD! BEWARE OF LAVA\p"
    .string "below'$"

gNameChoice_Gary::
    .string "WELCOME TO THE CAVE OF WONDERS!$"

gNameChoice_Kaz::
    .string "'Low balance. Sheq coins needed!'$"

gNameChoice_Toru::
    .string "ENTER PASSWORD?$"

gNameChoice_Ash::
    .string "YOU'VE FALLEN INTO A PIT OF SPiky\p"
    .string "DEBRIS.$"

gNameChoice_Kene::
    .string "'You possess the key. Proceed with\p"
    .string "caution.'$"

gNameChoice_Geki::
    .string "'ALIEN ASSAULT IMMINENT!'$"

gNameChoice_Jak::
    .string "ANGER!$"

gNameChoice_Janne::
    .string "FINDING JOB OFFICE... GOOD LUCK$"

gNameChoice_Jonn::
    .string "'The slumbering dragon, Zorvath,\p"
    .string "stirs in the dark depths of the\n"
    .string "VOLCANO CAVE.'$"

gNameChoice_Kamon::
    .string "'You Must Conquer the Dojo to\p"
    .string "Unlock the Next Level'$"

gNameChoice_Karl::
    .string "'HA! I SEE YOU'RE READY FOR ROUND\p"
    .string "2!'$"

gNameChoice_Taylor::
    .string "Welcome back, Taylor!$"

gNameChoice_Oscar::
    .string "You have obtained OSCAR, a shiny\p"
    .string "new keycard. What will you do\n"
    .string "next?$"

gNameChoice_Hiro::
    .string "' nalara! '$"

gNameChoice_Max::
    .string "MAXIMUM MORTGAGE! 5000$"

gNameChoice_Jon::
    .string "'Welcome to Mega City, Jon!'$"

gNameChoice_Ralph::
    .string "You stumble upon an old trunk in\p"
    .string "the corner of the room...$"

gNameChoice_Kay::
    .string "STREET FIGHTER$"

gNameChoice_Tosh::
    .string "INSERT QUARTER$"

gNameChoice_Roak::
    .string "CRUMBLING BRIDGE AHEAD!$"

gNameChoice_Omi::
    .string "'Power Source Detected!'$"

gNameChoice_Jodi::
    .string "CLASSES UNLOCKED. AIM FOR THE TOP!$"

gNameChoice_Amanda::
    .string "'Cannot Access Amanda's Files. Sec\p"
    .string "Clearance Required.'$"

gNameChoice_Hillary::
    .string "'CLIMB TO THE SUMMIT'$"

gNameChoice_Makey::
    .string "Repair Shop Ahead.$"

gNameChoice_Michi::
    .string "WELCOME HOME$"

gNameChoice_Paula::
    .string "HELP ARRIVES!$"

gNameChoice_June::
    .string "WARMth SETTLES OVER THE DESERT.$"

gNameChoice_Cassie::
    .string "'Energy: 80/100'$"

gNameChoice_Rey::
    .string "'Fuel tanks: 50 lifes: 3'$"

gNameChoice_Seda::
    .string "'Echoes of the past await your\p"
    .string "uncovering.'$"

gNameChoice_Kiko::
    .string "ENTER PIN?$"

gNameChoice_Mina::
    .string "'Welcome to Mina's Castle'$"

gNameChoice_Norie::
    .string "'Welcome, Norie '$"

gNameChoice_Sai::
    .string "SAILBACK ANGRILY$"

gNameChoice_Momo::
    .string "'CRITICAL ERROR DETECTED: MOMO\p"
    .string "QUEEN DOWN!'$"

gNameChoice_Suzi::
    .string "'This way, lest ye face the claw!'$"

gControlsGuide_Text_Intro::
    .string "JETSTICK: Explanation Coming Up$"

gControlsGuide_Text_DPad::
    .string "Press Enter$"

gControlsGuide_Text_AButton::
    .string "CONFIRM Choice?$"

gControlsGuide_Text_BButton::
    .string "CANCEL$"

gControlsGuide_Text_StartButton::
    .string "PUSH TO OPEN MENU$"

gControlsGuide_Text_SelectButton::
    .string "USE N/U$"

gControlsGuide_Text_LRButtons::
    .string "PERFECT YOUR SKILLS ALREADY!$"

gOakSpeech_Text_AskPlayerGender::
    .string "The spirits of the land whisper to\p"
    .string "me...$"

gPikachuIntro_Text_Page1::
    .string "GREETINGS, ADVENTURER! YOU'VE\p"
    .string "ENTERED THE LAND OF TORR socks.$"

gPikachuIntro_Text_Page2::
    .string "'The whispers of the ancient ones\p"
    .string "grow faint, but a new path\n"
    .string "awaits!'$"

gPikachuIntro_Text_Page3::
    .string "Prepare for self-discovery...$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "WELCOME TO Pallet Town!$"

gOakSpeech_Text_ThisWorld::
    .string "...of eternal darkness.$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "STRANGE SMELL IN AIR$"

gOakSpeech_Text_IStudyPokemon::
    .string "Professor Oak's words echo in my\p"
    .string "mind... 'Gotta catch 'em all!'\n"
    .string "Some new leads on a rare species\p"
    .string "emerged...$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Name: Zaran Title: Last Hopen\p"
    .string "Class: Warrior$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "STRANGER, MY NAME IS RAVEN\p"
    .string "BLACKWOOD.$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "You're the legendary hero of old,\p"
    .string "seeking fortune and fame.$"

gOakSpeech_Text_WhatWasHisName::
    .string "You see the wispy form of Buster!$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "'BOWTIER'$"

gOakSpeech_Text_ConfirmRivalName::
    .string "'A HECK YES, IT WAS!'$"

gOakSpeech_Text_RememberRivalsName::
    .string "'ZNACKER!'$"

gOakSpeech_Text_LetsGo::
    .string "POKeMON Trainer School Wing, your\p"
    .string "starting point awaits!$"

