Text_ObtainedTheX::
    .string "' strengthens your legs!'$"

Text_BagIsFull::
    .string "NOT ENOUGH ROOM!$"

Text_PutItemAway::
    .string "You put the potion in the chest.$"

Text_FoundOneItem::
    .string "You found one Golden Feather!$"

Text_TooBadBagFull::
    .string "TRY THE TRADER!$"

Text_FoundXCoins::
    .string "You found Ancient Temple Keys!$"

Text_PutCoinsAwayInCoinCase::
    .string "You stash the loot securely.$"

Text_CoinCaseIsFull::
    .string "'DUPLICATE COINS! TRY OTHER\p"
    .string "SLOTS?'$"

Text_NothingToPutThemIn::
    .string "'EMPTY INVENTORY'$"

Text_FoundXItems::
    .string "Trap 5 treasure chests!$"

Text_ObtainedTheDecor::
    .string "' strengthens your legs!'$"

Text_NoRoomForAnotherDecor::
    .string "'None to spare!'$"

Text_DecorTransferredToPC::
    .string "'Data transfer complete. ECX:\p"
    .string "000001'$"

