Text_BootedUpPC::
    .string "'Welcome to Cyberpunk 2087!'$"

Text_AccessWhichPC::
    .string "'Security Mainframe PC Alpha\p"
    .string "bribed?'$"

Text_AccessedSomeonesPC::
    .string "'Hacking Data...'$"

Text_OpenedPkmnStorage::
    .string "'You have 3 open slots.'$"

Text_AccessedPlayersPC::
    .string "'Files:  BANK RECORDS  LOVE\p"
    .string "LETTERS  PROGRAMMER'S NOTES'$"

Text_AccessedBillsPC::
    .string "Diskette inserted. File contents:\p"
    .string "'MYDIARY.TXT'...$"

