Text_MonSentToBoxInSomeonesPC::
    .string "GRIZZ'S TREASURE was transferred\p"
    .string "to Someone's PC. It was placed in\n"
    .string "BOX 'Pirate's Booty.'$"

Text_MonSentToBoxInBillsPC::
    .string "PLAYER'S NOTES was transferred to\p"
    .string "BILL'S PC. It was placed in BOX\n"
    .string "'INVENTORY'.$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "Box 'System' on Someone's PC was\p"
    .string "full.  Data was transferred to Box\n"
    .string "'Save'.$"

Text_MonSentToBoxBillsBoxFull::
    .string "BOX 'DOS DATA' on BILL'S PC was\p"
    .string "full. DOSUPG was transferred to\n"
    .string "BOX 'dosdata.'$"

Text_PlayerObtainedTheMon::
    .string "You obtained the Sword!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "Unable to carry Pokemon son Stored\p"
    .string "STRVAR1 in computer boxn STRVAR2\n"
    .string "flashed on screen!$"

Text_NoMoreRoomForPokemon::
    .string "You caught too many!$"

