Text_MayIHelpYou::
    .string "VENTORY EXHAUSTED. SEARCH FOR MORE\p"
    .string "SUPPLIES.$"

Text_FillOutQuestionnaire::
    .string "PAPERWORK LOOMS!$"

Text_QuestionnaireThankYou::
    .string "THANK YOU FOR YOUR TIME$"

Text_YouKnowThoseWords::
    .string "'Gift received! Polaroid photo of\p"
    .string "clairvoyant skull?'$"

Text_YouCanAccessMysteryGift::
    .string "Mystery Gift Unlocked!$"

Text_ThankYouForAccessingMysteryGift::
    .string "UNLOCKED: GLOWING AMULET$"

