Pokedude_Text_SpeedierBattlerGoesFirst::
    .string "'Choose your attack!'$"

Pokedude_Text_MyRattataFasterThanPidgey::
    .string "You Found 50 COPPberries!$"

Pokedude_Text_BattlersTakeTurnsAttacking::
    .string "ENEMY WOUNDED!rh 20 HP$"

Pokedude_Text_MyRattataWonGetsEXP::
    .string "Your Rattata is a WINNER!$"

Pokedude_Text_UhOhRattataPoisoned::
    .string "'WANT TO USE AN ANTI-POISON?!'$"

Pokedude_Text_HealStatusRightAway::
    .string "'POKE POWER REGEN!'$"

Pokedude_Text_UsingItemTakesTurn::
    .string "Opponent's STRATOSAUR sends out\p"
    .string "TOXICORUS!$"

Pokedude_Text_YayWeManagedToWin::
    .string "CONGRATULATIONS! YOU HAVE\p"
    .string "SUCCEEDED IN DEFEATING THE DARK\n"
    .string "LORD!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
    .string "The WATER-type attack inflicts\p"
    .string "only half the usual damage!$"

Pokedude_Text_GrassEffectiveAgainstWater::
    .string "SUPER EFFECTIVE!$"

Pokedude_Text_LetsTryShiftingMons::
    .string "WHAT'S YOUR PLAN, TRAINER?$"

Pokedude_Text_ShiftingUsesTurn::
    .string "'Opponent sends out: WEEDLE!'$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
    .string "'Grass-type attacks weak!'$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
    .string "You can't catch me, trainer!$"

Pokedude_Text_YeahWeWon::
    .string "VICTORY!$"

Pokedude_Text_WeakenMonBeforeCatching::
    .string "WARP POWER RESTORED!$"

Pokedude_Text_BestIfTargetStatused::
    .string "'Timing looks ripe... TRY THROW!'$"

Pokedude_Text_CantDoubleUpOnStatus::
    .string "Use Hypno's Confusion status\p"
    .string "overturned?$"

Pokedude_Text_LetMeThrowBall::
    .string "IT'S SUPER EFFECTIVE!$"

Pokedude_Text_PickBestKindOfBall::
    .string "Choose wisely!$"

