PokedexRating_Text_HowIsPokedexComingAlong::
    .string "Many catches so far, Professor!$"

PokedexRating_Text_SeenXOwnedY::
    .string "000 / 124 POKeMON seen and 002\p"
    .string "POKeMON owned.$"

PokedexRating_Text_LessThan10::
    .string "ITEM BAG FULL!$"

PokedexRating_Text_LessThan20::
    .string "You found the FLASH! What's next?\p"
    .string "HM...$"

PokedexRating_Text_LessThan30::
    .string "'Captain Cassiopeia's Pokedex\p"
    .string "says: Add more variety, trainer!'$"

PokedexRating_Text_LessThan40::
    .string "Collect aid from behind waterfall.$"

PokedexRating_Text_LessThan50::
    .string "CRUCIAL AIDE.Joining the battle!$"

PokedexRating_Text_LessThan60::
    .string "You got a new AIDE! What will you\p"
    .string "name it?$"

PokedexRating_Text_LessThan70::
    .string "FOUND: PIKACHU!$"

PokedexRating_Text_LessThan80::
    .string "Fishing Spot: Lake Veritas$"

PokedexRating_Text_LessThan90::
    .string "A rare-seeked Orbadilite!$"

PokedexRating_Text_LessThan100::
    .string "WOWZA! CRUSHING SCORE RISES TO\p"
    .string "1000!$"

PokedexRating_Text_LessThan110::
    .string "CONGRATULATIONS, YOU'VE REACHED A\p"
    .string "MAJOR MILESTONE!$"

PokedexRating_Text_LessThan120::
    .string "'EVOLVED FORMS CONFIRMED!'$"

PokedexRating_Text_LessThan130::
    .string "TRADE ITEMS W/ FRIENDS TO BOOST\p"
    .string "stash!$"

PokedexRating_Text_LessThan140::
    .string "WELL DONE, CHAMPION!$"

PokedexRating_Text_LessThan150::
    .string " receive receive it!$"

PokedexRating_Text_Complete::
    .string "'Hey there, Trainer!'$"

PokedexRating_Text_NationalDexSeenXOwnedY::
    .string "Your NATIONAL POKeDEX is: 45\p"
    .string "POKeMON seen and 20 POKeMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
    .string "'You have 249 Pokemon to go!'$"

PokedexRating_Text_YouveCompletedDex::
    .string "YOU'VE DONE IT, TRAINER!$"

PokedexRating_Text_Wroooaaarrr::
    .string "Dragon Approaches!$"

PokedexRating_Text_HaHa::
    .string "You're getting dizzy from the\p"
    .string "spinning blades. Better get outta\n"
    .string "here!$"

PokedexRating_Text_ThankYouMadeDreamReality::
    .string "THANK YOU FOR MAKING MY DREAM\p"
    .string "REALITY!$"

PokedexRating_Text_LoveSeeingYourPokedex::
    .string "My POKeDEX is complete!$"

