Text_OnlySkilledTrainersAllowedThrough::
    .string "Build your team first!$"

Text_CantLetYouPass::
    .string "'BUSTED! NOW IT'S TIME TO FACE THE\p"
    .string "MUSIC, KID!'$"

Text_OhThatsBadgeGoRightAhead::
    .string "UFO special forces have landed!$"

Text_OnlyPassWithBadgeDontHaveYet::
    .string "Get STRVAR1 to advance!$"

Text_OnlyPassWithBadgeOhGoAhead::
    .string "You must have the Sceptre.$"

