gText_WouldYouLikeToSaveTheGame::
    .string "Y/N?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
    .string "Y/N$"

gText_SavingDontTurnOffThePower::
    .string "Save Successful!$"

gText_PlayerSavedTheGame::
    .string "Game Saved!$"

gText_SaveFailed2::
    .string "Maths Error: SAVE FILE CORRUPT.$"

gText_DifferentGameFile::
    .string "Say YES to overwrite or NO to\p"
    .string "cancel?$"

