@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
    .string "Maybe? Try again!$"

PalletTown_Text_OhLookLook::
    .string "SECRET RUINS DISCOVERED!$"

PalletTown_Text_ReadItReadIt::
    .string "Decrypting Ancient Scrolls...$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
    .string "SELECT OPTIONS CERAELY$"

PalletTown_Text_SignsAreUsefulArentThey::
    .string "MAP FOUND!$"

PalletTown_Text_LookCopiedTrainerTipsSign::
    .string "'BATTLE WIZARDRY: CAST SHIELD\p"
    .string "FIRST!'$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
    .string "ITEM SLOTS FULL! DUMP SOME JUNK!$"

