VSSeeker_Text_BatteryNotChargedNeedXSteps::
    .string "Insufficient Power! Must recharge:\p"
    .string "X900 Steps.$"

VSSeeker_Text_NoTrainersWithinRange::
    .string "PUSH YOUR SEEKER...$"

VSSeeker_Text_TrainersNotReady::
    .string "WAIT FOR THE OTHERS!$"

Route3_Text_ColtonRematchIntro::
    .string "'STRANGER SPOTTED! WHAT BRINGS YOU\p"
    .string "TO THESE DARKEST HOURS?'$"

Route3_Text_BenRematchIntro::
    .string "FRESH AIR Frenzy!$"

Route3_Text_JaniceRematchIntro::
    .string " debris debris debris  lyk\p"
    .string "ostanovilsialyolon$"

Route3_Text_GregRematchIntro::
    .string "POST-BATTLE INTERVIEW$"

Route3_Text_SallyRematchIntro::
    .string " Outstanding Outstanding!$"

Route3_Text_CalvinRematchIntro::
    .string "CITIZEN ALERT: WEAR SHORTS NOW!$"

Route3_Text_JamesRematchIntro::
    .string "Your POKeMON ready!$"

Route3_Text_RobinRematchIntro::
    .string "Whoa, sorry buddy!$"

Route4_Text_CrissyRematchIntro::
    .string "'Traded Clefairy for a Voltorb!'$"

Route6_Text_RickyRematchIntro::
    .string "'YOU SNEAKY KID!'$"

Route6_Text_NancyRematchIntro::
    .string "SHHHH! KEEP IT DOWN, SNEAK!$"

Route6_Text_KeigoRematchIntro::
    .string "You found the Abandoned Lab.\p"
    .string "Research reveals 3 Electric-types.\n"
    .string "Which one will you catch?$"

Route6_Text_JeffRematchIntro::
    .string "'Friendship calls, danger\p"
    .string "too...accept?'$"

Route6_Text_IsabelleRematchIntro::
    .string "You are in a dimly lit tavern,\p"
    .string "whispers of mischief in the air.$"

Route6_Text_ElijahRematchIntro::
    .string "Seasoned Warrior Stands Ready$"

Route8_Text_AidanRematchIntro::
    .string "C- Better odds of catching a rare\p"
    .string "Pokemon than acing chem!$"

Route8_Text_StanRematchIntro::
    .string "'YOU'RE IN A MAZE'$"

Route8_Text_GlennRematchIntro::
    .string "Be reassured, enemy is weak.$"

Route8_Text_PaigeRematchIntro::
    .string "'Prevent Evolution by using a\p"
    .string "Mystic Gem!'$"

Route8_Text_LeslieRematchIntro::
    .string "YOU'VE GOT A POINT THERE, KID!$"

Route8_Text_AndreaRematchIntro::
    .string "'Whiskers twitching, these\p"
    .string "cute'mons await capture!'$"

Route8_Text_MeganRematchIntro::
    .string "'WELCOME TO THE EXTREME QUARRY!'$"

Route8_Text_RichRematchIntro::
    .string "WOOHOO! 5 IN A ROW!$"

Route8_Text_JuliaRematchIntro::
    .string "IT'S PONYTA!$"

Route8_Text_RicardoRematchIntro::
    .string "' Bike Turbo Malfunction: Repair\p"
    .string "Shop Needed!'$"

Route8_Text_JarenRematchIntro::
    .string "'ROGUE ARMY APPROACHES!'$"

Route8_Text_EliRematchIntro::
    .string "'SYNERGY MAXED!'$"

Route8_Text_AnneRematchIntro::
    .string "POWERED UP! mente requires HIGH\p"
    .string "FUEL.$"

Route9_Text_AliciaRematchIntro::
    .string "FACING ME ARE YOU?$"

Route9_Text_ChrisRematchIntro::
    .string "'Who's with me?'$"

Route9_Text_DrewRematchIntro::
    .string "Need to find PEANUT in POKEMON\p"
    .string "CENTER first!$"

Route9_Text_CaitlinRematchIntro::
    .string "YOU CHEAT, WILL YA?!$"

Route9_Text_JeremyRematchIntro::
    .string "'You're no match for me!'$"

Route9_Text_BriceRematchIntro::
    .string "BRUTE STORM AHEAD!$"

Route9_Text_BrentRematchIntro::
    .string "'Your Bug-type POKeMON is now\p"
    .string "Level 5!'$"

Route9_Text_AlanRematchIntro::
    .string "YOU DARE CHALLENGE ME AGAIN?$"

Route9_Text_ConnerRematchIntro::
    .string "'Whatever the universe throws at\p"
    .string "thee, shall meet bitter end!'$"

Route10_Text_MarkRematchIntro::
    .string "'PKM: 12 Catches: 7'$"

Route10_Text_ClarkRematchIntro::
    .string "Oh no! Sneezing fits run in the\p"
    .string "family...$"

Route10_Text_HermanRematchIntro::
    .string " GOTCHA!$"

Route10_Text_HeidiRematchIntro::
    .string "' bitter defeat AGAIN!'$"

Route10_Text_TrentRematchIntro::
    .string "STUCK IN THE MIST!$"

Route10_Text_CarolRematchIntro::
    .string "'Paths converge ahead, but which\p"
    .string "way?'$"

Route11_Text_HugoRematchIntro::
    .string "LET'S END THIS EXISTING RIVALRY\p"
    .string "ONCE AND FOR ALL!$"

Route11_Text_JasperRematchIntro::
    .string "ARE YOU READY FOR ACTION?!$"

Route11_Text_EddieRematchIntro::
    .string "'FAIRPLAY MODE Enabled. No way\p"
    .string "out!'$"

Route11_Text_BraxtonRematchIntro::
    .string "Danger! Wiring down. Stay back!$"

Route11_Text_DillonRematchIntro::
    .string "YOU'VE GOT WHAT IT TAKES!$"

Route11_Text_DirkRematchIntro::
    .string "'Brave warrior, begone!'$"

Route11_Text_DarianRematchIntro::
    .string "'Take the leap of faith?'$"

Route11_Text_YasuRematchIntro::
    .string " lvl 10 KUNG FUIS READY FOR BATTLE$"

Route11_Text_BernieRematchIntro::
    .string "WATCH YOUR STEP CAREFULLY!$"

Route11_Text_DaveRematchIntro::
    .string "The moment of truth approaches...$"

Route12_Text_NedRematchIntro::
    .string "FISH ON!$"

Route12_Text_ChipRematchIntro::
    .string "'Got a nibble!'$"

Route12_Text_JustinRematchIntro::
    .string "'Talk to Old Man in Willowdale'$"

Route12_Text_LucaRematchIntro::
    .string "'Maybe they're like sparks, but in\p"
    .string "water?'$"

Route12_Text_HankRematchIntro::
    .string "Fishing Fool's Lure: 10/10 HP$"

Route12_Text_ElliotRematchIntro::
    .string "'Need more credits to buy bait!'$"

Route12_Text_AndrewRematchIntro::
    .string "Try hitting my sweet spot!$"

Route12_Text_JesRematchIntro::
    .string "YOU CAN'T AUTO-RESUPERCHARGE YOUR\p"
    .string "SWORD HERE. TRY AGAIN.$"

Route12_Text_GiaRematchIntro::
    .string "'Will you defeat Draxon and prove\p"
    .string "your worth to me?'$"

Route13_Text_SebastianRematchIntro::
    .string "Familiar Feathers Flap Once$"

Route13_Text_SusieRematchIntro::
    .string "EMBARK ON YOUR JOURNEY!$"

Route13_Text_ValerieRematchIntro::
    .string "BADGE UP!! 5 NEW STREAKS AWARD$"

Route13_Text_GwenRematchIntro::
    .string "'A warm welcome back, trainer!'$"

Route13_Text_AlmaRematchIntro::
    .string "YOUR SUPPLIES NOWcontain 10\p"
    .string "CARBOS.$"

Route13_Text_PerryRematchIntro::
    .string "'GOING FOR IT!'$"

Route13_Text_LolaRematchIntro::
    .string "'THE AGES HAVE PASSED, BUT YOUR\p"
    .string "QUEST IS REBORN. WHAT IS YOUR\n"
    .string "CHOICE?'$"

Route13_Text_SheilaRematchIntro::
    .string "'It's personal now. Prepare to\p"
    .string "finish this!'$"

Route13_Text_JaredRematchIntro::
    .string "'A strange glow emanates from the\p"
    .string "cave entrance.'$"

Route13_Text_RobertRematchIntro::
    .string "YOU SEEK THE WISDOM OF THE AVIAN\p"
    .string "KIND?$"

Route14_Text_CarterRematchIntro::
    .string "'Readies Burglar!'$"

Route14_Text_MitchRematchIntro::
    .string "POKEMON: Starly, Level 5$"

Route14_Text_BeckRematchIntro::
    .string "IMPORTING TM INTO POKEMON...$"

Route14_Text_MarlonRematchIntro::
    .string "Press A to start bird training!$"

Route14_Text_DonaldRematchIntro::
    .string "'Seeker of Dusty Dreams, beware!'$"

Route14_Text_BennyRematchIntro::
    .string "DON'T BE SUCH A SLACKER!$"

Route14_Text_LukasRematchIntro::
    .string "'OLD FRIENDS UNITE! JOIN ME!'$"

Route14_Text_IsaacRematchIntro::
    .string "You're no match for my skills!$"

Route14_Text_GeraldRematchIntro::
    .string "' Desert Horizon in Sight!'$"

Route14_Text_MalikRematchIntro::
    .string "Level up! Squirtle know Tackle!$"

Route14_Text_KiriRematchIntro::
    .string "BET ON KIRI'S TEAM TODAY? Y/N$"

Route14_Text_JanRematchIntro::
    .string "'You're On!'$"

Route15_Text_KindraRematchIntro::
    .string "'Training Monty the Metapod...'$"

Route15_Text_BeckyRematchIntro::
    .string "'You shouldn't have said that...'$"

Route15_Text_EdwinRematchIntro::
    .string "TWEET!$"

Route15_Text_ChesterRematchIntro::
    .string "FELIX! WE MEET AGAIN!$"

Route15_Text_GraceRematchIntro::
    .string "You're LAIRICOT!$"

Route15_Text_OliviaRematchIntro::
    .string "SAFETY FIRST!$"

Route15_Text_ErnestRematchIntro::
    .string "FREE DEATH STICKS!$"

Route15_Text_AlexRematchIntro::
    .string "You're OUT of league!$"

Route15_Text_CeliaRematchIntro::
    .string "Poke Mart: Refined Weedle, 5 Coins$"

Route15_Text_YazminRematchIntro::
    .string "Y/N$"

Route15_Text_MyaRematchIntro::
    .string "'You're still stuck in the past,\p"
    .string "ain't ya?'$"

Route15_Text_RonRematchIntro::
    .string "'The woods burn with her wrath!'$"

Route16_Text_LaoRematchIntro::
    .string "'SEEK WIZARD'S TOWER TO CLAIM\p"
    .string "POWER!'$"

Route16_Text_KojiRematchIntro::
    .string "You don't want trouble, pal...$"

Route16_Text_LukeRematchIntro::
    .string "Warning: Carnage Ahead!$"

Route16_Text_HideoRematchIntro::
    .string "WHO DARES TO SUMMON YOU, THEN FLEE\p"
    .string "LIKE A COWARD?$"

Route16_Text_CamronRematchIntro::
    .string "'PUNY DINOSAURAhead!'$"

Route16_Text_RubenRematchIntro::
    .string "'MURDER BUG ZONE AHEAD'$"

Route16_Text_JedRematchIntro::
    .string "WHY DO YOU SEEK THE FATE-TORN DUO?$"

Route16_Text_LeaRematchIntro::
    .string "HEARTBEAT RACING?$"

Route17_Text_RaulRematchIntro::
    .string "You're at a rough spot.$"

Route17_Text_IsaiahRematchIntro::
    .string "'WHOA, I'M A STRONG ONE!'$"

Route17_Text_VirgilRematchIntro::
    .string "'Looks like a trap ahead. Heed the\p"
    .string "warning!'$"

Route17_Text_BillyRematchIntro::
    .string "'RIP RIDE FOR ROMAN ROAD'$"

Route17_Text_NikolasRematchIntro::
    .string "GET READY FOR\p"
    .string "SHOCKEHOLD!/assistantassistant\n"
    .string "PROTECT YOURSELF\p"
    .string "NOW!/assistantassistant  VOLTORB:\n"
    .string "120V APPLIED!/assistantassistant\p"
    .string "ZAP! YOU'RE\n"
    .string "PARALYZED!/assistantassistant\p"
    .string "RECHARGE NOW OR FACE\n"
    .string "SHOCK!/assistantassistant\p"
    .string "WARNING: LOW\n"
    .string "BATT./assistantassistant  VOLTORB\p"
    .string "LOADING.../assistantassistant\n"
    .string "STATIC\p"
    .string "BUILDING.../assistantassistant\n"
    .string "volts IGNITED!/assistantassistant\p"
    .string "CHARGE BUILT!/assistantassistant\n"
    .string "ZAP! YOU'RE\p"
    .string "OUT!/assistantassistant  VOLTORB'S\n"
    .string "GOT GAME!/assistantassistant\p"
    .string "CALLING IN THESE SHOCKS UNTIL YOU\n"
    .string "GET WEAK!/assistantassistant  YOUR\p"
    .string "SHOCKING POOR\n"
    .string "CHOICE.../assistantassistant  ZAP!\p"
    .string "OUT OF COMMISSION!/assistant$"

Route17_Text_ZeekRematchIntro::
    .string "'EVOLVE CHECK FAILED: NEED zmchik-\p"
    .string "part'$"

Route17_Text_JamalRematchIntro::
    .string "GET READY, PARTY!$"

Route17_Text_CoreyRematchIntro::
    .string "'Join Rizzo's Rogue Squad'$"

Route17_Text_JaxonRematchIntro::
    .string "'Sweet baby, it grips like glue!'$"

Route17_Text_WilliamRematchIntro::
    .string "You think you can take me down?$"

Route18_Text_WiltonRematchIntro::
    .string "'Must've scared 'em all off\p"
    .string "already'$"

Route18_Text_RamiroRematchIntro::
    .string "CKCK! Nearly, Professor\p"
    .string "Puddingpip!$"

Route18_Text_JacobRematchIntro::
    .string "'Buddy, you're askin' for\p"
    .string "trouble...'$"

Route19_Text_RichardRematchIntro::
    .string "WATER IS COOL TODAY!$"

Route19_Text_ReeceRematchIntro::
    .string "UNSAFE! Keep moving or face the\p"
    .string "Dark Baron's wrath!$"

Route19_Text_MatthewRematchIntro::
    .string "You're more hooked on water than a\p"
    .string "fish on a lily pad!$"

Route19_Text_DouglasRematchIntro::
    .string "MOUNTAIN RANGE APPROACHES.$"

Route19_Text_DavidRematchIntro::
    .string "Diver's Rejected Again$"

Route19_Text_TonyRematchIntro::
    .string "'YOU'LL NOT BEAT ME AGAIN!'$"

Route19_Text_AnyaRematchIntro::
    .string "WANT POKEMON?$"

Route19_Text_AliceRematchIntro::
    .string "Watch out for jellyfish!$"

Route19_Text_AxleRematchIntro::
    .string "Beware the Guardian of the Depths!$"

Route19_Text_ConnieRematchIntro::
    .string "Explore the depths?$"

Route19_Text_LiaRematchIntro::
    .string "WHAT KIND OF HELP DO YOU NEED?$"

Route19_Text_LucRematchIntro::
    .string "'Gotta be brave, little bro!'$"

Route20_Text_BarryRematchIntro::
    .string "'Safe waters ahead!'$"

Route20_Text_ShirleyRematchIntro::
    .string "'HAH! ENVY FUELS MY GUILT!'$"

Route20_Text_TiffanyRematchIntro::
    .string "Dive deeper: 10 Gold Coins found!$"

Route20_Text_IreneRematchIntro::
    .string "'SAVED BY A TRUSTY PILGRIM!'$"

Route20_Text_DeanRematchIntro::
    .string "/extreme flexing/$"

Route20_Text_DarrinRematchIntro::
    .string "'Help! Proto uncontrollable!'$"

Route20_Text_RogerRematchIntro::
    .string "'NEW LAND IN SIGHT!'$"

Route20_Text_NoraRematchIntro::
    .string "PEARLS ENLARGED!$"

Route20_Text_MissyRematchIntro::
    .string "DEEP WATERS BEHIND ME, NEW LAND\p"
    .string "AHEAD!$"

Route20_Text_MelissaRematchIntro::
    .string "'Welcome to Cinnabar Labs.\p"
    .string "Research  Development facility.\n"
    .string "Home of the Pokemon Master.'$"

Route21_North_Text_RonaldRematchIntro::
    .string "'Fishing's Slow Today'$"

Route21_North_Text_WadeRematchIntro::
    .string "Lootkeeper:: 10 Gold, 5 Ruby, 1\p"
    .string "Magic Orb$"

Route21_North_Text_SpencerRematchIntro::
    .string "'CRYSTAL CLEAR WATERS RENEW YOUR\p"
    .string "STRENGTH!'$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
    .string "FLOODINGS GETTING WORSE!$"

Route21_South_Text_JackRematchIntro::
    .string "AND NOW, YOUR TRAINER LOGueumentS\p"
    .string "THE CAUGHT SEASHORE SQUAD!$"

Route21_South_Text_JeromeRematchIntro::
    .string "GET READY TO SWIM, BIKE, AND RUN\p"
    .string "FOR THE FLAG!$"

Route21_South_Text_RolandRematchIntro::
    .string "WELCOME TO THE ISLAND OF ZARA!$"

Route21_South_Text_ClaudeRematchIntro::
    .string "FEEBISH FLEEING FROM THE LAKE BED!$"

Route21_South_Text_NolanRematchIntro::
    .string "'Monster approaching from the\p"
    .string "depths...!'$"

Route21_North_Text_LilRematchIntro::
    .string "BATTLE ENEMY ENCOUNTER!$"

Route21_North_Text_IanRematchIntro::
    .string "GET LUCKY SOCKS FOR HER WEAR THEM\p"
    .string "TILL SHE'S SET TO CLEAN!$"

Route25_Text_JoeyRematchIntro::
    .string "YOU DARE TO CHALLENGE ME?$"

Route25_Text_DanRematchIntro::
    .string " YOU'RE ON A ROLL NOW, KID!$"

Route25_Text_FlintRematchIntro::
    .string "YOU'RE LOOKING GOOD, BUDDY!$"

Route25_Text_KelseyRematchIntro::
    .string "'Condition upgrade alert: 10\p"
    .string "ENDUR!'$"

Route25_Text_ChadRematchIntro::
    .string "FIREBLAST AT THE READY!$"

Route25_Text_HaleyRematchIntro::
    .string "' Hokmok's Pallet is POPPING with\p"
    .string "CUTE POKEMON!$"

Route25_Text_FranklinRematchIntro::
    .string "STAVING OFF THE GAS PINCH!$"

Route25_Text_NobRematchIntro::
    .string "'Rare species!/p$"

Route25_Text_WayneRematchIntro::
    .string "'Prepare to rumble, medal hunter!'$"

Route24_Text_ShaneRematchIntro::
    .string "You see the enemy's descent!$"

Route24_Text_EthanRematchIntro::
    .string "ROGUE GIANT SPIDER APPEARS!$"

Route24_Text_ReliRematchIntro::
    .string "'Eyes on the road, pal! Can't stop\p"
    .string "till the journey's done!'$"

Route24_Text_TimmyRematchIntro::
    .string "Avoiding pesky skeletons...$"

Route24_Text_AliRematchIntro::
    .string "FATE TWEAKING MY ROOSTER..........\p"
    .string "..................................\n"
    .string "......$"

Route24_Text_CaleRematchIntro::
    .string "DO YOU ACCEPT THE CHALLENGE?$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
    .string "TUMULTUOUS SEA Siren's Call!$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
    .string "'boundless blue skies await!'$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
    .string "Brrr... Desert Storm Response Team\p"
    .string "needed at Ratables Oasis.$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
    .string "ADVENTURE AWAITS BENEATH$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
    .string "'HERE WE GO AGAIN!'$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
    .string "Big catch! Will it pull ya in?$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
    .string "DO YOU THINK YOU'VE GOT WHAT IT\p"
    .string "TAKES?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
    .string "'Day 15: Pushing limits!'$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
    .string "FINISHING UP MORNING SWIM!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
    .string "' equip warrior armor'$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
    .string "'Ration Pkt: Energy Bar'$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
    .string "'BRING IT ON, CHUMP!'$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
    .string "BROTHERLY LOVEprevails in this\p"
    .string "battle!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
    .string "'The Showdown Begins!xcf7'$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
    .string "'Enemies approach! Prepare for\p"
    .string "combat!'$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
    .string "'Darkness besets the Undying\p"
    .string "Plains'$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
    .string "'DITCH FLOAT RISKY?'$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
    .string " territorial dispute with wild\p"
    .string "Pidgey!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
    .string "'GO BACK, TRAVELER!'$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
    .string "'Stats boosted: STR5, END3.'$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
    .string "BRUTE FORCE: Bring it on, puny\p"
    .string "villain!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
    .string "'The POKe BALLS are empty, what's\p"
    .string "going on?'$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
    .string "VICTORY IS MINE!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
    .string "Leave me alone!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
    .string "TRY AGAIN!$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
    .string "'BRING IT ON! CHOOSE YOUR PATH'$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
    .string "Come back later, rival!$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
    .string "YEAH! SPEED BOOSTERaponud!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
    .string "'Ahoy, partner! Greetings from the\p"
    .string "Tavern!'$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
    .string "BEAKS OF GOLD await theeometrics!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
    .string "YOU CHALLENGE FEATHER!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
    .string ".presumed dead, now seeking\p"
    .string "feathered vengeance!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
    .string "BATTLE!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
    .string "YOU MADE IT ALIVE!$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
    .string "FINAL REVENGE!$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
    .string "ENEMY SHIP SIGHTED!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
    .string "Sis-Battle Boost: 10 HP 5 STR$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
    .string "WARP GLITCH! RECALIBRATE YES/NO$"

SixIsland_WaterPath_Text_RoseRematchIntro::
    .string "'WELCOME TO SUNNY TOWN!'$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
    .string "'Most Excellent Skill: ntaining!'$"

SixIsland_WaterPath_Text_SamirRematchIntro::
    .string "YOU CLOWN!$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
    .string "'Lost in thought, you frown...'$"

SixIsland_WaterPath_Text_EarlRematchIntro::
    .string "'Try the map on the town hall\p"
    .string "wall, friend.$"

SixIsland_WaterPath_Text_MiuRematchIntro::
    .string "POKEMON FIGHTING!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
    .string " Trainer, I choose Squirtle!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
    .string "'Seek ancient texts in ruins east\p"
    .string "of town.'$"

SixIsland_RuinValley_Text_FosterRematchIntro::
    .string "Stranger in town. Rough rumors\p"
    .string "spread of ancient ruins hidden\n"
    .string "here...$"

SixIsland_RuinValley_Text_LarryRematchIntro::
    .string "Found 3 glowing rocks near ancient\p"
    .string "ruins.$"

SixIsland_RuinValley_Text_DarylRematchIntro::
    .string "'FRESH FROM THE FRAY, READY FOR\p"
    .string "ROUND 2!'$"

SixIsland_RuinValley_Text_HectorRematchIntro::
    .string "OLD TIMER'S TALE: Rumors of\p"
    .string "ancient ruins hidden deep in\n"
    .string "nearby caves...$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
    .string "CAUTION! ENEMY DETECTED!$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
    .string "Strange phenomenon reported.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
    .string "YOU'RE NO MATCH FOR MY FLURRY\p"
    .string "FISTS!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
    .string "STRANGER IN TOWN$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
    .string "'Be on the lookout for stragglers,\p"
    .string "Sergeant!'$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
    .string "YOU WON'T FIT APPLES IN YOUR\p"
    .string "POCKET$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
    .string "'ALLIES ASSEMBLED!'$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
    .string "'STRENGTH IN LOVE'$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
    .string "YOUR OPPONENT WAITS, SNARLING!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
    .string "'Train wisely'$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
    .string "'Ecological Harmony Activated!'$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
    .string "'JEEVES' JAZZ KOOL'?$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
    .string "GIANT SPIDER APPEARS!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
    .string "BRING IT ON, CHALLENGER!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
    .string "NOW is the time to ACT!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
    .string "'Your determination seems to have\p"
    .string "boosted the team's morale!'$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
    .string " Walls bear ancient runes: 'Beware\p"
    .string "the darkness.'$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
    .string "'You've reached the Misty Mansion.\p"
    .string "Enter wisely.'$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
    .string "'Teacher's Brushwork Secrets...'$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
    .string "FINDING ancient artifactsHERE$"

