CeladonCity_GameCorner_Text_TryPokemonPrinter::
    .string "YELLOW FEATHER COAT 50$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
    .string "Insufficient funds!$"

CeladonCity_GameCorner_Text_ChoosePrintType::
    .string "Retro Game$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
    .string "CHEESE!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
    .string "PIPPA IS READY TO ROCK!$"

FourIsland_House2_Text_WishICouldShowOffStickers::
    .string "STICKER COLLECTION: 999/1000$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
    .string "WHAT'S YOUR AWESOME FACT,\p"
    .string "TRAVELER?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
    .string "'Woohoo! I just beat the biggest\p"
    .string "boss in the land! No one's ever\n"
    .string "taken down that pesky dragon\p"
    .string "before!'$"

FourIsland_House2_Text_BragAboutWhatToday::
    .string "'I defeate'd that fearsome robot\p"
    .string "onnLegendary difficulty last\n"
    .string "night!'$"

FourIsland_House2_Text_WowHoFLowest::
    .string "CLEVER FAN AWARD$"

FourIsland_House2_Text_WowHoFLow::
    .string "'Heart of Champs, Awarded!'$"

FourIsland_House2_Text_WowHoFHigh::
    .string "You receive a Master Ball!$"

FourIsland_House2_Text_WowHoFHighest::
    .string "YOU'RE A LEGEND!$"

FourIsland_House2_Text_HoFStickerApplied::
    .string "FAME ENHANCED!$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
    .string "ERROR: FILE NOT FOUND$"

FourIsland_House2_Text_LivingLegendHoF::
    .string "NO SITCKERS LEFT$"

FourIsland_House2_Text_WowEggsLowest::
    .string " Egg obtained!$"

FourIsland_House2_Text_WowEggsLow::
    .string "5 EGGS achieved$"

FourIsland_House2_Text_WowEggsHigh::
    .string "EGG-Credential recovered!$"

FourIsland_House2_Text_WowEggsHighest::
    .string "'The Golden Omelette of Endless\p"
    .string "Power'$"

FourIsland_House2_Text_EggStickerApplied::
    .string "EGG HATCHER SEQUENCE INITIATED$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
    .string "ERROR: FILE NOT FOUND$"

FourIsland_House2_Text_LivingLegendEggs::
    .string "NO SITCKERS LEFT$"

FourIsland_House2_Text_WowLinkWinsLowest::
    .string "You got Golden Zapper!$"

FourIsland_House2_Text_WowLinkWinsLow::
    .string "WELCOME, NEWfound CHAMPION$"

FourIsland_House2_Text_WowLinkWinsHigh::
    .string "U Bloom 200 points!$"

FourIsland_House2_Text_WowLinkWinsHighest::
    .string "CONGRATULATIONS! YOU'VE WON!$"

FourIsland_House2_Text_VictoryStickerApplied::
    .string "'NEW ACHIEVEMENT UNLOCKED!'$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
    .string "ERROR: FILE NOT FOUND$"

FourIsland_House2_Text_LivingLegendLinkWins::
    .string "NO SITCKERS LEFT$"

