Text_FirstShouldRestoreMonsHealth::
    .string "You should heal at the Lab in\p"
    .string "Pallet Town.$"

Text_MonsHealedShouldBuyPotions::
    .string "Your POKeMON healed.$"

Text_MonsHealed::
    .string "Well done! Your POKeMON are fully\p"
    .string "healed!$"

Text_HadQuiteAnExperienceTakeRest::
    .string "'Exhausted'$"

Text_MomExplainHPGetPotions::
    .string "HP? What's that all about?$"

Text_WhitedOutLostMoney::
    .string " Pavel Pavel is out of usable\p"
    .string "POKeMON!p  Pavel panicked and lost\n"
    .string "Y3000...p ... ... ... ...p  Pavel\p"
    .string "whited out!$"

Text_WhitedOut::
    .string "Reeve's Pokemon Center is just\p"
    .string "ahead, nice and calm cybersecurity\n"
    .string "measures support.$"

