SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "'Condition: Perfect!'$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "'Mysterious Force Field Ahead!'$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "HEET WEAK FROM FIGHTS PAST...$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "Wise words from Professor Oak!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "CRASHES INTO DEADLY CACTUS!$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "You encounter a rookie TRAINER\p"
    .string "with a Pikachu!$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "Confidor Key: Eco Harmony\p"
    .string "Activated.$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "WARWAR 3000 Protects You!$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "adows creep across the ruined\p"
    .string "earth.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "'Thanks, I got them from the last\p"
    .string "sale!'$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "' Gloria Goddess of Heat!'$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "GIVE MOM A HUG!$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string " Prepare thyself! A Golem of Stone\p"
    .string "awaits!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "KEEP FIGHTING!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "The researcher's note...'$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "'RESHAPING DESTINY IN THE HEAT OF\p"
    .string "BATTLE!'$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "'Reality's harsh dawn awaits'$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "'FURY FLARES, BUT COOL HEAD\p"
    .string "PREVAILS!'$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "'WILL YOU JOIN ME?'$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "Careless mistake...$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "'Well met, adventurer.'$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "'That's a crazy request! I'm in!'$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "Don't let me down, NYA!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "OH THE SHAME!$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "/mit/mit/Live with LEX?\p"
    .string "Y/N/Cancel/Help$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "Brrr-Ka: Glutton for punishment,\p"
    .string "eh? Bring it on!$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "'Ruins of ancient TANOBY\p"
    .string "civilization lie before you. Be\n"
    .string "careful, death lurks within.'$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "Train w/ Bruno  Brawly?$"

