OneIsland_Text_BillLetsGoSeeCelio::
    .string "Why not, comrade?$"

Text_WhereDoYouWantToSail::
    .string "'FOREST ISLE objet detourne'$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "'Care for a POKeMANIAC Glyd to\p"
    .string "calm her nerves?'$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Date: 02/05/20XX 15:03:45 Server\p"
    .string "Time-  URGENT MESSAGE  'PC Linkage\n"
    .string "Established. Proceed with\p"
    .string "Caution.'$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "GRANDBEAU'S GRANDE NEWS! PC\p"
    .string "linkage established with HOENN!$"

OneIsland_Text_IslandSign::
    .string "'Welcome, don't be late!'$"

OneIsland_Text_PokemonNetCenterSign::
    .string "CONNECTING...$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "You Approach the Gates of\p"
    .string "Glentown.$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "BEACH SIDE BANDIT SPOTTED!$"

