LavenderTown_Text_DoYouBelieveInGhosts::
    .string "RUMOR HAS IT, MAVILLE FOREST IS\p"
    .string "HAUNTED BY restless spirits.$"

LavenderTown_Text_SoThereAreBelievers::
    .string "'Whispers spread darkness within'$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "'FEAR THE SHADOW'$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "RUINS OF THE TOWER AHEAD$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "'Beware the malevolent aura'$"

LavenderTown_Text_TownSign::
    .string "You've arrived in Lavender Town.$"

LavenderTown_Text_SilphScopeNotice::
    .string "'Activated! Invisible Plains now\p"
    .string "visible.'$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "Welcome Volunteer!$"

LavenderTown_Text_PokemonTowerSign::
    .string "'Greetings, Trainer! The mystical\p"
    .string "energies of POKeMON Tower stir.\n"
    .string "What secrets will you unravel?'$"

