PokemonMansion_Text_PressSecretSwitchJP::
    .string "Do ye dare activate the mysterious\p"
    .string "switch?$"

PokemonMansion_Text_LetsTryIt::
    .string "READY TO ROCK THE TRIGGER!$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "YOUR PATH IS FORgiven!$"

PokemonMansion_1F_Text_SimonIntro::
    .string "WELCOME TO CYGNUSryan's MAZE OF\p"
    .string "WONDERS$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "The Temple of the Ancients Lies\p"
    .string "Ahead$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "REENACTING INTERIOR ROOM...$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "'Welcome to the Abandoned Temple\p"
    .string "of the Ancients'$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "OKAY, CHASER! YOU'VE MADE IT OUT\p"
    .string "ALIVE!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "JUMP TO SAVEDistance: 5 Feet$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "New family addition found!$"

