Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Gathered ten POKeMON yet?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "WOOHOO!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "'Legacy Teleport Received!'$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "Heard rumors it reveals hidden\p"
    .string "paths!$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "FLASH acquired!$"

