Route17_Text_RaulIntro::
    .string " Beating the streets will take\p"
    .string "time.$"

Route17_Text_RaulDefeat::
    .string "HEALTH LOW$"

Route17_Text_RaulPostBattle::
    .string "'Picked up some scrap metal. Worth\p"
    .string "500 coins'$"

Route17_Text_IsaiahIntro::
    .string "'Hey, trainer! This body's a\p"
    .string "wrestlin' legend in the makin'!'$"

Route17_Text_IsaiahDefeat::
    .string "'WELCOME TO ADVENTURE ISLAND!'$"

Route17_Text_IsaiahPostBattle::
    .string "'Watch out, Grug!'$"

Route17_Text_VirgilIntro::
    .string "Watch yer back, stranger. Rumors\p"
    .string "of treacherous terrain ahead!$"

Route17_Text_VirgilDefeat::
    .string "ENGINE FAILURE!$"

Route17_Text_VirgilPostBattle::
    .string "Buckle up: Maverick Mountain\p"
    .string "AHEAD!$"

Route17_Text_BillyIntro::
    .string "'VROOOOM! Fast Riders Forever!!!'$"

Route17_Text_BillyDefeat::
    .string "'ENEMY DOWN!'$"

Route17_Text_BillyPostBattle::
    .string "Embark on Quest for Golden\p"
    .string "Chalice!$"

Route17_Text_NikolasIntro::
    .string "BZZT! TO TYPING!$"

Route17_Text_NikolasDefeat::
    .string "'STUCK! ENEMY ENCLOSURE BLOCKING\p"
    .string "PROGRESS...'$"

Route17_Text_NikolasPostBattle::
    .string "You feel a surge of electricity!$"

Route17_Text_ZeekIntro::
    .string "'Evol-shift? Check level, await\p"
    .string "key item or trade.'$"

Route17_Text_ZeekDefeat::
    .string "'BETRAYAL! THE TRUST HAS BEEN\p"
    .string "SHATTERED!'$"

Route17_Text_ZeekPostBattle::
    .string "'PURIFY YOUR POKE BALLS YET?'$"

Route17_Text_JamalIntro::
    .string "GET READY TO SWEAT!$"

Route17_Text_JamalDefeat::
    .string "YOU FEEL STRONG$"

Route17_Text_JamalPostBattle::
    .string "You fell off a ledge.$"

Route17_Text_CoreyIntro::
    .string "'REBELBASE UNDER ATTACK! FLEE FOR\p"
    .string "YOUR LIFE!'$"

Route17_Text_CoreyDefeat::
    .string "ATTENTION: PIRATE ANCHORED HOT!$"

Route17_Text_CoreyPostBattle::
    .string "'Gorthok, the Unyielding, awaits\p"
    .string "your challenge.'$"

Route17_Text_JaxonIntro::
    .string "Fast, Agile, and Responsive!$"

Route17_Text_JaxonDefeat::
    .string "'Target acquired!'$"

Route17_Text_JaxonPostBattle::
    .string "'Careful, mate ye gotta correct\p"
    .string "yer course!'$"

Route17_Text_WilliamIntro::
    .string "'You ain't takin' me down without\p"
    .string "a fight!'$"

Route17_Text_WilliamDefeat::
    .string "SURE, SORCERESS. WHAT'S YOUR WILL?$"

Route17_Text_WilliamPostBattle::
    .string "'Sleep Deprivation: -25 HP'$"

Route17_Text_WatchOutForDiscardedItems::
    .string "'Be cautious of stray trash'$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "'Your team's distinct\p"
    .string "personalities will make all the\n"
    .string "difference on your quest!'$"

Route17_Text_PressBToStayInPlace::
    .string "STAY PUT, B BUTTON!$"

Route17_Text_RouteSign::
    .string "'Next stop: Fuchsia City!'$"

Route17_Text_DontThrowGameThrowBalls::
    .string "'Feel the POKE-emon Power!'$"

Route17_Text_CyclingRoadSign::
    .string "'WHEW! FLAT ROAD AHEAD!'$"

