Route5_PokemonDayCare_Text_WantMeToRaiseMon::
    .string "Yes/No$"

Route5_PokemonDayCare_Text_ComeAgain::
    .string "You can't go back now!$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
    .string "'Consider Power Wing's swift speed\p"
    .string "Thunder Fist's electrifying\n"
    .string "attacks.'$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
    .string "'Open Door Ahead!'$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
    .string "You've got a curious one on your\p"
    .string "hands, eh?$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
    .string "'See ya, partner!'$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
    .string "'You're so impatient, aren't you?'$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
    .string "'Hey, PAL! You gotta pay me\p"
    .string "STRVAR2 yen for thatledigi!'$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
    .string "Pikachu  HP: 65$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
    .string "Bella got 500 gold back$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
    .string "YOU SHOULD BRING MORE!$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
    .string "MY PIKACHU$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
    .string "Your HP has grown a lot. Yes,\p"
    .string "quite a lot, I'd say. Let me\n"
    .string "see... By level, it's grown by 50.\p"
    .string "Aren't I great?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
    .string "'NO SPACE'$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
    .string "Not enough clams!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "ARE YOU WATCHING?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "'Bad boy with hidden talent...\p"
    .string "Eve...'$"

