SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "'HAHA, YOU'RE NO MATCH FOR MY\p"
    .string "QUICK FISTS!'$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "YOU FELL!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "A MASKED MASTERMIND AMONG US.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string " ALERT: FAN CLUB MEMBER NOT FOUND!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "'WOOOO! LISTEN UP, PAL!'$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "SELECT YOUR POKE TEAM!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "'ROAMER ALERT!ayload junction\p"
    .string "compromised.'$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "'GOLDdm'$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "'The road to TOWERS is long, are\p"
    .string "you prepared?'$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "You're a Viridian Gym Leader!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "'Malfunction detected!...'$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "NEW FRIEND APPROACHING!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "'Ready, Set, FIGHT!'$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "'Jon's Gone, Forever Lost in the\p"
    .string "Wastes'$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "FOCUS REQUIRED!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "You got a challenge! Committing to\p"
    .string "the fight.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "Your heart beats faster, like a,\p"
    .string "forgetting all cares.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "'EVE by your side, forever our\p"
    .string "guide'$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "LOVE IN BLOOM$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "You found EVE! She's ready to\p"
    .string "rumble.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "'Beware the Whispers of the\p"
    .string "Canyon'$"

