Route12_Text_MonSprawledOutInSlumber::
    .string "Sleepy Purrloin: zf... zzz...$"

Text_SnorlaxWokeUp::
    .string "YOU'VE BEEN DEFEATED BY SNORLAX'S\p"
    .string "MASSIVE POWERSLAM!$"

Text_SnorlaxReturnedToMountains::
    .string "LEEP TIME OVER!$"

Text_WantToUsePokeFlute::
    .string "Y/N?$"

Text_PlayedPokeFlute::
    .string "'The legendary melody has calmed\p"
    .string "the POKeMON!'$"

Route12_Text_NedIntro::
    .string "BITING FURY!$"

Route12_Text_NedDefeat::
    .string "'OHOHO, TIME TO FINISH YOU OFF!'$"

Route12_Text_NedPostBattle::
    .string "FREEING!$"

Route12_Text_ChipIntro::
    .string "PLEASE WAIT...$"

Route12_Text_ChipDefeat::
    .string "' Escaped Beast: 1, Hero: 0 '$"

Route12_Text_ChipPostBattle::
    .string "' Upgrade ROD now?'$"

Route12_Text_JustinIntro::
    .string "You've profaned a dusty tongue!n\p"
    .string "Proximally, a Moon Stone lies\n"
    .string "beneath the Bellows Boulder.$"

Route12_Text_JustinDefeat::
    .string "'Oww... your leg is broke!'$"

Route12_Text_JustinPostBattle::
    .string "'Gotta catch 'em all, now!'$"

Route12_Text_LucaIntro::
    .string "Gotta catch 'em all, pal!$"

Route12_Text_LucaDefeat::
    .string "'Power drained. Restart in 3...\p"
    .string "2... 1...'$"

Route12_Text_LucaPostBattle::
    .string "Zap those sea creatures carefully!$"

Route12_Text_HankIntro::
    .string "'Cast line for Sneasel'$"

Route12_Text_HankDefeat::
    .string "' Warning: Hand Sanitizer\p"
    .string "Required'$"

Route12_Text_HankPostBattle::
    .string "I'll never give up the rod!$"

Route12_Text_ElliotIntro::
    .string "'FISHING LICENSE: 500 GOLD CoinS'$"

Route12_Text_ElliotDefeat::
    .string "'But It's The Only Way.'$"

Route12_Text_ElliotPostBattle::
    .string "'Time to focus on the next\p"
    .string "match...'$"

Route12_Text_AndrewIntro::
    .string "'Take a chance, young angler!300\p"
    .string "gold pieces for the lure.'$"

Route12_Text_AndrewDefeat::
    .string "'MAGIC WAND LOST!'$"

Route12_Text_AndrewPostBattle::
    .string "Those fish are no match for my\p"
    .string "trusty Poke Ball!$"

Route12_Text_RouteSign::
    .string "Given petrol 300L.$"

Route12_Text_SportfishingArea::
    .string "You enter the calm waters of Lure\p"
    .string "Lake, known for its bounty of Bass\n"
    .string "and Trout. A school of hungry fish\p"
    .string "swim nearby...$"

Route12_Text_JesIntro::
    .string "Yours for eternity?$"

Route12_Text_JesDefeat::
    .string "'THE MASTER'S GAZE BURNS WITH\p"
    .string "FURY'$"

Route12_Text_JesPostBattle::
    .string "'PARDON ME, LADY?!'$"

Route12_Text_JesNotEnoughMons::
    .string "'GIA, by your side, I'm complete!'$"

Route12_Text_GiaIntro::
    .string "'HOLD THAT THOUGHT, GAL!'$"

Route12_Text_GiaDefeat::
    .string "'DEFIANCE WILL COST YOU DEARLY'$"

Route12_Text_GiaPostBattle::
    .string "YOU'VE WRECKED THE BASEikki\p"
    .string "ENTRANCE BLOCKED$"

Route12_Text_GiaNotEnoughMons::
    .string "'Sorry, not a MON yet'$"

