SaffronCity_Gym_Text_SabrinaIntro::
    .string "'The fate of your journey... will\p"
    .string "soon be revealed!'$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "You earned?$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Utilize your hidden psychic\p"
    .string "energies!$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "'Congratulations! Your MARSHBADGE\p"
    .string "is yours!'$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "TM04: Surf Learned!$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "EXECUTING... CALM MIND$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "'Cannot add more!'$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "'Rightly so, you've proven\p"
    .string "yourself.'$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "resume scan complete. contact\p"
    .string "lost.$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "Unleash thy inner strength!$"

SaffronCity_Gym_Text_JohanIntro::
    .string "'YOU DARE NOT LOOK!'$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "Suddenly, a mysterious energy\p"
    .string "vortex engulfs the city!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "GASTLY: Ghost/Poison-type.\p"
    .string "firepower: 65$"

SaffronCity_Gym_Text_StacyIntro::
    .string "YOU BECOME...RIKUO!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "'...the ancient Scroll of Doom was\p"
    .string "hidden here all along!'$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "DetailView: PSI deliberately\p"
    .string "showcases esteem$"

SaffronCity_Gym_Text_TyronIntro::
    .string "'A bond of trust with your\p"
    .string "partner!'$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "WHAT IN THE N Lumpur?!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "'TERROR of the DOJO now reigns!'$"

SaffronCity_Gym_Text_TashaIntro::
    .string "'Choose wisely, Trainer!'$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "'Game Over. Better Luck Next Time,\p"
    .string "Adventurer!'$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Welcome to the ancient ruins.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "WARNING: SABRINA GUARDING ENTRANCE$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "'YOU LOST A LIFE!'$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "'SAFFRON CITY, 1st POKE stop!'$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "'Meet Sabrina now?'$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "'SHRINCK'S STRONGHOLD 10,000 XP\p"
    .string "AWAITS'$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "'MIND CONTROL ACQUIRED!'$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "FIGHTING POKes WEAK TO PSYCHIC?\p"
    .string "CtlrN$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "'WEIRD!', exclaimed Goro$"

SaffronCity_Gym_Text_GymStatue::
    .string "RIVAL SAYS: 'TIME TO SETTLE OLD\p"
    .string "SCORE, SAFIIIIIRN!'$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "You've arrived at Saffron Pokemon\p"
    .string "Gym! Its leader, Sabrina, awaits!$"

