PokemonTower_6F_Text_AngelicaIntro::
    .string "Find the mysterious scroll in the\p"
    .string "dark forest.$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "'Ugh, what's eatin' away at my\p"
    .string "gut?'$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "'HP: 12/50'$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Grrr... ENEMY APPEARS!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "'Mysterious Treasure Chest\p"
    .string "Opened!'$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "'Evil energy dissipates. Whispers\p"
    .string "of ancient curse echo through the\n"
    .string "void.'$"

PokemonTower_6F_Text_JenniferIntro::
    .string "MEME ALERT!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string " Warning: incoming meteor shower!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "'FORBIDDEN CAVE AHEAD! BEWARE THE\p"
    .string "SPIKES'$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "'THEY APPROACH!'$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "'Unquiet Bones... Dance!'$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "REST IN PEACE$"

