SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "'Meet yer match, matey!'$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "'WE MADE IT!'$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "SET SAIL FOR NEW HORIZONS!$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "BRING IT ON, LANDLUBBER!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "YOU DROWN IN THE DEEP$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "OVER HERE!$"

