Text_RockSlideTeach::
    .string "slides sound CAREFUL, TRAVELER!$"

Text_RockSlideDeclined::
    .string "'RUN FOR YOUR LIFE!'$"

Text_RockSlideWhichMon::
    .string "Try GEODUDE.$"

Text_RockSlideTaught::
    .string "BREATHE CAREFULLY$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string " WATCH OUT FOR ROCKY CURRENTS!$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "Beware the rapids ahead!$"

