CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "'You're the here to save the world\p"
    .string "from the evil Zorvath!'$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Congratulations are in order...\p"
    .string "Now, let's proceed with caution,\n"
    .string "you're not exactly... stable, are\p"
    .string "you?$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "You: blushes OH MY, YOU LIKE ME\p"
    .string "TOO?!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "GET BACK TO CATCHIN'!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "POKeDex Complete!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "BEEP BOOP: SYSTEM WARNING:\p"
    .string "UNAUTHORISED ACCESS ATTEMPT.\n"
    .string "TERMINATING SESSION.$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Oops, 'Sorry, Dave, I'm\p"
    .string "reading...'  Note: This is a\n"
    .string "reference to a famous phrase from\p"
    .string "the movie '2001: A Space\n"
    .string "Odyssey'akeup$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "TRY FAIRY TALE FADER?$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "System Check Complete:\p"
    .string "Initializing Debug Menu.$"

