SilphCo_7F_Text_HaveMonForSavingUs::
    .string "'Take Raticate, yours now!'$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "New Team Member!$"

SilphCo_7F_Text_ExplainLapras::
    .string "You received LAPRAS!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "Investigating boardroom\p"
    .string "activities...$"

SilphCo_7F_Text_OhNo::
    .string "YOU'RE OUT OF LUCK, PAL!$"

SilphCo_7F_Text_SavedAtLast::
    .string "WOOHOO! TRUST FUND INCREASED!$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "You've got ROCKET SCIENTIST Jessie\p"
    .string "on your tail!$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Mission Abort: MASTER BALL\p"
    .string "Redirected$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "Don't let it happen!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "HAH! YOU'RE A REAL HERO?!$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "'No way out here'$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "' Maven's mystery awaits thee!'$"

SilphCo_7F_Text_Grunt3Intro::
    .string "'THE MOZZY MONSTER AWAITS!'$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "SHUTTERBUG amour hallucinates in\p"
    .string "the darkness...$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "Seek out the rumors in Hammer's\p"
    .string "Pub.$"

SilphCo_7F_Text_JoshuaIntro::
    .string "'WHO ARE YOU TO QUESTION MY\p"
    .string "IDENTITY, POOR GUY?'$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "'Congratulations, you've won!'$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "AGED LIKE A GOOD WINE, EH?$"

SilphCo_7F_Text_Grunt1Intro::
    .string "'Meet me in Joe's Garage, bro!'$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "'Flee while you still can... Erden\p"
    .string "Castle gates closing!'$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "REVENGE SEEMS NIGH$"

SilphCo_7F_Text_Grunt2Intro::
    .string "'You shouldn't be here!'$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "GAME OVER!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "'Strange noises emanating from the\p"
    .string "experimental wing...'$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "'Too busy savin' the world from\p"
    .string "your inferior reflexes, RIVAL!'$"

SilphCo_7F_Text_RivalIntro::
    .string "You want revenge for earlier, eh?$"

SilphCo_7F_Text_RivalDefeat::
    .string "ENEMY BOSS: ROCKET MAN APPEARS!$"

SilphCo_7F_Text_RivalVictory::
    .string "'You're no match for me, fool!'$"

SilphCo_7F_Text_RivalPostBattle::
    .string "'Well, back to grindin' for that\p"
    .string "LEAGUE!'$"

SilphCo_7F_Text_FloorSign::
    .string "DOOR UNLOCKS$"

