SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "'THE TIME HAS COME! FIGHT IT!'$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "HERACROSS: 5.5 METERS$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "Whoa, GIGANTASMITE!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "A behemoth HERACROSS layoffs in\p"
    .string "the distance!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "'Inches away from fatal mistake!'$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "'7 inches. The HERACROSS before\p"
    .string "was bigger. It was 9 inches, the\n"
    .string "biggest HERACROSS you've brought\p"
    .string "me.'$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "You're not in Kong Country no\p"
    .string "more!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "Not enough room in tumbling!$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "'47.5 inches!'$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "CRIME LOG$"

