ViridianCity_Gym_Text_GiovanniIntro::
    .string "You've ruined my plans...$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "You have won!$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "YOU'VE BEEN DEFEATED BY MY HAND!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "You received EARTHBadge!$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "'Thunderbolt learned!'$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "YOU'VE GOT IT!$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "MONTHS OLD SUPPLIES LEFT$"

ViridianCity_Gym_Text_YujiIntro::
    .string "You've got 3 minutes to escape the\p"
    .string "volcano!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "'Empty Tank! Repair Station\p"
    .string "Ahead.'$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "'Stock up on Poke Balls and\p"
    .string "Electro Peps!'$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "'ENRAGE MODE ACTIVATED!'$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "'Orc Army Spotted Ahead!'$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "'PUNY HERO, BRING ARTIFACT OF\p"
    .string "WISDOM'$"

ViridianCity_Gym_Text_JasonIntro::
    .string "'WONDERFUL RHYTHM DETECTED!'$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "'Angel's melody echoes through the\p"
    .string "forest'$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "IT'S WHISPER OF VIRGIN VALLEY!$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "'KIAI!'$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "'Strange Incense FumesSWG in\p"
    .string "Sight!'$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "...you'd be in a world of trouble!$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "'You're a natural!'$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "'HOLD TIGHT! GRAVELLY CLIMB'$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "'FALtering Tactics!'$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "PREPARE TO FACE YOUR DEMISE!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "You found the ancient scroll!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "'A TRAINER RISES!'$"

ViridianCity_Gym_Text_ColeIntro::
    .string "'Fearless Trainer Approaches'$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "'Owwww...'$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "NOT IT AGAIN...!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "'LEADER HAS ARRIVED! TRAINING\p"
    .string "RESUMED!'$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "'Better Luck Next Time,\p"
    .string "Adventurer!'$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "DEFEAT LARRY AND CLAIM YOUR BADGE!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "You've reached Viridian! Meet its\p"
    .string "mysterious Leader...$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "'Da Peso! Worldol'zno take the\p"
    .string "stage!'$"

ViridianCity_Gym_Text_GymStatue::
    .string "LEADER: CAMI$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "RIVAL CHALLENGES LEADER GIOVANNI!$"

