RocketHideout_B1F_Text_Grunt1Intro::
    .string "Stranded Survivor of the Last\p"
    .string "Upturned Earthly Realm. Washed\n"
    .string "Ashore by Turbulent Storms of\p"
    .string "Cryptic Energies.$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "'YOUR INJURIES ARE SERIOUS. SEEK\p"
    .string "MEDICAL ATTENTION.'$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "'BRING IT ON, CHUMP!'$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "Take cover, we're surrounded!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "EXPLOSION INVOLVED!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "YOU'RE UNDER ARREST, SCUM!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "'INtruder DETECTED! FLEE FOR\p"
    .string "COVERR!'$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "YOUR TIME IS RUNNING OUT!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "'IN CASTLE TOWN, TRY OLD MAN'r$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "'Seeking ancient artifacts,\p"
    .string "Luminous ruins beckon you.'$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "ERROR: POWER FAILURE DETECTED.$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "' templateUrl: loading... sorry,\p"
    .string "BROKE AGAIN.'$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "'Exit Village?'$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "'LOST IN LABYRINTHINE RUINS...'$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "-dire creatures emerge!$"

