SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "'TreasuresSpawnedFromThe\p"
    .string "DepthsRuinsLurkBeneath'$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "'Pikachu's DEFLEWN to 12! Check\p"
    .string "its item...'$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .string "NOT GONNA WASTE TIME HERE!$"

