RocketHideout_B4F_Text_GiovanniIntro::
    .string "'You sank MY POKEMON SHIP!'$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "'FEDERAL BUILDING IN RUINS'$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "You've got SCHOOL SPIRIT!$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "IT'S ABOUT TIME WE FLEW INTO\p"
    .string "ACTION AGAINST YOU!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "'Dirty flames engulf your boots.\p"
    .string "Do you drink from nearby pond?'$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "'BEWARE: Enemy Lair Ahead!'$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "'Ahahahaha, The darkness reveals\p"
    .string "itself.'$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "'Explore the mystical ruins!'$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "'Don't apologize, comrade! Next\p"
    .string "time we strike back!'$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Security Guard found key in\p"
    .string "Evidence Locker.$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Explosion Goes BOOM!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "'KEY LOST! TRYING OTHER\p"
    .string "SERVICES...'$"

