SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "'INACCESSIBLE ENTRANCE? TRY\p"
    .string "SHOOTING WALL TO UNLOCK PATH.'$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "'The Gardens of Eternal Rest'$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "' obsolete lock may be jammed'$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "'Door remains locked'$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Strange symbols read: 'EYES WATCH'$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "'WARNING: DOOR OPEN'$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "' Legend speaks of hidden\p"
    .string "doors...'$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Wanted for: Bank Robbery$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Ancient tome lies nearby.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "STRANGERS IN THE DARK$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "'GET READY TO FIGHT... AGAIN!'$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Enter SEVII ISLANDS Ruins? Y/N$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "You stumble upon a stone with\p"
    .string "ancient runes...$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "'Flickering Door: Warning.\p"
    .string "Treasure hidden behind.'$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "'Cursed door refuses to budge.'$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "'??????? CROSSES PATHS WITH YOU!'$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "'Not again! The Agony!'$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Craggy peaks await!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "SSHSSH! Mystery Ruins Ahead$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "'Spoken by Sultry Siren'$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "EGAEGAjr INITIATE INSCRIPTION\p"
    .string "ANALYSIS.$"

