SafariZone_North_Text_RestHouse::
    .string "'Welcome weary traveler! Rest\p"
    .string "well, but beware the whispers in\n"
    .string "the night...'$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "Entrance hidden behind waterfall\p"
    .string "awaits!$"

SafariZone_North_Text_Area2::
    .string "'CRUMBLING BRIDGE AHEAD!x27;$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "HEADS UP, TRAINER!$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "Discover the SECRET HOUSE!$"

