VictoryRoad_2F_Text_DawsonIntro::
    .string "Beware: ROCKY ROAD ahead!$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "NO WAY!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "OH SNAP! NOT TODAY!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Climb the peaks of VICTORY ROAD!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Alien Scout spotted!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Pushing against door...$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "BEGONE, NOVICE!$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "YOU'VE BEEN CAUGHT!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "You see a set of old, rusted tire\p"
    .string "tracks leading off into the desert\n"
    .string "wasteland.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "YOU DARE TO CHALLENGE ME?$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "'YOU HAVE BEEN DEFEATED BY THE\p"
    .string "EVIL WARLOCK!'$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "YOU'RE NEXT FOR THE GYM LEADER!$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "'CAUTION ADVANCE AT YOUR OWN RISK'$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "'YOU'VE EARNED 100 EXPERIENCE\p"
    .string "POINTS!'$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "BUT NOT YOU, CHOOSE YOUR NEXT MOVE\p"
    .string "CAREFULLY!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "'WE'RE IN TROUBLE NOW!'$"

