SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "'Careful, sounds like FUCHSIA's\p"
    .string "GYM LEADER's on patrol!'$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "USE ROCKS WITH CARE!$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "You found a SCHOOL of SHINY\p"
    .string "BEEDRILL!$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "'Better luck on the next trail?'$"

