SSAnne_Deck_Text_ShipDepartingSoon::
    .string "ABANDON SHIP NOW!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "DECKS CLEANED!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "'Fresh air... not so fresh\p"
    .string "anymore...'$"

SSAnne_Deck_Text_EdmondIntro::
    .string "JIGGING IN PLACE$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "'Your stats are impressive,\p"
    .string "adventurer. Continue on?'$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "151 RUMORED$"

SSAnne_Deck_Text_TrevorIntro::
    .string "'Navigator's Log: Estimated\p"
    .string "12-hour voyage ahead. Prepare for\n"
    .string "rough seas!'$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "'Whoops! Lost that treasure...'$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "'Rumors of a rare POKeMON sighting\p"
    .string "in the nearby woods!'$"

