FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "Don't mess with Professor Oak's\p"
    .string "research!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Hmph! Mind yer own biznetail!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "'Take that scoundrel!'$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "'SEEMS LIKE YOU'RE PUSHING\p"
    .string "BOUNDARIES, TRAINER...'$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "'UH-OH! ALIEN INVASION!'$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "'Resist, or reveal the hideout's\p"
    .string "location!'$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "-index-index! whispers Tell me...$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "ceeceecee!$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "'Mind the sharp rocks on Five\p"
    .string "Island, trainer...'$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "'Seek shelter, stranger... NOW!'$"

