SSAnne_2F_Room2_Text_BrooksIntro::
    .string "'A kindred spirit!'$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "WOOHOO! You succeeded in\p"
    .string "rekindling your fervor!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "'Get Revenge, Jackson!'$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "GOLDEN FISHscaled Brilliance!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "'Need Credits? Find More in the\p"
    .string "Cash Register!'$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "'Lost my ticket...'$"

