FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "'The memories mock me, like\p"
    .string "whispers in the wind...'$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "AND NOW, IT IS TIME FOR ME TO\p"
    .string "LEAVEserializer$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "'Courage is my wake-up call!'$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "'DETECT RARE 'MON COLLECTION!'$"

