Route4_Text_TrippedOverGeodude::
    .string "You're badly hurt! What now?$"

Route4_Text_CrissyIntro::
    .string "FOUND: MUSHROOM POKEMON ENCLAVE\p"
    .string "FURTHER UP TRAIL$"

Route4_Text_CrissyDefeat::
    .string "'ESCAPED.too!'$"

Route4_Text_CrissyPostBattle::
    .string "'You've collected all the\p"
    .string "mushrooms!'$"

Route4_Text_MtMoonEntrance::
    .string "CRASH!$"

Route4_Text_RouteSign::
    .string "CERULEAN CITY AHEAD!$"

Text_MegaPunchTeach::
    .string "LEARN MEGA PUNCH?$"

Text_MegaPunchDeclined::
    .string "MEGA PUNCH: 100DMA$"

Text_MegaPunchWhichMon::
    .string "Pikachu, Charmander, Squirtle.$"

Text_MegaPunchTaught::
    .string "Use the hole to escape, it seems!$"

Text_MegaKickTeach::
    .string "Learn MEGA KICK$"

Text_MegaKickDeclined::
    .string "'HA!'$"

Text_MegaKickWhichMon::
    .string "Charmander knows Ember!$"

Text_MegaKickTaught::
    .string "'Away, mortal, or suffer their\p"
    .string "rage!'$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Wow!  You think you have what it\p"
    .string "takes?$"

