VermilionCity_Text_GrimerMultipliesInSludge::
    .string "'Mulch To avoid contamination!'$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "CAPTAIN! YES, THAT'S THE S.S. ANNE\p"
    .string "I SEE!$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "DREAMS DASHED ON SHATTERED WATERS$"

VermilionCity_Text_BuildingOnThisLand::
    .string "'Laying foundation, strong and\p"
    .string "deep, groundwork for greatness,\n"
    .string "indeed.'$"

VermilionCity_Text_Machop::
    .string "'FURY UNLEASHED!'$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "YOU FEEL THE GROUND SHAKE!$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "'Welcome Aboard S.S. ANNE!'$"

VermilionCity_Text_CitySign::
    .string ".scrollView has stopped.$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "Watch out! Route 12 blocked by\p"
    .string "sleeping Pokemon. Take detour\n"
    .string "through Rock Tunnel to Laverdead\p"
    .string "Town!$"

VermilionCity_Text_PokemonFanClubSign::
    .string "JOIN THE FUN TODAY!$"

VermilionCity_Text_GymSign::
    .string "Prepare for Shocking Showdown!$"

VermilionCity_Text_VermilionHarbor::
    .string "PORT AUTHORIZATION REQUIRED$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Boarded the ship. Door creaks\p"
    .string "open...$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Aye, got it right here, mate!$"

VermilionCity_Text_FlashedSSTicket::
    .string "Welcome aboard!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "You need S.S. Ticket.$"

VermilionCity_Text_TheShipSetSail::
    .string "' Charting course for Treasure\p"
    .string "Isles... '$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "YES$"

VermilionCity_Text_Seagallop7Departing::
    .string "'Departing for Aquaria-4.'$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "What a bargain!$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "'LANDING NOW'$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "'Welcome to BIRTH ISLAND'$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Aye,captain! Let's set sail!$"

VermilionCity_Text_Seagallop10Departing::
    .string "Doc onboard, confirmingn luggage\p"
    .string "and cargo in order.$"

VermilionCity_Text_Seagallop12Departing::
    .string "FERRY TICKET IN HAND!$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "'Routing for AIDE on ROUTE 2?'$"

