@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "What's your destination?$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "Floor 10 awaits.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "Brace yourself, adventurer!$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "You look nervous.$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "YOU'RE OFF LIKE A SHOT!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "WELCOME BACK TO THE TOWN$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "MISSION FAILED. TRY AGAIN?$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "YOUR MOVE, CHAMPION!$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "'Jump over trainers, then try\p"
    .string "door!'$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "'Fates entwined, like the winds\p"
    .string "that caress...'$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "Ciaran's Letter$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string " RECORD ACHIEVED!$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "'You're almost too late...'$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "YOU ARE COUNTED ON BY THE KING!\p"
    .string "Note: I've maintained the style\n"
    .string "and brevity of classic retro game\p"
    .string "text while still conveying the\n"
    .string "message$"

TrainerTower_Text_XMinYZSec::
    .string "2 min. 14.nine sec.$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "YOU FOUND THE ANCIENT Scroll!$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "NOT ENOUGH POKEMON!$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "TIME ATTACK. GET TO THE OWNER ON\p"
    .string "THE ROOF AS FAST AS YOU CAN!$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "Congratulations! You won!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "A CHALLENGER APPROACHES!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "'CLIMB WITH CAUTION!'$"

