PokemonLeague_LoreleisRoom_Text_Intro::
    .string "'Pokemon, use Gust!'$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "'You think you can beat me? We'll\p"
    .string "see...'$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "'The Dark Lord's done gone and\p"
    .string "messed up reality!'$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "'Bigger challenges await in\p"
    .string "Viridian City.'$"

