CeladonCity_Gym_Text_ErikaIntro::
    .string "GREETINGS, TRAINER! CHALLENGE MY\p"
    .string "GRASS-TYPE POKEMON, WILL YOU?$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "RAINBOWBADGE GRANTED!$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "Artistic Sense: 50$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "Got the RAINBOWBADGE! LV 50\p"
    .string "POKeMON obey.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "YOU NOW HAVE TEACH POINT!$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "'A Wise Choice!'$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "MAKE SOME SPACE$"

CeladonCity_Gym_Text_KayIntro::
    .string "'BATTLE READY, HOORAY! GYM ZONE\p"
    .string "AHEAD!'$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Ouch! You've been warned!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "'YOU DARE CHALLENGE MY FURY?'$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "You've been hanging around too\p"
    .string "much.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "'Your cosmetics are RUINED!'$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "Pokemon's hidden strength lies in\p"
    .string "its GRASS-Covered Heart!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "YOU SNEAKY THING!$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "YOU'RE RUNNING OUT OF AIR!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "BETRAYAL?$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "'GRASS POKeMON gazing at you!'$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Explosion Goes BOOM!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "'Ah, sweet symbiosis!'$"

CeladonCity_Gym_Text_LisaIntro::
    .string "NO WAY!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string " Mortal, what brings you to these\p"
    .string "cursed woods?$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "'Shh, she's studying the ancient\p"
    .string "maps.'$"

CeladonCity_Gym_Text_LoriIntro::
    .string "'Hey, I'm Brock! Pokemon stud!'$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "BEBE HAS AWAKENED!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "'Be on your best Behavior, hero!'$"

CeladonCity_Gym_Text_MaryIntro::
    .string "'Get ready for some serious\p"
    .string "battling!'$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "YOU WIN!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "'You can't catch me yet!'$"

CeladonCity_Gym_Text_GymStatue::
    .string "Battling Erika!$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "Challenge Accepted!$"

