CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "'Elixir nearby'$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "'PINA COLADA: Refreshing vitality\p"
    .string "'$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Got a fishy taste?$"

Text_ReceivedItemFromLittleGirl::
    .string "You received a flower$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "/move: LIGHT SCREEN! POWER DOWN!$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "EXTRA LIFE!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "SAFEGUARD prevents status\p"
    .string "setMessage!$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Lemonade 1 Health$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "REFLECT READY!$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "PUSH IT FURTHER$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "You veer off from the oasis,\p"
    .string "continuing north into the\n"
    .string "scorching desert.$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "'Ha! Sis, you calln'$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Water Well-cache 300ft$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string " Vand ?$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "Energy Drink: 50 coins Healing\p"
    .string "Serum: 100 coins Health Kit: 200\n"
    .string "coins$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "NOT ENOUGH COINS! TRY AGAIN?$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "A can of SPARK-Cola popped out!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "'Inventory Full. Delete Some\p"
    .string "Items?'$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "'Oh no, you're parched!'$"

