SSAnne_1F_Room2_Text_TylerIntro::
    .string "WANT TO BEHOLD THE MIGHT OF\p"
    .string "PIKACHU?!$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Congratulations! Well done\p"
    .string "adventurer!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string " Buddy up?$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "'A WORLD COLLECTION: 142/151\p"
    .string "POKeMON GATHERED!'$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "'Those rare pearls are now Yours!'$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "'Heal Them Now? Y/N'$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "'Setting sail for exotic shores.\p"
    .string "Keep watch for sea monsters!'$"

