FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "I do!$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Let's hook some fins and swap\p"
    .string "stories!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "BOON TO THY FISHING WAYS!$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "Grab old trusty rod, you'll reel\p"
    .string "in a MAGIKARP$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "'Sorry, no choice here'$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Better than ever!$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "NO ROOM!$"

