IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "-Type selection: Trainers, choose\p"
    .string "your!' Let me know what type of\n"
    .string "response you need next!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "CHALLENGE APPROACHING!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string ",path you must taken to the next\p"
    .string "town to challengen another\n"
    .string "TRAINING AREA.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "YOU BETTER WATCH YOUR STEP,\p"
    .string "TRAINER!$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "The rumors are true.$"

