Text_MetronomeTeach::
    .string "Learn Metronome Poke Co.$"

Text_MetronomeDeclined::
    .string "'Get Ready for the Ultimate Skiing\p"
    .string "Adventure!'$"

Text_MetronomeWhichMon::
    .string "TEACH ElectroPkmn: Zap!$"

Text_MetronomeTaught::
    .string "'METRONOME: Brain-shaped Reset?'$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Potions and pills, I'll buy 'em\p"
    .string "from ya!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "YOU'VE BEEN DEFEATED!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "CAUTION! TIME LOOP AHEAD p Bring\p"
    .string "joy to nearby areas n Exploring\n"
    .string "this route looks promising!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Buggin' emerald caves$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "You received the Antidote.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "PLAYER'S POKEDEX FULL! TOO MANY\p"
    .string "POKES, NOT ENOUGH SPACE!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Fossil of ARCEUS, a Pokemon that\p"
    .string "is already extinct!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "A dusty old manuscript crumbles to\p"
    .string "dust.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "You stroll back to town.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "'WATCH YOUR BACK, TRY-HARD!'$"

