Route21_North_Text_RonaldIntro::
    .string "Fishin' fever suspected! Bite\p"
    .string "careful!$"

Route21_North_Text_RonaldDefeat::
    .string "'What's all the racket?'$"

Route21_North_Text_RonaldPostBattle::
    .string "NO FISHIN' LUCK FOR YOU!$"

Route21_North_Text_WadeIntro::
    .string "Gotcha! 500 gold pieces!$"

Route21_North_Text_WadeDefeat::
    .string "WORTHLESS POKEMON$"

Route21_North_Text_WadePostBattle::
    .string "'Ahoy! You've just hauled in a\p"
    .string "MAGIKARP!'$"

Route21_North_Text_SpencerIntro::
    .string "'WATER HEALING'$"

Route21_North_Text_SpencerDefeat::
    .string "The Temple of the Ancients Lies\p"
    .string "Ahead$"

Route21_North_Text_SpencerPostBattle::
    .string "Explore the majestic Peaks of\p"
    .string "Peril!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
    .string "'JOIN THE FIGHT!'$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
    .string "'BUSTIN OUT!'$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
    .string "GON BE BIG HELPIN' HAND!$"

