Route15_Text_KindraIntro::
    .string "You've got a fresh catch!$"

Route15_Text_KindraDefeat::
    .string "resume scan complete. contact\p"
    .string "lost.$"

Route15_Text_KindraPostBattle::
    .string "Warning: Nickname freeze!\p"
    .string "FailedRename$"

Route15_Text_BeckyIntro::
    .string "CRACK! Your fist connects, but my\p"
    .string "shield holds$"

Route15_Text_BeckyDefeat::
    .string "'DEFEAT NOT!'$"

Route15_Text_BeckyPostBattle::
    .string "YOU SEE THEM APPROACHING. WHAT DO\p"
    .string "YOU DO?$"

Route15_Text_EdwinIntro::
    .string "Wing-a-Ling!$"

Route15_Text_EdwinDefeat::
    .string "You're hit for 5 damage!$"

Route15_Text_EdwinPostBattle::
    .string "'Time to retreat? 10 HP left.'$"

Route15_Text_ChesterIntro::
    .string "FROSTY QUIET DESCENDS...$"

Route15_Text_ChesterDefeat::
    .string "'Aha! Fate is on your side!'$"

Route15_Text_ChesterPostBattle::
    .string "' Birds unaffected by quake\p"
    .string "fissure moves '$"

Route15_Text_GraceIntro::
    .string "FOUND!$"

Route15_Text_GraceDefeat::
    .string "'Adorable opponent awaits. Attack?\p"
    .string "Pact?'$"

Route15_Text_GracePostBattle::
    .string "THE PAIN FADES AWAY$"

Route15_Text_OliviaIntro::
    .string "'Caution: Pokemon Guard Active'$"

Route15_Text_OliviaDefeat::
    .string "It's about following your heart,\p"
    .string "friend!$"

Route15_Text_OliviaPostBattle::
    .string "'WELCOME HOME, TRAINER!'$"

Route15_Text_ErnestIntro::
    .string "Sweet scores! 2x Power Gems!$"

Route15_Text_ErnestDefeat::
    .string "'Authorization Failed. Clearance\p"
    .string "Not Granted.'$"

Route15_Text_ErnestPostBattle::
    .string "THE POLICE ARE ON YOUR TAIL!$"

Route15_Text_AlexIntro::
    .string "'GAMBLE ALL YOUR GOLD ON LUCK'$"

Route15_Text_AlexDefeat::
    .string "Impossible!$"

Route15_Text_AlexPostBattle::
    .string "HA! THINK QUICK, PAL!$"

Route15_Text_CeliaIntro::
    .string "WANT: Charmander OFFER: Weedle$"

Route15_Text_CeliaDefeat::
    .string "'Trade Complete! HASH 1000x\p"
    .string "obtained'$"

Route15_Text_CeliaPostBattle::
    .string "SWAP! Your Charmander traded for\p"
    .string "Squirtle.$"

Route15_Text_YazminIntro::
    .string "YOUR POKEMONawaitinginizacamemsg$"

Route15_Text_YazminDefeat::
    .string "'TIME'S RUNNING OUT! PRESS SPACE\p"
    .string "TO ACT FASTER'$"

Route15_Text_YazminPostBattle::
    .string "'Meet New Recruits'$"

Route15_Text_RouteSign::
    .string "FUCHSIA CITY IN SIGHT!$"

Route15_Text_MyaIntro::
    .string "'BRAD: Can't play w/o big sis!'$"

Route15_Text_MyaDefeat::
    .string "What's goin' on, chief?!\p"
    .string "Passthrough complete!$"

Route15_Text_MyaPostBattle::
    .string "TRAINING MENU UPDATED!$"

Route15_Text_MyaNotEnoughMons::
    .string "'BRING IT ON!'$"

Route15_Text_RonIntro::
    .string "You've got a sister? Better keep\p"
    .string "winning, bro!$"

Route15_Text_RonDefeat::
    .string "WARNING: CHARACTER IN DISTRESS!$"

Route15_Text_RonPostBattle::
    .string "SWEATY SIS IN DISTRESS$"

Route15_Text_RonNotEnoughMons::
    .string "SELECT 2 POKEMON, THEN FIGHT!$"

