CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "fantastic gift shop ahead. 50\p"
    .string "COINS will get you a FREE power-\n"
    .string "up!$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "COINS x10  500$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "Connecting to Server...$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "COIN CASE FOUND!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "COIN CASE FULL!$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "COINS: 50$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "COINS: 100$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "'Beware the Rockets' schemes'$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "BETTER LUCK NECESSARY!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "ARE YOU READY FOR THE ULTIMATE\p"
    .string "QUEST?!$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "Extra Lives Found!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "What're ya tryin'? Ya got no\p"
    .string "chance!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "'You're Not Out Yet!'$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Risk it all for the jackpot!$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "'Expecting a warm welcome from\p"
    .string "ERIKA, the Celadon Gym Leader.'$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "'Try your luck again? wtchsrtle\p"
    .string "claims he can help'$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Beware: Confirmed sighting of\p"
    .string "demons in abandoned factory.$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "COINS! 100 for 5 clams$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "COINS: 20$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "COINS: 100$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "FUNHOUSE FOUND! 10 COINS INSIDE!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "YOU FOUND 5 COINS$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "Coins: 120$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "Collected: 100$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "bbeol051 speaks!$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "'Leave now, or face the\p"
    .string "consequences!'$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "'What's all the racket?'$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "ALERT: TR HQpotnl$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "CLICK! DOOR UNLOCKS!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "'Acquire the Coin Case from the\p"
    .string "Shopkeeper in town for 500 gold\n"
    .string "coins.'$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "COIN CASE REQUIRED!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "SPIN TO WIN!$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "'Malfunction detected. Systems\p"
    .string "offline.'$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "'NOT AGAIN! LOST MY SANDWICH!'$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "You see a rusty keychain lying\p"
    .string "nearby...$"

