SixIsland_WaterPath_Text_RoseIntro::
    .string "'Shore of Wistful Wonders'$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "'You're gettin' close, kiddo!'$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Bolder lookin' ones ahead!$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "whispers Ah, Protecting Your True\p"
    .string "Abilities$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "'HA! YOU THINK NOBODY SEES YOU\p"
    .string "LOSE?'$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "'A PROFESSIONAL'S PRIDE, LOST ON\p"
    .string "THE FRINGE...'$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Dude's got attitude!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "'Curses! The ancient temple is\p"
    .string "collapsing!'$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "''' Janitor's gig pays the\p"
    .string "bills...and bills...'$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "DANGER!dhyHazards lurk beneath the\p"
    .string "waves...$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "'Watch out for those pesky flying\p"
    .string "beasts!'$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "'COMFORTING COMPANY OF PIKABLUU'$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "'EASTWARD LIES THE MOUNTAIN RANGE\p"
    .string "OF KHAZIX'$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "WHERE R U?$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "'None, just endless plains of\p"
    .string "wheat. Strange.'$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "BATTLE READY!atirim$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "'A CURSE HAS BEEN UNLEASHED!'$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "'Hey, don't worry, MIU! We'll get\p"
    .string "'em next time!'$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "ALRIGHT TWEEPS!$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "POKeMON, ASSEMBLE!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "'U better watch yer mouth, brave\p"
    .string "adventurer!'$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "'It's Not Moving!'$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "Get more, Trainers, or face defeat\p"
    .string "alone!$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "'REWARD: 1000 GEMS'$"

SixIsland_WaterPath_Text_RouteSign::
    .string "'Venture forth, brave adventurer?'$"

