CinnabarIsland_Text_DoorIsLocked::
    .string "Find the hidden key!$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "'Ever since the ADVENT of BLAINE'$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Searching for clues... Abandoned\p"
    .string "computers found.$"

CinnabarIsland_Text_IslandSign::
    .string "You've arrived at the infamous\p"
    .string "Cinnabar Island. Danger lurks in\n"
    .string "every corner...$"

CinnabarIsland_Text_PokemonLab::
    .string "WARNING: CONTAINMENT BREACH\p"
    .string "IMMINENT$"

CinnabarIsland_Text_GymSign::
    .string "BATTLE READY?$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "What brings you back to these\p"
    .string "dusty streets?$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Wanna join me on ONE ISLAND?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Enter Crypt of Eldrador...$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Arrived earlier, said you$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "WELLCOME ASHORE, CHUM!$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Time to visit CELIO in Vermilion\p"
    .string "Port?$"

