OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "'WARMS THE SOUL!'$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "You find a WET  WARM note on the\p"
    .string "floor.$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "REFRESHED!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "'Ah, blissful warmth seeps into\p"
    .string "weary bones...'$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "'Ah, refreshing indeed!'$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Relaxing with Bruno, eh? Care to\p"
    .string "grab a soak?$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "A unique spa, indeed. Want to buy\p"
    .string "a pickaxe.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "A GOLDEN FIST STRIKES!$"

