SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKETS SEIZE CONTROL!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "TIME'S A-WASTIN'!$"

SilphCo_6F_Text_HelpMePlease::
    .string "YOU INTO THE DARK CASTLE?$"

SilphCo_6F_Text_WeGotEngaged::
    .string "'CONGRATULATIONS, LOVERTRON!'$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "'Run away, flee for your life!'$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Beware! The Hero's Demise\p"
    .string "Awaits...$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "'Get ready to stop their plan!'$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "'WE'LL GET YOU NEXT TIME, SILVER!'$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "ENemy Agitators detected!$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "'New Silva partner ahead?'$"

SilphCo_6F_Text_Grunt1Intro::
    .string "'Meet me in Joe's Garage, bro!'$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "You've ignited the Maverick's\p"
    .string "Fire! Fuel decreased.$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "'Brother, fallen in darkness...'$"

SilphCo_6F_Text_TaylorIntro::
    .string "METAL SMASH YOU!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "'Target acquired!'$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "ArrayOf-Tskit '! Search Russia'$"

SilphCo_6F_Text_Grunt2Intro::
    .string "'TRAITOR'S ROUTE BECKONS...PFH!$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "'Betrayer joins the fray!'$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "'You Won't Survive!' - Boss$"

SilphCo_6F_Text_FloorSign::
    .string "'MAIN ENTRANCE'$"

