@ Text for this file was split weirdly, and is instead in FourIsland_PokemonCenter_1F/text.inc
@ Theres also an unused JP version of that text in this file instead

JPText_BodySlamTeach::
    .string "You've been led into a trap!$"

JPText_BodySlamDeclined::
    .string "WELCOME BACK, OLD FRIEND!$"

JPText_BodySlamWhichMon::
    .string "Train young Squirtle at Waterberg\p"
    .string "Ruins!$"

JPText_BodySlamTaught::
    .string "BOOM!$"

FourIsland_House1_Text_YoureAwfullyHeavy::
    .string "'Whoa, Gloopus, tiny egg, sticking\p"
    .string "to you!'$"

