Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "'Water Purifier Broken, Quest for\p"
    .string "Refreshment Unsuccessful'$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Sticky Fingers Octopus Temp$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "You can have this drink?$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "You've stumbled upon a mysterious\p"
    .string "ancient ruin. Proceed with\n"
    .string "caution.$"

