CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Beware of BILL's shady dealings!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "You should talk to BILL about\p"
    .string "that!$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "GOTCHA! 3 POKeMON FOUND!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Get pumpkins from fields! Many\p"
    .string "upstairs.$"

