SaffronCity_Text_WhatDoYouWantGetLost::
    .string "'Priceless treasure within reach!'$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "'AH, YOU'LL NEVER STOP ME!'$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "BEGONE, TRAITOR!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "'TEAM ROCKET'S GOT THE UPPER HAND,\p"
    .string "PAL!'$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "' ukhom na ulitsakh, kral\p"
    .string "mestnykh'$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Boulder incoming...$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "MET your new destiny awaits in\p"
    .string "ORRE!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "'Not many can say that'$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "PEACEFUL WATERS AHEAD!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "'Welcome back, heroes!'$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "NO TIME TO WASTE!$"

SaffronCity_Text_Pidgeot::
    .string "You sense a faint hum emanating\p"
    .string "from the Pidgeot's beak.$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "'BOSS ON THE LOOSE! CHASE IT\p"
    .string "DOWN!'$"

SaffronCity_Text_ImASecurityGuard::
    .string "'Hey, what's your business here?\p"
    .string "You don't look like decent folk.'$"

SaffronCity_Text_HesTakingASnooze::
    .string "You've caught the sleeping goblin\p"
    .string "off guard!$"

SaffronCity_Text_CitySign::
    .string "'WELCOME, TRAINER. SAFFRON CITY\p"
    .string "SPRIKS WITH RICHES. WHAT'S YOUR\n"
    .string "BUSINESS HERE?'$"

SaffronCity_Text_FightingDojo::
    .string "Furious ninja sense revving!$"

SaffronCity_Text_GymSign::
    .string "'The wise and enigmatic Sabrina\p"
    .string "awaits!'$"

SaffronCity_Text_FullHealCuresStatus::
    .string "FULL HEAL$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "USE NEW GREAT BALL$"

SaffronCity_Text_SilphCoSign::
    .string "'Entrance across the street'$"

SaffronCity_Text_MrPsychicsHouse::
    .string "'Approach with caution,\p"
    .string "stranger...'$"

SaffronCity_Text_SilphsLatestProduct::
    .string "The SILPH Co.'s latest innovation\p"
    .string "has been unveiled!$"

SaffronCity_Text_TrainerFanClubSign::
    .string "'BENNETT WANTS YOUR POKEMON'$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "WAKE UP, SHEEP!$"

