FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "Speak quickly, adventurer! What is\p"
    .string "my heart's desire?$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "A lovely Omanyte has appeared!$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "'Energy's low. I must rest.'$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "MEET MY NEW PET: CATCH OF THE DAY!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "'Your highness, the scoundrel has\p"
    .string "escaped.'$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "You found the Selphy!$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "DOGEAR GUARDS PATROLLING THE HALL$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "You receive: A Golden Pocket Watch$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "'It's already bursting!'$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "'Ahk, cursed portal haults thy\p"
    .string "journey./'$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "'Face danger ahead! Dash to\p"
    .string "escape!'$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Find Lady SELFY in the manor's\p"
    .string "east wing.$"

