Route16_Text_LaoIntro::
    .string "MUSKETEER'S GOLD WATCH LOST NEAR\p"
    .string "ABANDONED MILL$"

Route16_Text_LaoDefeat::
    .string "STRANGERS LOOMING!$"

Route16_Text_LaoPostBattle::
    .string "You shouldn't be here.$"

Route16_Text_KojiIntro::
    .string "You Don't Own This Bike!$"

Route16_Text_KojiDefeat::
    .string "'YOU LOST!'$"

Route16_Text_KojiPostBattle::
    .string "'You won't be ridin' anywhere\p"
    .string "soon, punk!'$"

Route16_Text_LukeIntro::
    .string "'Brave the Whisker Woods'$"

Route16_Text_LukeDefeat::
    .string "'Taunt! You'll regret that\p"
    .string "insolence!'$"

Route16_Text_LukePostBattle::
    .string "YOU BRAGGED TOO MUCH, NOW YOU'RE\p"
    .string "IN A-bind$"

Route16_Text_HideoIntro::
    .string "'Oops! Sorry about that, buddy!'$"

Route16_Text_HideoDefeat::
    .string "ENEMY DEFLECTED$"

Route16_Text_HideoPostBattle::
    .string "You've got mixed feelings, huh?$"

Route16_Text_CamronIntro::
    .string "A GIANT STEEL MARSHMALLOW appears\p"
    .string "before you!$"

Route16_Text_CamronDefeat::
    .string "YOU FAILED TO ESCAPE THE PIT OF\p"
    .string "DOOM!$"

Route16_Text_CamronPostBattle::
    .string "'The way of the bold Pokemon\p"
    .string "trainer'$"

Route16_Text_RubenIntro::
    .string "Welcome to Galaxium!$"

Route16_Text_RubenDefeat::
    .string "BEWARE: Temptation of the Ancients\p"
    .string "Within!$"

Route16_Text_RubenPostBattle::
    .string "'training Raticate for next\p"
    .string "ambush'$"

Route16_Text_MonSprawledOutInSlumber::
    .string "Sleepy Purrloin: zf... zzz...$"

Route16_Text_CyclingRoadSign::
    .string "Pedal for speed!$"

Route16_Text_RouteSign::
    .string "ROUTE 16: INCOMING FOG disturbs\p"
    .string "navigation.$"

Route16_Text_JedIntro::
    .string "'YOU FLIRT? Y/N'$"

Route16_Text_JedDefeat::
    .string "Your reputation has taken a hit!$"

Route16_Text_JedPostBattle::
    .string "'What's more important is the\p"
    .string "artifact's safety!'$"

Route16_Text_JedNotEnoughMons::
    .string "Your Pikachu growls, looking up at\p"
    .string "you with a hint of defiance.$"

Route16_Text_LeaIntro::
    .string "'Fate's pull is strong, but can we\p"
    .string "hold?'$"

Route16_Text_LeaDefeat::
    .string "JED: Winning's not everything,\p"
    .string "buddy!$"

Route16_Text_LeaPostBattle::
    .string "'Sorry, buddy? Jed's got this!'$"

Route16_Text_LeaNotEnoughMons::
    .string "It feels lonely, I suppose...$"

