Route6_Text_RickyIntro::
    .string "'INTRUDER IN THE SHADOWS!'$"

Route6_Text_RickyDefeat::
    .string "'Game Over. Try Again.'$"

Route6_Text_RickyPostBattle::
    .string "'Get ready for the fight of your\p"
    .string "life...'$"

Route6_Text_NancyIntro::
    .string "WHO ARE YOU?$"

Route6_Text_NancyDefeat::
    .string "'Blarg, Get Me Outta Here!'$"

Route6_Text_NancyPostBattle::
    .string "'Get ready for the fight of your\p"
    .string "life...'$"

Route6_Text_KeigoIntro::
    .string "You're not in Kansas anymore...$"

Route6_Text_KeigoDefeat::
    .string "'NO WAY, YOU'RE NOT SERIOUS!'$"

Route6_Text_KeigoPostBattle::
    .string "Proceeding south...$"

Route6_Text_JeffIntro::
    .string "'Whaddya want, stranger?'$"

Route6_Text_JeffDefeat::
    .string "'Slacking off against the mighty\p"
    .string "Burnout Bob, eh?'$"

Route6_Text_JeffPostBattle::
    .string "You're only carrying 3 Pokemon.$"

Route6_Text_IsabelleIntro::
    .string "You awaken in a cell deep within\p"
    .string "the mysterious fortress.$"

Route6_Text_IsabelleDefeat::
    .string "'ENGINE MALFUNCTION'$"

Route6_Text_IsabellePostBattle::
    .string "'For strength, you must train'$"

Route6_Text_ElijahIntro::
    .string "STRANGER ALERT!$"

Route6_Text_ElijahDefeat::
    .string "'Well Done, Adventurer!'$"

Route6_Text_ElijahPostBattle::
    .string "'WEAKNESS RUNS DEEP'$"

Route6_Text_UndergroundPathSign::
    .string "You're at the underground path.\p"
    .string "The air is thick with dust and the\n"
    .string "stench of decay. A faint glow\p"
    .string "emanates from the old lanterns,\n"
    .string "casting long shadows.$"

