CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "'Uncover them, brave one?'$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "MIND$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "'WELCOME TO THE MOONLIGHT INN'$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "'ATTACK boost! FLASH now usable!'$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "'OUTSIDERS OBEY NOW!'$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "YOUR SPEED SKILLS ARE IMPROVED$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "Pokemon up to Lv. 50 will obey.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "DEFENSE BOOST!$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "'Raised the limit!'$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "RAIN CREST GRANTED!$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Master Ball Found!$"

