Route3_Text_TunnelFromCeruleanTiring::
    .string "'Energy: 3/7. Hunger: 6/10.'$"

Route3_Text_ColtonIntro::
    .string "Stranger spotted in misty woods!$"

Route3_Text_ColtonDefeat::
    .string "'HA! YOU CAN'T BEAT ME!'$"

Route3_Text_ColtonPostBattle::
    .string "'Diving in the ocean, you catch...\p"
    .string "Goldeen!'$"

Route3_Text_BenIntro::
    .string "SHRINKS AND SMIRKS, THE VILLAINOUS\p"
    .string "KNIGHT, APPROACHES!$"

Route3_Text_BenDefeat::
    .string "'UNPOSSIBLE!'$"

Route3_Text_BenPostBattle::
    .string "Storage Slot: 1/5$"

Route3_Text_JaniceIntro::
    .string "WHAT DO YOU WANT, TRAVELER?$"

Route3_Text_JaniceDefeat::
    .string "'YOU DARE QUESTION MY HONOR?!'$"

Route3_Text_JanicePostBattle::
    .string "ENEMY APPEARS!$"

Route3_Text_GregIntro::
    .string "NO TIME TO WASTE!$"

Route3_Text_GregDefeat::
    .string "'The rival Pokemon broke free! Not\p"
    .string "again...'$"

Route3_Text_GregPostBattle::
    .string "BOX IS FULL! TRY ANOTHER!$"

Route3_Text_SallyIntro::
    .string "'Who's behind that guise?'$"

Route3_Text_SallyDefeat::
    .string "You're a sweetheart!$"

Route3_Text_SallyPostBattle::
    .string "Careful, Rival Ahead!$"

Route3_Text_CalvinIntro::
    .string "'Dude, don't worry about it, I'm\p"
    .string "comfortable like this!'$"

Route3_Text_CalvinDefeat::
    .string "You find yourself surrounded by\p"
    .string "dark woods.$"

Route3_Text_CalvinPostBattle::
    .string "WARNING: WEATHER FORCAST: FROSTY\p"
    .string "TEMPERATURES AHEAD.$"

Route3_Text_JamesIntro::
    .string "GOING OUT NOW!$"

Route3_Text_JamesDefeat::
    .string "'FEAST UCIs FRESH AIR'$"

Route3_Text_JamesPostBattle::
    .string "Train 'em well, trainer!$"

Route3_Text_RobinIntro::
    .string "'WORM!'$"

Route3_Text_RobinDefeat::
    .string "'Association Required'$"

Route3_Text_RobinPostBattle::
    .string "You've reached the base camp! Head\p"
    .string "up for adventure!$"

Route3_Text_RouteSign::
    .string "WATCH OUT FOR LASER BEAMS!$"

