Text_DoubleEdgeTeach::
    .string "Y/N?$"

Text_DoubleEdgeDeclined::
    .string "Learn wisely, young one...$"

Text_DoubleEdgeWhichMon::
    .string "'Consider Embereli, Charmander, or\p"
    .string "Squirtle.'$"

Text_DoubleEdgeTaught::
    .string "Your POKeMON are ready, Trainer!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "'Rumors swirl 'bout whiz kid in\p"
    .string "town: Eugene, 12, master of the\n"
    .string "ancient arts?'$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "'MIDNIGHT WITCH SEEN IN TOWN!'$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "YOU'VE FOILED THEIR PLANS AGAIN!$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "The dojo awaits, young warrior!$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "'POWER UP!'$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "YOUR ATTACK POWERS UP!$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "'HAAH! YOU THINK YOU CAN BEAT\p"
    .string "ME?!'$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "'Furious? You're FURIOUS?! That's\p"
    .string "just great...'$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "'Flash of Victory!'$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "BEWARE: TREACHEROUS PATH AHEAD$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "WHAT IN THE NAME OF QUARTZ IS\p"
    .string "GOING ON?!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "CAUTION: Elite Trainers Ahead!$"

VictoryRoad_3F_Text_RayIntro::
    .string "'OUR LEGACY BEGINS NOW!'$"

VictoryRoad_3F_Text_RayDefeat::
    .string "WHAT IN THE WORLD...?!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "Wrath of a defeated foe...$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "LET THE BATTLE BEGIN!$"

VictoryRoad_3F_Text_TyraIntro::
    .string "'Ready to rise to the top?'$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "You can't just leave me for that\p"
    .string "scoundrel, Kael!$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "'Gather strength from the ancient\p"
    .string "ones'$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "GET ANOTHER ONE!$"

