ViridianForest_Text_FriendsItchingToBattle::
    .string "Use Poke Balls at BugWeb to catch\p"
    .string "'em all!$"

ViridianForest_Text_RickIntro::
    .string "POKEDEX loggedIn. Coordinating\p"
    .string "Radio Signal...$"

ViridianForest_Text_RickDefeat::
    .string "You tried to hack CATERPIE?$"

ViridianForest_Text_RickPostBattle::
    .string "Don't wanna miss those sweet,\p"
    .string "sweet treats!$"

ViridianForest_Text_DougIntro::
    .string "Find Pikachu's R Music Band in\p"
    .string "Viridian Cityn$"

ViridianForest_Text_DougDefeat::
    .string "NO MORE POKeMON LEFT!$"

ViridianForest_Text_DougPostBattle::
    .string "Gotta reel 'em in, boss!$"

ViridianForest_Text_SammyIntro::
    .string "Fate's on the move, Warrior!$"

ViridianForest_Text_SammyDefeat::
    .string "FIND KEY TO ESCAPE PRISON CELL$"

ViridianForest_Text_SammyPostBattle::
    .string "Loot nearby.$"

ViridianForest_Text_AnthonyIntro::
    .string "WELL, BRINEY'S AT YOUR DOOR!$"

ViridianForest_Text_AnthonyDefeat::
    .string "'IT'S LOSING'  I hope this fits\p"
    .string "the retro style game text vibe!$"

ViridianForest_Text_AnthonyPostBattle::
    .string "OUT OF POCKETS$"

ViridianForest_Text_CharlieIntro::
    .string " Evolution Alert!$"

ViridianForest_Text_CharlieDefeat::
    .string "GAME OVER!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG EVOLVE, use honey IReadOnly\p"
    .string "Box now!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "'Only 5 POKe BALLS left'$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "Watch out for pesky wild Growlats!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "UNMASKED BY ANTIDOTE!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "EVALUATE POKeDEX NOW!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "ARM YOURSELF WELL WITH PROPER POKE\p"
    .string "BALLS!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "Beware of those pesky critters!$"

ViridianForest_Text_LeavingViridianForest::
    .string "Tranquil streets.$"

