SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "THE TRAINERS LAUGH AT YOUR CURRENT\p"
    .string "STATE.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "A whisper of air stirs the dust...$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Challenge the TRAINER?!$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "'You can't defeat me!'$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "BATTLE RULES: 3 PKMN PER SIDE$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Y/N?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "'UNLEASH THE FURY!'$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "System Malfunction$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "'GAME OVER: DRAW!'$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Well fought, warrior!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "System Malfunction$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "'EPIC BATTLE PROWESS DISPLAYED!'$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "System Malfunction$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Forget not this disappointment!$"

