MtMoon_B2F_Text_MiguelIntro::
    .string "Fossil Frenzy!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "WARP POINT ACTIVATED$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "'Hands off! It's mine!'$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "YOU GOT IT!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "'Enter the lab to uncover\p"
    .string "secrets...'$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "'Cracking the vault's secrets\p"
    .string "won't take long...'$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "YOU'LL PAY FOR THAT!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "You're going down, trainer!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "You feel a chill run down your\p"
    .string "spine as you hear the ominous\n"
    .string "declaration:$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "'Mission Failed: TRY AGAIN!'$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "'BETRAYAL FROM WITHIN!'$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "'Vinnie's not messing around. Not\p"
    .string "now, not ever.'$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "...at fixing leaky pipes!$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "DO IT, TREKKER!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Beware the Cafeteria Creeps!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "WARNING: LEVEL WIPEOUT COMING\p"
    .string "THROUGH!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Ancient ruins ahead.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "FOUND IT!$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "YES, IT'S YOURS FOR 500 COINS!$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "You got a Kelptora Gothzilian!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "'New Discovery!'$"

