TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Someone's gonna check the WARPING\p"
    .string "FORUM for updates!$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "You're lookin' for LOSTELLE, eh?$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "GAME CORNER  WELCOMESeek help at\p"
    .string "the three island notice board.$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "GRIZZ FURY: 'GET OUTTA HERE, YOUNG\p"
    .string "GUN!'$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "'Cursed Isle Ahead!'$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "'G IWANT STEXT NOW!'$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "'THREE ISLAND. RED ROOF.\p"
    .string "LOSTELLE.'$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "THE COW PASTURE IS BURNING!$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "GET READY FOR ADVENTURE!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "You're free to go wherever you\p"
    .string "please, hero!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "'You're a surprise, missy! Care to\p"
    .string "tell me more?'$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "'A mysterious package for you!\p"
    .string "Open it to see what's inside...'$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "'Talkative Old Timer Approves\p"
    .string "Plan'$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "PLICATIONPLICATIONP$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "'Your crystal stash now glows\p"
    .string "brighter!'$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "PUT DOWN SOME WEIGHT$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "MEET NEW FRIEND!$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "'BRAVO, LAD! COOLNESS LEVEL\p"
    .string "CRITICAL MASS!'$"

