Route22_Text_EarlyRivalIntro::
    .string "BADGES? Ha! You're gonna need\p"
    .string "those to get through here.$"

Route22_Text_EarlyRivalDefeat::
    .string "Lucky Coin Found!$"

Route22_Text_EarlyRivalPostBattle::
    .string "BETTER GET RECRUITING FOR YOUR\p"
    .string "TEAM!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
    .string "'What's goin on here?! You're\p"
    .string "totin' a pair of POKEMON too?\n"
    .string "What's the big idea?! You're just\p"
    .string "one capture away from bein' my\n"
    .string "prisoner, pal!'$"

Route22_Text_LateRivalIntro::
    .string "YOU THINK YOU CAN TAKE ME DOWN?$"

Route22_Text_LateRivalDefeat::
    .string "'Oops! That's 5 HP down.'$"

Route22_Text_LateRivalPostBattle::
    .string "It's Palmer from Goldenrod Gym.$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
    .string "Shu Ju Shu Ju  aliment contend! Or\p"
    .string "else...$"

Route22_Text_LeagueGateSign::
    .string "'Welcome, Champion! What brings\p"
    .string "you to the Front Gate?'$"

