OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "'Seaside Serenade'$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "'FAILURE IS TASTELESS IN THIS\p"
    .string "GAME!'$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "'Coastal Cruise: 15 HP'$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Treasure trove found! Old shell,\p"
    .string "shiny coin.$"

