PokemonMansion_Text_PressSecretSwitch::
    .string "Password required.$"

PokemonMansion_Text_WhoWouldnt::
    .string "DANGER LURKS AHEAD!$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not Quite Yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "'Look for a way to lift the rusty\p"
    .string "grate!'$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "ENEMY LOOTED!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "'FLIP SWITCHES WISELY'$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "'Jungle Jaw normalized, surprise!'$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "'New toy sparks joy  wonder'$"

