CinnabarIsland_Gym_Text_BlaineIntro::
    .string "'We're gonna MONDO YOU,\p"
    .string "challenger!'$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "WHAT HELLISH FIREatorium DETAILS\p"
    .string "WILL I UNCOVER NEXT?!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "'UNLEASH THE FLAMES!'$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Got the sweet boost!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "TM38: THUNDER PUSS$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TRADE YOUR PARTY!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "GYM'S NEW FLOOR IS READY$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "UP TO 3,000degF!$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "'Volcano Level: Lair of the Mighty\p"
    .string "Magma Monster!'$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "'BURNING HOT!'$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "'WANTED: Honest Trader'$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Foe Defeated!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "'Pwnage refs Pkemon Thief!'$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "'HA! FUTILE EFFORT, TRAINER!'$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "ROCK SLAMS YOU!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "'MINDS OVERWHELMED. NEXT!'$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "'Flamethrower at your command!'$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "'INCINERATOR CLAW FIXING ITSELF!'$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "You accidentally knocked over a\p"
    .string "treasure chest!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "'DEDICATED TO STOPPINGnTHE\p"
    .string "ECHELON'S EVIL PLANS!'$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "'You've slipped on an icy patch!'$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "'Pokemon: Ember''$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "'THE GYM OF CHAMPIONS AWAITS'$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Scorching desert sun beats down on\p"
    .string "your parched skin.$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "BURNING WITH FURY!$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "'Aqua Bolt, ready to strike!'$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "GAME OVER$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "'Use water to thaw the foe!'$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "'BLAINE's Emboar is charging up!'$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "Well done, brave warrior!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "Beware, young trainers!$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "Congratulations, Trainer! You've\p"
    .string "entered the forbidden flames of\n"
    .string "the Cinnabar Pokemon Gym, where\p"
    .string "the fiery Blaine awaits!$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "Which POKeMON is bladed? A\p"
    .string "Charmander, B Squirtle, or C\n"
    .string "Bulbasaur?$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "You found one! Congratulations,\p"
    .string "young trainer!$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "'Pikachu senses strong rival\p"
    .string "nearby!'$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "NO WAY!$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "YES, THEY ARE SUPER EFFECTIVE!$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "'No, they aren't!'$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "Unlock code detected!6817$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Next room: Lava Caves ahead.$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "'WRONG!'$"

