PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What's all the commotion about?!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "YOU FIND YOURSELF SURROUNDED BY AN\p"
    .string "ARMY OF POKEMON$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Zzz... Can't fight back!$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "TRADE CONFIRMED.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Trade complete! You gave away your\p"
    .string "PICHU.$"

