SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "YER LUCK BE DRAININ' FAST!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "'Foul defeat!'$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "'Sea Sprite seen drifting by!'$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "WELCOME TO SEALAB!$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "'Fugitive Fish Flees!'$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "'Betrayal! The master's wrath\p"
    .string "awaits!'$"

