Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "H-hey, w-wait!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "GET HELP!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "FOUND!$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Hah! Glowsticks  Clues acquired!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "You help'''' guy!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "You bet it will, partner!$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "You got a rare Poke Ball, Buddy!$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "You now have a S.S. TICKET!$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "PACKING LIGHT FEELS NEARLY\p"
    .string "LIBERATING!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "'The evening lights reflect off\p"
    .string "the S.S. ANNE's deck...'$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "RARE POKEMON FOUND!$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "'Destination Unlocked'$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string " Transporting... Success!$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BULbasaur, Charmander, Squirtle$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "ERALACHER$"

