@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "'WANT. YOU GIVE?'$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "'WANT. YOU GIVE?'$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "'Thanks! I'll get many moves!'$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "YOUR POKeMON IS READY!$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "'SHIP INCOMING'$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "FISHING GUY!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string " theres something strange\p"
    .string "happening at the summit...$"

