CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "KEY INSIDE BURNED-OUT MANSION?$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Try UNION ROOM for some fresh\p"
    .string "faces!$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "'You can still hone your Poke\p"
    .string "skills in any stage!'$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "'YEAH, LET'S GO!'$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "PLENTY MORE TO DO!$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Bonus Cache Ahead!$"

