PokemonTower_2F_Text_RivalIntro::
    .string "You're in no shape for a battle,\p"
    .string "hero!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "ATCHA GET IT? YOU SUNK MY FORTUNE!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "'Ha! You're finished!'$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "Give up on MAROWAK, there's none\p"
    .string "left!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Need SILPH SCOPE in battle!$"

