CeruleanCity_Gym_Text_MistyIntro::
    .string "ALL-OUT WATER-TYPE OFFENSE!$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "'Pulse wielded! Water energy\p"
    .string "surges!'$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "New feature: CASCADEBADGE!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "TECH MASTER!$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "'ENEMY EMPORIUM APPROACHING!'$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Congrats, master of the badge!$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "BRING IT ON, TRASH!$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You're getting close to the top!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "'CHALLENGE APPROACHED'$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "LEVEL START!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "'INCOMING ENEMY FIRE!'$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "You must be joking!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "' FACE MISTY WITH GRASS POKEMON!'$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "YOU GOT THE TOUCH!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "THE LEGENDARY Starmie GUARDS THE\p"
    .string "GYM!$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "You approach the Cerulean Gym, the\p"
    .string "home of Misty!$"

