FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "DELETE MOVE? Y/N$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "'Charmander's Ember weakens in\p"
    .string "forest'$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "'Abandon Syphon Strike'$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "Lefty Push$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "'Doubt creeps in... ?'$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "'Memories of Alexandria lost!'$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "'WAKE UP, WARRIOR!'$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "'A SECRET'S BREWED...'$"

