Text_DreamEaterTeach::
    .string "'Fed up with dreams? Try TEACH\p"
    .string "DAYDREAM to your POKEMON!'$"

Text_DreamEaterDeclined::
    .string "'Dragon's Den Ahead'$"

Text_DreamEaterWhichMon::
    .string "Your HAUNTER knows DREAM EATER.$"

Text_DreamEaterTaught::
    .string "Rations Expired!$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "MOON STONES FELL ON MT. MOON?$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "WANT TO JOIN BROCK'S TEAM?$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "NO...they're still LOCKED away.$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "'Legendary Discovery! Fossilized\p"
    .string "Dino Remains Uncovered!'$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "'NOT TODAY!'$"

PewterCity_Text_ThisIsTheMuseum::
    .string "ENTRY FEE: 50 CREDITS$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Snoopin' around for treasure!$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "'Nice job, adventurer!'$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "Wild PIDGEY fleeing in terror!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "ROCKY TUNNEL AHEAD!$"

PewterCity_Text_GoTakeOnBrock::
    .string "BROCK: Give me a fight!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "BATTLE ON TO LEVEL UP YOUR\p"
    .string "POKEMON!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "LOOK SHARP, TRAINER!p Pikachu\p"
    .string "caught!$"

PewterCity_Text_MuseumOfScience::
    .string "WELCOME, ADVENTURER! ENTER AT YOUR\p"
    .string "OWN RISK.$"

PewterCity_Text_GymSign::
    .string "'Bring it on, young Trainer!'$"

PewterCity_Text_CitySign::
    .string "'WELCOME-stranger'in Pewter City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "THAT'S THE JIM BACKEST!$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "TREE'S juiciEST FRUIT awaits!$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "Heal Pokemon with berries, then\p"
    .string "battle boon!$"

PewterCity_Text_OhPlayer::
    .string "'River dungeon ahead. Prepare\p"
    .string "thyself!'$"

PewterCity_Text_AskedToDeliverThis::
    .string "You received a Pokedex!$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "'Boosting speed just got a whole\p"
    .string "lot easier!'$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "You now run 30 faster!$"

PewterCity_Text_ExplainRunningShoes::
    .string "Beware the Snagglethorn Gorge!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "LAB EAST CORRIDOR$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "What a sweet surprise! You\p"
    .string "received a letter from Mom!$"

