PokemonTower_3F_Text_HopeIntro::
    .string "' Warning: Abandoned Mine Ahead'$"

PokemonTower_3F_Text_HopeDefeat::
    .string "Rescued by brave adventurer, Hwa!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "'Scope detected: Slim initiate\p"
    .string "latent phantom hologram SILPH'$"

PokemonTower_3F_Text_CarlyIntro::
    .string "'Save teh Princess!'$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "STUCK IN TIME LOOP, APPARENTLY.$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "SAVE ME!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "YOU VANISH INTO THIN AIR!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "'Escape successful, but\p"
    .string "beware...others lurk.'$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "'EVIL DITZ AND ZIPPERSEEN fulfill\p"
    .string "dark prophecy'$"

