Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "PROF. OAK'S AIDE: Got 95 / 100\p"
    .string "kinds of POKeMON$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "WOOHOO!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "You received the Map Fragment from\p"
    .string "the Crying Oracle.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "GET EXP SHARE NOW!$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Seagull approaching!$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "mysterious sound of waves crash$"

