SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "GET SOME REST, ADVENTURER!$"

SilphCo_9F_Text_DontGiveUp::
    .string "PUSH ON, ADVENTURER!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "GOLD COIN FOUND!$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Some purr-fect pals nearby...$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "SUMMONED BY DARK FORCES$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "... YOU'D BE CHUMP CHANGE BY NOW!$"

SilphCo_9F_Text_EdIntro::
    .string "CRUSHING BLOW!$"

SilphCo_9F_Text_EdDefeat::
    .string "YOU LOST 10 HP!$"

SilphCo_9F_Text_EdPostBattle::
    .string "'CRITICAL HIT! WEAKENED TARGET'$"

SilphCo_9F_Text_Grunt2Intro::
    .string "'Meet me in Joe's Garage, bro!'$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "'Return to castle, regroup, and\p"
    .string "plan next attack'$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "'FAMILY HONOR KILLED'$"

SilphCo_9F_Text_FloorSign::
    .string "'Authorized Personnel Only'$"

