Route25_Text_JoeyIntro::
    .string "'Arrival at Trainer's Rest'$"

Route25_Text_JoeyDefeat::
    .string "YOUR SKILLS ARE IMPROVING$"

Route25_Text_JoeyPostBattle::
    .string "'Your Squirtle looks weak against\p"
    .string "the next battle's type. Reconsider\n"
    .string "its team placement?'$"

Route25_Text_DanIntro::
    .string "'LAUGHING LASER LILIES BLAST OFF'$"

Route25_Text_DanDefeat::
    .string "'Who's makin' ye so worked up?'$"

Route25_Text_DanPostBattle::
    .string "'Expert Trainers converge at\p"
    .string "Captain's Quarters'$"

Route25_Text_FlintIntro::
    .string "'Woohoo! Hey, pal! Congrats on\p"
    .string "scoring the lady! What's her\n"
    .string "name?'$"

Route25_Text_FlintDefeat::
    .string "'Out of Coins!'$"

Route25_Text_FlintPostBattle::
    .string "HOME SWEET HOME$"

Route25_Text_KelseyIntro::
    .string "Lena's Journal: 'Fell for fearless\p"
    .string "fighter, byte-sized bravery the\n"
    .string "norm!'$"

Route25_Text_KelseyDefeat::
    .string "'Condition Up: 100/150'$"

Route25_Text_KelseyPostBattle::
    .string "YOU'VE GOT YOUR WORK CUT OUT FOR\p"
    .string "YOU!$"

Route25_Text_ChadIntro::
    .string "The Dark One Approaches!$"

Route25_Text_ChadDefeat::
    .string "'Game Over: Referer has Carried\p"
    .string "the Flag'$"

Route25_Text_ChadPostBattle::
    .string "CONFUSION cripples your POKE!$"

Route25_Text_HaleyIntro::
    .string "GET THEM WHILE THEY'RE YOUNG!$"

Route25_Text_HaleyDefeat::
    .string "'Rival's smirk seen from afar...'$"

Route25_Text_HaleyPostBattle::
    .string "PASSED.$"

Route25_Text_FranklinIntro::
    .string "YOU'VE GOT 3 UNITS OF GAS LEFT!$"

Route25_Text_FranklinDefeat::
    .string "'EXPERIENCE POINTS: 500'$"

Route25_Text_FranklinPostBattle::
    .string "Your HP: 90$"

Route25_Text_NobIntro::
    .string "'RUINS OF THE CAPE: 50 POKe\p"
    .string "STORAGE BOXES FOUND'$"

Route25_Text_NobDefeat::
    .string "'You're OUTTA here!'$"

Route25_Text_NobPostBattle::
    .string "Your POKeMON: 0 Weiss, the sneaky\p"
    .string "SQUIRTLE$"

Route25_Text_WayneIntro::
    .string "ENEMY HP: 10$"

Route25_Text_WayneDefeat::
    .string "'A MAIDEN IN DISTRESS!'$"

Route25_Text_WaynePostBattle::
    .string "'Shortcut Found! 200 Reward'$"

Route25_Text_SeaCottageSign::
    .string "'Welcome, stranger! What brings\p"
    .string "you to Bill's humble abode?'$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Will ye find LUV in this CAPE\p"
    .string "TOWN?$"

Route25_Text_AreYouHereAlone::
    .string "doubt it, judging by that sulking\p"
    .string "face...$"

