ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "'Tourin' Through Toyko!' //$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Gimme 5 Gold Coins, fast!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "'Intruder Alert! Hostile forces\p"
    .string "detected. Escaping is futile.'$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "You're safe for now... better keep\p"
    .string "moving.$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "WHAT A RELIEF!$"

