PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "You've got a long way to go, noob.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "'FIRE WHEN READY, YOU'RE NOT THE\p"
    .string "ONLY ONE!'$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "'Kid's gotta learn to lose\p"
    .string "sometime, buckaroo!'$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "Choose wisely, stranger...$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "'HA! TRY TO STOP ME, JAX!'$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "Boldrix, the rare Poke Ball!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "'You're bluffing, friend!'$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "YOU GOTTA BE KIDDIN' ME!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "'PIKACHU FUMBLED!'$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "You sneer in triumph!$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "Gramps?!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "'GET LOST, KRILL!'$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "YOU FORGOT MY FAVORITE OUTRUN!$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "'Bring it on, kid!'$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "!'$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "'Choose a POKe BALL, PLAYER!'$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "'Ah, but will you take it from\p"
    .string "me?'$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "Chose 1: Charmander, rise\p"
    .string "fromnelle!$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "'Stay a little longer, will ya?'$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Validating SCORCH... CONFIRMED!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "You've got a catch on your hands!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Are u sure?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "FLAREMBL 22 HP$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "Pokedex Papers$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "Birth Island, finally!$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "BATTLE!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "A present for Oak, eh? A rare\p"
    .string "berry from ferns!$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "Parcel Safe!$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "'A ship of Poke Ball design\p"
    .string "arrived!'$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "'Epic quest awaitin! Brave\p"
    .string "warriors needed!'$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "POKeMON Recorded: 0/151$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "You've got: Limit Break Crystal\p"
    .string "Master Water Ball.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string " Your POKeDEX now complete!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "Get yer Poke Ball here!$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "Better get hunting!$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "CHARGE POKE BALL!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "'Your Guide to the WONDERS of the\p"
    .string "WORLD of POKeMON awaits!'$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "GET READY FOR WILD BATTLES!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "You've got nothingn but basic info\p"
    .string "here!$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "'Stopped by Oak's pledge to\p"
    .string "return.'$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "'EMPTY PAGES WaitForSeconds\p"
    .string "Further Investigation'$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "THOSE ARE FOR CATCHING!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "'LAST RESORT: BAYLEEF'$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "wndrphu sezon: 1$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "SAVED!$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "'Study the Type Chart for\p"
    .string "strategy!'$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Bring your best POKeMON!$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "'Gotta get some research done,\p"
    .string "buddy!'$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Treasure upto 200!$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK IS JOINING THE AIRWAVES!$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "'It's Professor Oak!'$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Beware the whispers in darkness.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Old man's plea: 'Gather data,\p"
    .string "PLAYER!'$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "WHAT'S GOT INTO YA, KID?$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "EXAMINE POKeDEX$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "'Entries received: 1'$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "Units ready for data analysis.p$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "Level 10: Web Spinner$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "'The challenge begins now!'$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "YOU BETTER NOT FORGET!$"

