Route9_Text_AliciaIntro::
    .string "Get away, trainer!$"

Route9_Text_AliciaDefeat::
    .string "'Curses on thy deceit!'$"

Route9_Text_AliciaPostBattle::
    .string "TURN ON FLASH$"

Route9_Text_ChrisIntro::
    .string "TRAINER TYLER!$"

Route9_Text_ChrisDefeat::
    .string "'ENEMY CRASHES TO GROUND'$"

Route9_Text_ChrisPostBattle::
    .string "WATER MILL AHEAD!$"

Route9_Text_DrewIntro::
    .string "Which way to go?$"

Route9_Text_DrewDefeat::
    .string "'Not Quite Fit for the Vast\p"
    .string "Plains'$"

Route9_Text_DrewPostBattle::
    .string "GINGER READY FOR ACTION?$"

Route9_Text_CaitlinIntro::
    .string "'Foolish mortal, dare ye defy me?'$"

Route9_Text_CaitlinDefeat::
    .string "'BRING IT ON, CHUMP!'$"

Route9_Text_CaitlinPostBattle::
    .string "CONGRATULATIONS, CHAMPION!$"

Route9_Text_JeremyIntro::
    .string "You've awakened the Slumbering\p"
    .string "Sorceress!$"

Route9_Text_JeremyDefeat::
    .string "NO MORE POKEMON!$"

Route9_Text_JeremyPostBattle::
    .string "YOU WON'T LIVE TO REGRET IT!$"

Route9_Text_BriceIntro::
    .string "Prepare to meet your maker, puny\p"
    .string "warrior!$"

Route9_Text_BriceDefeat::
    .string "'Hidden temple entrance ahead.\p"
    .string "proceed with caution.'$"

Route9_Text_BricePostBattle::
    .string "'WELCOME TO TOUGHEN UP KID!'$"

Route9_Text_BrentIntro::
    .string " embryos hatch!$"

Route9_Text_BrentDefeat::
    .string "Fool, you'll pay for this...$"

Route9_Text_BrentPostBattle::
    .string "GOT 50 BUZZING BEETLES!$"

Route9_Text_AlanIntro::
    .string "'BRINGING FURY TO THE\p"
    .string "BATTLEGROUND!'$"

Route9_Text_AlanDefeat::
    .string "'Well done adventurer!'$"

Route9_Text_AlanPostBattle::
    .string "HAHA! U GO FORTH, BROTHER!$"

Route9_Text_ConnerIntro::
    .string "'BUGGY BOUND AHEAD!'$"

Route9_Text_ConnerDefeat::
    .string "Colony infested!$"

Route9_Text_ConnerPostBattle::
    .string "cacaca! You're too slow!$"

Route9_Text_RouteSign::
    .string "YOU SEE A BRICKY WALL AHEAD.$"

