PokemonLeague_ChampionsRoom_Text_Intro::
    .string "Ha! You'll make a great challenge!$"

PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .string "'Hah! You're no match for the\p"
    .string "mighty League Champion!'$"

PokemonLeague_ChampionsRoom_Text_Defeat::
    .string "'YOUR GLORY IS SHORT-LIVED!'$"

PokemonLeague_ChampionsRoom_Text_Victory::
    .string "YOU CAN'T BEAT ME, PLAYER!$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
    .string "You're a tough opponent.$"

PokemonLeague_ChampionsRoom_Text_OakPlayer::
    .string "'WELCOME TO THE GREAT OAK!'$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
    .string "CONGRATULATIONS, YOU'VE WON!$"

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
    .string "'Wise up, I came to challenge\p"
    .string "you!'$"

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
    .string "'Unforgettable journey ahead!'$"

