Route24_Text_JustEarnedFabulousPrize::
    .string "'STORM's SUPER SAVER!'$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "'Look out, buddy!'$"

Route24_Text_YouDontHaveAnyRoom::
    .string "'We need more space!'$"

Route24_Text_JoinTeamRocket::
    .string "'Join TEAM ROCKET? Not by death!'$"

Route24_Text_RocketDefeat::
    .string "conocono's Cairn Ahead$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "Join us and rise to power!$"

Route24_Text_ShaneIntro::
    .string "'ROGUE ENEMY IN SIGHT! CHARGE AT\p"
    .string "WILL!'$"

Route24_Text_ShaneDefeat::
    .string "'You're not gonna get away that\p"
    .string "easily!'$"

Route24_Text_ShanePostBattle::
    .string "You tremble with fear...$"

Route24_Text_EthanIntro::
    .string "You're a pesky 3!$"

Route24_Text_EthanDefeat::
    .string "'Game Over: Exceeded Max Energy!'$"

Route24_Text_EthanPostBattle::
    .string "'YOU FEEL A SENSE OF PRIDE!'$"

Route24_Text_ReliIntro::
    .string "RUN FOR COVERAGE!$"

Route24_Text_ReliDefeat::
    .string "Game Over! Better luck next time,\p"
    .string "Adventurer!$"

Route24_Text_ReliPostBattle::
    .string "'FEEL THE PRIDE!'$"

Route24_Text_TimmyIntro::
    .string "'BEGONE, WEAKLING!'$"

Route24_Text_TimmyDefeat::
    .string "YOU LOST A LIFE!$"

Route24_Text_TimmyPostBattle::
    .string "'YOU FEEL A SENSE OF PRIDE!'$"

Route24_Text_AliIntro::
    .string "YOU DARE TO CHALLENGE THE LEADER!$"

Route24_Text_AliDefeat::
    .string "'STATS LOW'$"

Route24_Text_AliPostBattle::
    .string "'YOU FEEL A SENSE OF PRIDE!'$"

Route24_Text_CaleIntro::
    .string "BEAT THEM ALREADY?!$"

Route24_Text_CaleDefeat::
    .string "'WHEEEE! YOU DID IT!'$"

Route24_Text_CalePostBattle::
    .string "'YOU FEEL A SENSE OF PRIDE!'$"

