ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "'SHIPWRECK AHEAD!'$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "'DUNGEON TRAP ACTIVATED!'$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "'Eww,Magnitude's aura is getting\p"
    .string "funky!'$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "TO THE EAST, IN SEARCH OF THE\p"
    .string "MISSING ELDER!$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "GOLdeen caught!$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "You found a rare bottle of RED\p"
    .string "Elixir.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "WATER'S DEEP! BE CAREFUL!$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "HELP!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "'SWIMMINGLESSONS AHEAD!'$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "GOLBAT APPEARS!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "You stumble upon a mysterious\p"
    .string "portal.$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "GAME OVER! CONGRATULATIONS, YOU\p"
    .string "DIED!$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "'FOOL! YOU DARE TO APPROACH THE\p"
    .string "CURSED ONE?'$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "YOU WON'T GET RID OF ME SO EASILY!$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "WATER FIGHT?$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "'Professor's Pokedex Charged!'$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "'WELCOME TO LEVEL 2: DARK CAVERN'$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "SEE YOU ON THE NEXT ADVENTURE!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "'BRING. IT. ON!'$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "'Prepare for a battle of\p"
    .string "Trainers!'$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "'MEGA-DEVICE ACTIVATED!'$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "'YEAH, IT WAS TOTALLY RAD!'$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "You've been challenged by MEG!\p"
    .string "What will you do?$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "'POTENTIAL PICKS AHEAD! BE CAREFUL\p"
    .string "FOR THOSE SNEaky SNAKES!'$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "DANGER NEAR! ROAMING BANSHEES!$"

