FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "'ART OF THE WARRIOR UNLEASHED!'$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "'YOU'VE BEEN DEFEATED BY THE DARK\p"
    .string "LORD!'$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "'Get the Colors!' Collect 'em all!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Demands 'Go away, I'm creative!'$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "WARNING: ENERGY LEVEL CRITICAL$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "' PERFECT! NOW, LET'S GET BACK TO\p"
    .string "WORK!'$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "ADJUST SIGHT 3 DEGREES CLOCKWISE$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "ERROR: SYSTEM FAILURE: EMOTIONAL\p"
    .string "MALFUNCTION$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "CATCH THE WHIM OF THE WIND!$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "'SECRET MEETING. INSTRUCTORS\p"
    .string "WAIT.'$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "'FELINE FURY: Opponent Peril\p"
    .string "Rating: X'$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "'Ahoy, Captain Courage!$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "POKEWAVE RISINGAdministrator\p"
    .string "Approves Construction$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "' Warning: Undead hordes\p"
    .string "approaching!'$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "'Your aim is set... Poolside\p"
    .string "Paradise?'$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "Boosting at full speed!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Too hasty, adventurer!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "WHOOOSH! YOU'RE FLYING!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "'Breathe easy, buddy.'$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "'RUTHLESS ROBOT REDNECK ROAMING\p"
    .string "LOOSE!'$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "WHATCHA GONNA DO, BRO?$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "YOU ESCAPE FROM THE TEMPLE.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "'Welcome, Adventurer! Selphy's\p"
    .string "humble abode appears before you.'$"

