Route11_Text_HugoIntro::
    .string "'The Crowd is On the Edge!'$"

Route11_Text_HugoDefeat::
    .string "'Curse ye, fate!'$"

Route11_Text_HugoPostBattle::
    .string "'Enter BIOS to init Pokedex...'$"

Route11_Text_JasperIntro::
    .string "'GET READY TO RUMBLLLL'$"

Route11_Text_JasperDefeat::
    .string "'Gotcha!'$"

Route11_Text_JasperPostBattle::
    .string "BOLDLY FORTH, TRAINER!$"

Route11_Text_EddieIntro::
    .string "'Ye olde map clue: Thar be\p"
    .string "treasure in da nearby caves!'$"

Route11_Text_EddieDefeat::
    .string "Wut? U hed it wrng!$"

Route11_Text_EddiePostBattle::
    .string "YOUR SPIRIT ENDS WITH A SIGH...$"

Route11_Text_BraxtonIntro::
    .string "Laying down cables, eh?$"

Route11_Text_BraxtonDefeat::
    .string "ZAPPED BY ENERGY SURGE!$"

Route11_Text_BraxtonPostBattle::
    .string "'Power Grid Alert: Conservation\p"
    .string "Critical!'$"

Route11_Text_DillonIntro::
    .string "FIGHT START! GO, CHOOSE YOUR PATH!$"

Route11_Text_DillonDefeat::
    .string "'Try reviving one, Trainer!'$"

Route11_Text_DillonPostBattle::
    .string "'GRAH! FEEBLE OLE FARTHER!'$"

Route11_Text_DirkIntro::
    .string "'I shall crush you like the\p"
    .string "insignificant insect you are!'$"

Route11_Text_DirkDefeat::
    .string "'FELL TO DARKNESS'$"

Route11_Text_DirkPostBattle::
    .string "'Not going to rely on luck to win\p"
    .string "this war!'$"

Route11_Text_DarianIntro::
    .string "'LAUNCH CHANCE. WHAT ARE YOU\p"
    .string "WAITING FOR?'$"

Route11_Text_DarianDefeat::
    .string "'FATE IS COMING...'$"

Route11_Text_DarianPostBattle::
    .string "'Rolling a gutter ball... AGAIN!'$"

Route11_Text_YasuIntro::
    .string "FITNESS LEVEL: 80$"

Route11_Text_YasuDefeat::
    .string "Visit Professor Oak's Lab for\p"
    .string "training tips!$"

Route11_Text_YasuPostBattle::
    .string "'A JOLT CATCH!'$"

Route11_Text_BernieIntro::
    .string "'FUSE BOX DAMAGED! CAREFUL\p"
    .string "NodeList: 3'$"

Route11_Text_BernieDefeat::
    .string "CAUTION: Fuel Leak Ahead!$"

Route11_Text_BerniePostBattle::
    .string "TIME'S A-WASTIN'!$"

Route11_Text_DaveIntro::
    .string "Your Pokemon are ready!$"

Route11_Text_DaveDefeat::
    .string "GAME OVER$"

Route11_Text_DavePostBattle::
    .string "WAND WITH 3 MP STRUK$"

Route11_Text_DiglettsCave::
    .string " Rochelle trapped. Diggleton's\p"
    .string "rare crystals stolen!$"

