CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Jackpot Alert!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "CONGRATS, CHIEF!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "BEWARE THE VENDORS$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "YOU SMASH INTO THE WALL!$"

