SixIsland_OutcastIsland_Text_RocketIntro::
    .string "'Prepare to face the wrath of...\p"
    .string "TYPHLOOK!'$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "'WELCOME STRANGER!'$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "'Yeah, I know a guy who knows a\p"
    .string "guy who's got a Squirtle with a\n"
    .string "particularly... fancy shell.'$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "Foul odors emanating from dark\p"
    .string "cave entrance... incoming!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "fortunately, a nearby keycard lies\p"
    .string "nearby$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "'Fishy Fees Freezy Fangs Ahead!'$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "You've arrived at Ember's Edge!\p"
    .string "Tempting treasures within.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "'Whispers echo through the\p"
    .string "void...'$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "'Short on health... need medical\p"
    .string "kit!'$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "Cannot use POKeMON in water!$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "'YOU THINK YOU WON, BUT I KNOW THE\p"
    .string "TRUTH!'$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "'Be careful, stranger, winds of\p"
    .string "fatenblow strong on that isle.'$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "'Enemy Marines Spawned. Launch Bay\p"
    .string "Activated.'$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "'You're mean to be here, but\p"
    .string "beware the lurking threats!'$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "WAVES CRASH AGAINST THE SHORE.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "BRING IT ON!$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "'CHARGE FORTH!'$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "'SAVED CIVILIANS: 15'$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "'FOR SECONDS, YOU'RE A Quinton\p"
    .string "WARRIOR!'$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "Blast 'em, one's enough!$"

