Route14_Text_CarterIntro::
    .string "USE TM20 Ridley Bike$"

Route14_Text_CarterDefeat::
    .string "YOU'VE FOUND A getKey!$"

Route14_Text_CarterPostBattle::
    .string "You got it!$"

Route14_Text_MitchIntro::
    .string "Charlie, yours is too!$"

Route14_Text_MitchDefeat::
    .string "TRY AGAIN LATER!$"

Route14_Text_MitchPostBattle::
    .string "'Visit Professor Rowan's Lab\p"
    .string "Ahead!'$"

Route14_Text_BeckIntro::
    .string "TMs ON SALE!$"

Route14_Text_BeckDefeat::
    .string "OUT OF AMMO$"

Route14_Text_BeckPostBattle::
    .string "Training successful! Taught\p"
    .string "'Ember' to Charmeleon.$"

Route14_Text_MarlonIntro::
    .string "Try: FLUTTER BY SEEDS!$"

Route14_Text_MarlonDefeat::
    .string "Exploding in mid-air...$"

Route14_Text_MarlonPostBattle::
    .string "POKEMON: Pidgey, appears!$"

Route14_Text_DonaldIntro::
    .string "'Rumors whisper they haunt then\p"
    .string "Scorching Dunes of Fallen\n"
    .string "Oasis...'$"

Route14_Text_DonaldDefeat::
    .string "Lucky Shot From Goomba Costs You\p"
    .string "Lives$"

Route14_Text_DonaldPostBattle::
    .string "'Obtain all 3 Winged Mirages:\p"
    .string "ARTICUNO, ZAPDOS, MOLTRES'$"

Route14_Text_BennyIntro::
    .string "You: NOT INTERESTED$"

Route14_Text_BennyDefeat::
    .string "'...the ancient Scroll of Doom was\p"
    .string "hidden here all along!'$"

Route14_Text_BennyPostBattle::
    .string "'The thrum of the world's pulse\p"
    .string "endures.'$"

Route14_Text_LukasIntro::
    .string " GO, GO, GO!$"

Route14_Text_LukasDefeat::
    .string "'Stuck on cursed Isle o' Doom!'$"

Route14_Text_LukasPostBattle::
    .string "'Leave... now, before it's too\p"
    .string "late!'$"

Route14_Text_IsaacIntro::
    .string "ENEMY ENCOUNTER!  Groggi: 20 HP$"

Route14_Text_IsaacDefeat::
    .string "STRANGER IN TOWN$"

Route14_Text_IsaacPostBattle::
    .string "Need more Berries, dude?$"

Route14_Text_GeraldIntro::
    .string "'Holdin' steady, partner?'$"

Route14_Text_GeraldDefeat::
    .string "ENEMIES WIPED OUT!$"

Route14_Text_GeraldPostBattle::
    .string "Ha! computation of stats shows\p"
    .string "your team's edges ahead!$"

Route14_Text_MalikIntro::
    .string "'Pick your 'Mon wisely, trainer!'$"

Route14_Text_MalikDefeat::
    .string "CRASHING TO THE GROUND!$"

Route14_Text_MalikPostBattle::
    .string "BRING IT ON, CHUMP! BETTER BE\p"
    .string "READY!$"

Route14_Text_RouteSign::
    .string "'The city of neon dreams beckons,\p"
    .string "stranger...'$"

Route14_Text_KiriIntro::
    .string "'UNITE, WE FALL!'$"

Route14_Text_KiriDefeat::
    .string "'Fool's errand...'$"

Route14_Text_KiriPostBattle::
    .string "'NO WAY, KIRI! YOU FOUGHT WELL!'$"

Route14_Text_KiriNotEnoughMons::
    .string "WANT TO CHALLENGE?$"

Route14_Text_JanIntro::
    .string "'BURNING FLAMES OF DETERMINATION\p"
    .string "FLARE UP!'$"

Route14_Text_JanDefeat::
    .string "'YOU CHEATED, LARS! NOW IT'S ON!'$"

Route14_Text_JanPostBattle::
    .string "KIRI: sniffles Y-yes, brother...$"

Route14_Text_JanNotEnoughMons::
    .string "SELECT A POKeMON TO FIGHT!$"

