ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "MEMO: Notes: 3/5 Memory Ready$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "CLASS IS TODAY!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Use POKe BALL wisely...$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "'Try paralyzing it!'$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Seeking fellow trainers for\p"
    .string "battles!$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "'Capture the Checkmate'$"

ViridianCity_School_Text_TurnThePage::
    .string " Ancient Tome: 'Danger lurks\p"
    .string "within...'$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "KEEP IT ON THE DOWN LOW, PAL!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "WHAT NOW, TRAINER?$"

ViridianCity_School_Text_ReadWhichTopic::
    .string " Devin has discovered a mysterious\p"
    .string "cave in the dark forests of\n"
    .string "Veridia. Danger lurks within...$"

ViridianCity_School_Text_ExplainSleep::
    .string "AWAKENING? Y/N$"

ViridianCity_School_Text_ExplainBurn::
    .string "GET BURNED! -15 ATK$"

ViridianCity_School_Text_ExplainPoison::
    .string "POISON!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "Thaw out POKeMON with ICE HEAL!$"

ViridianCity_School_Text_ExplainParalysis::
    .string "CURED BY PARALYZ HEAL$"

