SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "'Join us for a voyage of bonding!'$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "'Who's the expert now, eh?'$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "'Growing Pains!'$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "GET READY TO FIGHT, SILLY PUMPKIN!$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "Meet the CUT master.$"

