Route10_Text_MarkIntro::
    .string "'Show me dat Pokemon!'$"

Route10_Text_MarkDefeat::
    .string "WHAT'S GOT YOUR GOAT?$"

Route10_Text_MarkPostBattle::
    .string "'Back to Pallet Town, then?'$"

Route10_Text_ClarkIntro::
    .string "LAUGHING MADNESS DESCENDS UPON\p"
    .string "YOU!$"

Route10_Text_ClarkDefeat::
    .string "You're sneezing uncontrollably!$"

Route10_Text_ClarkPostBattle::
    .string "'scriber sneezes, sending scrolls\p"
    .string "scattering!'$"

Route10_Text_HermanIntro::
    .string "Gotta catch 'em all! Get a peek!$"

Route10_Text_HermanDefeat::
    .string "'.RUN!'$"

Route10_Text_HermanPostBattle::
    .string "YOU DARE CHALLENGE MY DOMINION?$"

Route10_Text_HeidiIntro::
    .string "'Perhaps you just need a stronger\p"
    .string "team...?'$"

Route10_Text_HeidiDefeat::
    .string "'UNLEASH THE FURY!'$"

Route10_Text_HeidiPostBattle::
    .string "INCOMING POKEMON SQUAD!$"

Route10_Text_TrentIntro::
    .string "Fresh mountain springs ahead!$"

Route10_Text_TrentDefeat::
    .string "NO TIME TO DAWdle, ENEMY SPOTTED!$"

Route10_Text_TrentPostBattle::
    .string "'Your lungs ache for relief,\p"
    .string "descend carefully'$"

Route10_Text_CarolIntro::
    .string "CLIMBING BECOMES LABORIOUS$"

Route10_Text_CarolDefeat::
    .string "WAKE UP, SLAYER!$"

Route10_Text_CarolPostBattle::
    .string "You found a FEATHER SEGMENT!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "BOOM! TUNNEL COLLAPSED!$"

Route10_Text_RockTunnel::
    .string "'Watch out for falling rocks!'$"

Route10_Text_PowerPlant::
    .string "' Warning: Reactors critical!\p"
    .string "System failure imminent!'$"

