LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "'Well, welcome to Rivermouth, I\p"
    .string "s'pose...'$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "'Teachers' lounge, probably.\p"
    .string "Again.'$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "'Inert spirit, guide us home.'$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Welcome, young trainer!$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "The Pokemon's warmth wraps around\p"
    .string "you.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "'Geeeeez, NOT again!'$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "A wild Psyduck has appeared!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "'A Pokemon's heart is what truly\p"
    .string "matters...'$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "'Wind-scented treasure!'$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "POKe FLUTE$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "CLEAR PATH!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "NO... I STILL BELIEVE...$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "NO LUCK FOR YOU!$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "'Rumors of new species stirring in\p"
    .string "Viridian'$"

