RockTunnel_1F_Text_LennyIntro::
    .string "'Get ready for the darkest stretch\p"
    .string "of Underground Pass'$"

RockTunnel_1F_Text_LennyDefeat::
    .string "CONGRATULATIONS YOU ACED IT!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string " Beware Onix's deadly gaze!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Dunno which way to go.$"

RockTunnel_1F_Text_OliverDefeat::
    .string "You're in a tight spot. North\p"
    .string "passage looks like a bad idea.$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "Detour! Current location: WARP\p"
    .string "POINTALKAFOREST$"

RockTunnel_1F_Text_LucasIntro::
    .string "'BURN, FURRY!'$"

RockTunnel_1F_Text_LucasDefeat::
    .string "'YOUR WALLET IS EMPTY'$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "'Hike steep ridge. Occtasional\p"
    .string "mist.'$"

RockTunnel_1F_Text_AshtonIntro::
    .string "Charmander uses Ember!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "'Press Enter to continue'$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "GRAAAGH!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Beware the Shadows$"

RockTunnel_1F_Text_LeahDefeat::
    .string "Can't see a thing...$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "WATERY DARKNESS AHEAD!!!$"

RockTunnel_1F_Text_DanaIntro::
    .string "You see a dense forest ahead, the\p"
    .string "trees tall and menacing. Suddenly,\n"
    .string "a wild Pidgey appears before you!$"

RockTunnel_1F_Text_DanaDefeat::
    .string "'PSST! WANT TO BUY A POKE BALL?'$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "'Giant Spiky Behemoth Ahead!'$"

RockTunnel_1F_Text_ArianaIntro::
    .string "Wild Pidgey appears!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "BRUTAL DISMISSAL: Your feeble\p"
    .string "attack is deflected by the enemy's\n"
    .string "stalwart shield!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "'I think I need a drink...'$"

RockTunnel_1F_Text_RouteSign::
    .string "Watch out for stalactites!$"

