CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string " SYSTEM Offline$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "YOU NEED SOME POTIONS!$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "You hear strange noises coming\p"
    .string "from beneath the shop.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Loser's Blues: 'I'd sell my\p"
    .string "soul...'$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "You've Quit the Game!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "COIN CASE FILLED!$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Clearing space...$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "LOOT LOST FOREVER$"

