TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Bring 2 TINYMUSHROOMS, or 1 BIG\p"
    .string "MUSHROOM!$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "SURE THING!$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Eevee's cry for help.$"

TwoIsland_House_Text_TeachWhichMove::
    .string "'TEACH SHORYUKEN TO KEN'...$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "'TEACH IT THE MOVE ALREADY!'$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "A shiny FUNGI appears nearby!$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "Transaction complete!$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "Mysterious Merchant's Offering:\p"
    .string "Extra Life 1$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "'FIND SOME MOSSY TREES'$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "'No way to hone EGG's skills?'$"

