FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "'elda's Briefcases Found!'$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "SWORD DRAWN$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Fly to Four Island NOW!$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "CRASH! Your winged family legacy\p"
    .string "speaks of the skies.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "'BIRD ALERT! FLYING SOUTH FOR\p"
    .string "WINTER'$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "BROODING FIGURE SPOTTED$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "You are BJ, 16, BIRD BROTHER since\p"
    .string "'73$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "'Ah, sleep tight, hero...'$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "CHIRPING JOY GenerationType: 133$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "WEBBED FEET SLATE$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "hp: 75 frontline: SQUIRTLE$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Digging... FOUND!$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "Explore Tectonix's final resting\p"
    .string "place?$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "YES OR NO?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "What a dark and suspicious move...$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "THX FOR THE KINDNESS!$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Your POKeMON seem distressed...$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "'Storage Full. Try Again?'$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "'Gift of Gratitude'$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "DRYING PLATFORM STABLE!$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "OLD TOMBS$"

