Text_UltimateMoveThatMon::
    .string "'You block that STRVAR1 with\p"
    .string "ease!'$"

Text_JustMistaken::
    .string "'NOOO! THE BAZAAR OF SHADOWS HAS\p"
    .string "BEEN DECEIVED!'$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Will you allow your Squirtle to\p"
    .string "learn my Hydro Pump?$"

Text_YouRejectIt::
    .string "THEY SHOUT IN DEFiance!$"

Text_LetMeConferUltimateMove::
    .string "Will I?!$"

Text_TaughtMove::
    .string "'Worthless! Prepare to meet your\p"
    .string "maker!'$"

Text_MakeBestUseOfMove::
    .string "USE THROW WITH CARE!$"

Text_PassedOnEverythingIKnow::
    .string "'Until our lights fade...'$"

Text_FeelRejuvenated::
    .string "Your mentor's eyes glow with\p"
    .string "wisdom...$"

