Route1_Text_WorkAtPokeMartTakeSample::
    .string "You got 10 Poke Balls and 5\p"
    .string "Potions!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "ebp. Professor Elm's Lab$"

Route1_Text_PutPotionAway::
    .string "'POTION SECURED!'$"

Route1_Text_CanJumpFromLedges::
    .string "CAUTION: Ledges ahead.$"

Route1_Text_RouteSign::
    .string "Welcome to Route 1. A long stretch\p"
    .string "of road ahead. Where will you\n"
    .string "journey next?$"

