PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "'Welcome to Serenity's Haven!'$"

PokemonTower_5F_Text_TammyIntro::
    .string "USE CARD: ALAKAZAM$"

PokemonTower_5F_Text_TammyDefeat::
    .string " stalwart hero, beware the\p"
    .string "treacherous swamp of darkness\n"
    .string "ahead!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "'MIND CONTROL ACTIVATED!'$"

PokemonTower_5F_Text_RuthIntro::
    .string "The adventure begins...$"

PokemonTower_5F_Text_RuthDefeat::
    .string "ZOMBIES AHEAD!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "'You've been consumed by the dark\p"
    .string "force...'$"

PokemonTower_5F_Text_KarinaIntro::
    .string "' warning: undead horde\p"
    .string "approaching!'$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "'Stats Boost Ahead!'$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "You find yourself in the Forsaken\p"
    .string "Cave, the eerie silence broken\n"
    .string "only by the distant sound of\p"
    .string "dripping water.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "onga Warning System Malfunction$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "'WELCOME TO ADVENTURE ISLAND!'$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Curses consumed my soul.$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Congratulations!$"

