Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "'Ahah, a fellow angler!'$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "Let's hook some fins and swap\p"
    .string "stories!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "'A FIN-tastic catch awaits!'$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "CATCH BIG MAGIKARP WITH ROD?$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "'Sorry, no choice here'$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Try using the SUPER ROD!$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "YOU'VE ONLY GOT ONE FLAIL FISH!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "You receive a 'Linguistic Lure'!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "'TIME TO SET THE RECORD STRAIGHT!'$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "What is this, a minigun?! 4 inches$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "This one is 5 inches long. It\p"
    .string "doesn't measure up to the 10-inch\n"
    .string "one you brought before.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "WEAK AGAIN.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "NO COIN STORAGE!$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "WATER- TYPE BEAST 300 INCHES!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "CRIME LOG$"

