CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "WHERE WILL YOUR JOURNEY TAKE YOU?$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "'Ah ha! Caught myself an eevee!\p"
    .string "what'll I do with ya, little guy?'$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "'BOX FULL! SWITCH NOW!'$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "'Connect device, professor...'$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "EXPLORER'S LORE$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "Pokemon Wireless Club Membership\p"
    .string "Available Upstairs$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "Pokemon Wiress Club, DIR?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "UNION ROOM.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Obtained TM: .grp x Table-Splitter$"

