CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "Lucky spin: 30 CLOCK HOURS$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "'MONDAY'S GOLD: 10,000 GEMS'$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "'Acquire the Coin Case from the\p"
    .string "Shopkeeper in town for 500 gold\n"
    .string "coins.'$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "'Prize Box: 50 COINS'$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "Golden Power-Up Token$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "LOCKED DOOR: FIND KEY$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "'We found yours!'$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "YES$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "JUST 50 LEFT TO GO!$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "Your customer's tapped out!$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "'Ah ha! Gotcha!'$"

