SixIsland_PatternBush_Text_BethanyIntro::
    .string "USE ITEMS OR LEVEL UP IN BATTLES!$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "' ARE YOU SURE, TRAINER?'$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "'Believe in yourself, Trainers!'$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "WEST REGION CHIEF RESEARCHER$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "YOU'RE A REAL FIGHTER!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "POKE'MON TRAINERS UPGRADE NETTING\p"
    .string "SPARKING TURMOIL$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "'O? Find! That's Weedle!'$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "WOOHOO! Your Charmander's Blazing\p"
    .string "Form is looking FIERCE!$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "'Measure up for trainers, girl!'$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "BUG BEETLE DEPLOYED!$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "'Better luck next time, Trainer!'$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "PARADOX ENUMERATED$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "FOUND: Glitter Co., Bukotal\p"
    .string "Commonwealth, Instructor.: You\n"
    .string "encounter Buzzi, a wild Grand Buzz$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "'NOOOO!Back to the start you go!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "'BROTHER COMING SOON!'$"

SixIsland_PatternBush_Text_NashIntro::
    .string "PATTERN FRIEND FOUND!$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "'YOU'VE FOUND THE HIDDEN\p"
    .string "TREASURE!'$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "'WONDERFUL TRAILBLAZE\p"
    .string "OTPAINTINGS!'$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "YOU KILLED MY FATHER?!$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "'Bring it on, pal!'$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Hand it over, city slicker!$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Typical Llama Forge spring\p"
    .string "morning.$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "'BREATHE DEEP, WARRIOR!'$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "A breath of fresh air!$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "You found a CARIBEN bug, friend!$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "MISSING IN ACTION$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "You've got a Bug Badge!$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "'Camp Established.'$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "BROKEN SPIRIT$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "'Celestial bodies align overhead.\p"
    .string "Strange symbols etched in\n"
    .string "stars...'$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "You sting! -4 HP$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "OW! FALLEN ON GLASSY SLOPE$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string " Fix Bat Spray?$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Strategic component suspected\p"
    .string "faulty. Check records.$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "'You're stuck!'$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "'Mysterious energies emanate from\p"
    .string "ancient stones buried beneath the\n"
    .string "earth.'$"

