SilphCo_10F_Text_GruntIntro::
    .string "Welcome, adventurer.$"

SilphCo_10F_Text_GruntDefeat::
    .string "'BLOCKADE BREACHED! ENEMY ARMY\p"
    .string "APPROACHES!'$"

SilphCo_10F_Text_GruntPostBattle::
    .string "'Be careful, rival corp. agents\p"
    .string "nearby'$"

SilphCo_10F_Text_TravisIntro::
    .string "YOU DARE TO MOCK ME?!$"

SilphCo_10F_Text_TravisDefeat::
    .string "OUT OF CONTINUES$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Walk away, chump!$"

SilphCo_10F_Text_WaaaImScared::
    .string "'ROAMING CREATURES DETECTED 300 FT\p"
    .string "E!'$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "Your tears are safe with me$"

SilphCo_10F_Text_FloorSign::
    .string "Entrance Hall: Keycard Required$"

