SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "You're mocking me? That's my line!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "You think I'm weird?$"

Text_MimicTeach::
    .string " charm charm! MIMIC LEARNED!$"

Text_MimicDeclined::
    .string "'TREACHEROUS ILLUSION?'$"

Text_MimicWhichMon::
    .string "'YOU'RE NEXT!'$"

Text_MimicTaughtMale::
    .string "You're being mimicked again?$"

Text_MimicTaughtFemale::
    .string "'You'll be echoing the leader!'$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "'Treasure Trove FOUND! 10 gold\p"
    .string "coins!'$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "YOU: What's up, pal?$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "WATShai Ling ',?$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "New challenger? Dares thou take on\p"
    .string "the Dreaded Beauty?!$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "'Fake Mon!? Bizarre!'$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "WATER LOGGED MARIO FINDS KEY$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "'Ah, a kindred spirit! Want to\p"
    .string "trade secrets?'$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "'Whispers in the Dark: Gone!'$"

