PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "YOU SHOULDN'T HAVE GONE!$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "You've arrived at Prof. Oak's\p"
    .string "house!$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "'Too tired to continue... Zzz...'$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "You got a call from MOM!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "'A Long Way Home?'$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "??!You can't miss this!$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "ERROR!$"

