LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "POK-emon?!$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "'RHYDON?'$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "Y/N?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Enter new moniker:$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "DONE! Starlight$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "'WELCOME TO Yog's Cave'$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "From now on, this POKEMON shall be\p"
    .string "known as RAZORFLAME!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "Young Adventurer, it is Hero!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "What's crackin'!$"

