RocketHideout_B3F_Text_Grunt1Intro::
    .string "You'll pay for your INSOLENCE!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "YOU'VE BEEN DEFEATED!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "Find SILPH SCOPE in underground\p"
    .string "tunnels!$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "'OH NO! THE BOSS'S MEN ARE\p"
    .string "WAITING!'$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "GAME OVER: Health 0$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "ROOM 45, LIFT KEY NOT FOUND...$"

