SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "'Study this chart, Trainer!'$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "crony info leaked to NEST$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "'ELITE FORCE APPROACHING!'$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "MISSION CLEAR!$"

