Route16_House_Text_FoundMySecretRetreat::
    .string "'Treasure of the Ancients: 1000\p"
    .string "Gold Coins!'$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "You got the HM02!$"

Route16_House_Text_ExplainHM02::
    .string "USE HM02 FLY$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "'ROOM FULL - MOVE TO NEXT'$"

Route16_House_Text_Fearow::
    .string "urses and pales at the sight!$"

