PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "Etched stone: 'RIP: 151 POKeMON'$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "No, I'm here for the legendary\p"
    .string "trainers' guild. Heard great\n"
    .string "things about their battling\p"
    .string "prowess.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "What brings you to our humble HQ?$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Say a Hail Mary$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "FATALITY: Lost 15 HP. Injury:\p"
    .string "Weakened.$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "'UNCOVER THE MYSTERY... TOO HIGH\p"
    .string "FOR MORTALS'$"

