FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "'Warning: Warden SLOWPOKE spotted\p"
    .string "in the corridors!'$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "'Ah, a young trainer, eh? I can\p"
    .string "show you some old bones...'$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "'Wha' ya mean ya ain't\p"
    .string "t'understand?!'$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "Congratulations! You made it to\p"
    .string "the top!$"

