Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "'STRATEGY TIP: Study type matchups\p"
    .string "to triumph!'$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "'You've received Y5000'$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "'The veil between worlds is thin\p"
    .string "here...'$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "'Been wantin' to meet ya, kid!'$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "WOOHOO!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "Power of the ancient stone\p"
    .string "coursing through thy veins!$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Give EVERSTONE to POKEMON to\p"
    .string "prevent evolution.$"

