CeruleanCity_Text_RivalIntro::
    .string "You pitiful trainer, still\p"
    .string "catchingn weeds and rejects, eh?$"

CeruleanCity_Text_RivalDefeat::
    .string "Congratulations SAVIOR OF LIGHT!\p"
    .string "You have claimed victory!$"

CeruleanCity_Text_RivalPostBattle::
    .string "Meet me at BILL's and thank him\p"
    .string "for the POKeMON Storage System!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "'Gotcha! stab'$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "You scoff at the juicer: 'Think\p"
    .string "you're too cool for this fancy\n"
    .string "contraption, huh?'$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "Foolishness won't save you now!$"

CeruleanCity_Text_GruntIntro::
    .string "What are you gonna do, punk? Bring\p"
    .string "it on!$"

CeruleanCity_Text_GruntDefeat::
    .string "YOU DARE NOT LEAVE!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "'Recovering stolen goods... Not a\p"
    .string "good idea.'$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "'Trainer's Package Recovered!'$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "THE JOURNEY BEGINS NOW!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Take Key from corner store, will\p"
    .string "open door!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "'Yeah, but it's the only one I\p"
    .string "know!'$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "You found a CLEVER WAY '''$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Find sharp rock to deflect\p"
    .string "SLOWBRO's gaze.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "Loading...  ENCYCLOPEDIA: POKemon\p"
    .string "DATA   STATUS: WORK-IN-PROGRESS$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "You must stop the thieves!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "BOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "'GUARD POST 3 SECS AWAY!'$"

CeruleanCity_Text_SlowbroPunch::
    .string "'Thump!'$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "GAME OVER$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "RETREATING TO CAVE ENTRANCE,\p"
    .string "SLOWBRO!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "WEAK TRAINER!$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "Zzz... TOO LATE!$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "'Totally chill, dude.'$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "EVASIVE MOVES EFFECTIVE!$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "RUNNING WILD! DEFAULT TO DEFEND.$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "You've found a Chrome Red\p"
    .string "Roadster!$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "You are now entering the CERULEAN\p"
    .string "CAVE.$"

CeruleanCity_Text_CitySign::
    .string "STRANGENESS IN THE AIR...$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "'What to hold?'$"

CeruleanCity_Text_BikeShopSign::
    .string "'New Wheels Ahead!'$"

CeruleanCity_Text_GymSign::
    .string "BET YOU CAN'T CATCH ME!$"

