CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "'My trusty road warrior awaits'$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "NOT ENOUGH CREDITS!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "You've got a brand new bike, bro!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "You now ride a reliable bicycle.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Mission Accomplished. Saving the\p"
    .string "world...$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "WE fautined 100CP for crit!/p$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "BICYCLE BARRIERS AHEAD!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "'A practical choice, no doubt.'$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "BUSTING OUT YOUR PIGGY BANK!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "BIKE STATS$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "'TD-1 ESCAPES ENEMY FIRE!'$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "Found! 'You got a shiny new\p"
    .string "bicycle!'$"

