FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "'Break free the adventurous herd'$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "You hear faint whispers in the\p"
    .string "darkness...$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "' Warning: Trainers claim to have\p"
    .string "seen ESCAPE PODS onboard!'$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "'SAUCY HABIT! STOP RIGHT THERE,\p"
    .string "CYBORG!'$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "Earth, bthar!$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "'Ready when you are, trainer!'$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "'Whoa, back off, partner!'$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "'GET CASH 4 ur POKE!'$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "'What'cha doin' here, punk?'$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "'HA! YOU'LL BE TALKIN' WITH A COLD\p"
    .string "SWORD IN YA FACE!'$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "'Blast ye, begone, and trouble me\p"
    .string "no more!'$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "FAITH IN GIOVANNI$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Treacherous fate cruelly befell\p"
    .string "thee!$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "'A true hero emerges!'$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "'Ah, good planning!'$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "'You're gonna pay for this, kid!'$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "NOOOO! IT'S ALL OVER NOW...$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "WIRETAP TRANSMISSION DETECTED...$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "REQ: Analyze Data.$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "'YOU SABOTEUR!'$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "'Arrgh! Not Again!'$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "You've got a lousy deal!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Foes lurk in the shadows, waitin'\p"
    .string "to strike!$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "WHO R U?!$"

