CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "DEPT. STORE FLOOR PLAN   Clothing:\p"
    .string "2F  Furniture: 3F  Antiques: B1\n"
    .string "Accessories: 1F$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "Getting supplies from service\p"
    .string "counter.$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "-prop-prop: HP 20, MP 5$"

