@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "PASSWORDS goalturret AND citygate$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "'ATTENTION authorizednpersonnel\p"
    .string "only'p$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "You see CHANSEY inside.$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "You step inside, crates scattered\p"
    .string "everywhere.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "'ACCESS DENIED'$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "STRANGLER'S LAIR AHEAD!$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "'Leave me be, puny stranger!'$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "You're just in time!$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "INVESTIGATE THE SOURCE$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "Dusty crates scatter the floor.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "'Ain't happenin' pal...'$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "'ArrayOfGhosts Enters the Fray!'$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "Access Denied!$"

