CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "POKeMON: 3E4338 OT: NAME$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "TRADE CONFIRMED!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "'WHAT!?'$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "ID: 001$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "'The abandoned temple beckons...'$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "'Hordes of Gorthok approach,\p"
    .string "battle imminent!'$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "'Kickoff in 30 seconds'$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "SOLVE THE XYLOPHONE OF DOOM TO\p"
    .string "UNLOCK NEXT LEVEL!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "YOU READY FOR THIS?!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "'Shopkeeper: Latest games cheap!\p"
    .string "Score high! 5000 units unclaimed!'$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "'Choose one or switch!$"

Text_CounterTeach::
    .string "Teach me, I'll learn$"

Text_CounterDeclined::
    .string "STRANGER AT THE TAVERN$"

Text_CounterWhichMon::
    .string "Try Slyveon. Its Normal/Psychic\p"
    .string "mix could help its stat boosts\n"
    .string "stand strong against foes!$"

Text_CounterTaught::
    .string "'Ha! Not smart enough, Trainer!'$"

