Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "PROF. OAK'S AIDE: Got 95 / 100\p"
    .string "kinds of POKeMON$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "WOOHOO!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "You received the Map Fragment from\p"
    .string "the Crying Oracle.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "'ITEMFINDER: ISSUED. FINE-TUNE\p"
    .string "YOUR SEARCH.'$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Squirtle appear to be slumbering\p"
    .string "heavily...$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "A mysterious cave lies below,\p"
    .string "beckoning you to explore its\n"
    .string "depths.$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "A tunnel through the rocks!$"

