Route13_Text_SebastianIntro::
    .string "FEATHERED FURY APPROACHING!$"

Route13_Text_SebastianDefeat::
    .string "NO WAY!$"

Route13_Text_SebastianPostBattle::
    .string "'Their spirits remain unbroken!'$"

Route13_Text_SusieIntro::
    .string "WANTED FOR QUESTIONING$"

Route13_Text_SusieDefeat::
    .string "GAME OVER! TRY AGAIN?$"

Route13_Text_SusiePostBattle::
    .string "TRAINING FIEND HAS ARRIVED!$"

Route13_Text_ValerieIntro::
    .string "'BADGES ROCK!'$"

Route13_Text_ValerieDefeat::
    .string "OUT OF CREDITS!$"

Route13_Text_ValeriePostBattle::
    .string "BADGE COLLECTION GOALS!$"

Route13_Text_GwenIntro::
    .string "Meet your new friends!$"

Route13_Text_GwenDefeat::
    .string "VICTORY IS YOURS!$"

Route13_Text_GwenPostBattle::
    .string "'BEGIN BATTLED LIST...'$"

Route13_Text_AlmaIntro::
    .string "'Carbos Documents Found. Proceed\p"
    .string "with Caution.'$"

Route13_Text_AlmaDefeat::
    .string "GAME OVER$"

Route13_Text_AlmaPostBattle::
    .string "WOOHOO!$"

Route13_Text_PerryIntro::
    .string "The daredevil spirit burns bright!$"

Route13_Text_PerryDefeat::
    .string "Windswept draught now blows in dra$"

Route13_Text_PerryPostBattle::
    .string "'Your wings are yours once more!\p"
    .string "proceeding...'$"

Route13_Text_LolaIntro::
    .string "YOU'VE REACHED THE ABANDONED\p"
    .string "MINING TOWN. BEWARE OF THE SHADOWY\n"
    .string "FIGURES LURKING IN THE NIGHT.$"

Route13_Text_LolaDefeat::
    .string "Run!$"

Route13_Text_LolaPostBattle::
    .string "DATA ANALYSIS pending... Type\p"
    .string "MATTER neutralize TYPE ADVANTAGE!$"

Route13_Text_SheilaIntro::
    .string "The cave is dark and eerie.$"

Route13_Text_SheilaDefeat::
    .string "'IT SEEMS THE CURSE WAS TOO MUCH\p"
    .string "FOR YOU!'$"

Route13_Text_SheilaPostBattle::
    .string "A Fierce Pigeot waits!$"

Route13_Text_JaredIntro::
    .string "MIND CONTROL RELAY IN VIEW$"

Route13_Text_JaredDefeat::
    .string "'GREY AREA CONTAMINATED'$"

Route13_Text_JaredPostBattle::
    .string "'Peaceful Oasis Ahead. Danger\p"
    .string "Brewing!'$"

Route13_Text_RobertIntro::
    .string "'You're a true Birdkeeper, eh?'$"

Route13_Text_RobertDefeat::
    .string "'GET ENERGIZER!'$"

Route13_Text_RobertPostBattle::
    .string "'WOBBLE WOBBLE!'$"

Route13_Text_LookToLeftOfThatPost::
    .string "Examine Post!$"

Route13_Text_SelectToSwitchItems::
    .string "Use L1 to switch items.$"

Route13_Text_RouteSign::
    .string "North of Silence Bridge: MOUNTAIN\p"
    .string "PASS$"

