VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Train hard, battler!$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "'POISONED! POKEMON FAINTED!'$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "'Mastering type matchups key to\p"
    .string "success.'$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "'Battlin' the ghosts of the past?'$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Battery found! 1/4 charged.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "Beep-beep-beep!$"

