ViridianCity_Text_CanCarryMonsAnywhere::
    .string "'Pokemon 025: Sandshrew'$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Leader: MALAMICS$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "'Falkner's Fiery Flare'$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "'Metapod's armored shell won't\p"
    .string "break'$"

ViridianCity_Text_OhOkayThen::
    .string "' Warning: Creepy Floor Ahead!'$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "'Beware WEEDLE's POISON STING!'$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "GRANDMA'S CRYING ONCE MORE...$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "You found a rare Scalpel.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "ACCESS DENIED$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "'Ah, show me how, pleeease?'$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Urgh! Sneering Thief Attacks!$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "THAT POKE BALL IS MINE$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "'Ow, head's spinning! Think I need\p"
    .string "some water...'$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "You're heading out, but coffee's\p"
    .string "got you down?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "'Learn from the young master?'$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "LOGGING OFF. TEACHY TV ON HOLD.$"

ViridianCity_Text_CitySign::
    .string "Welcome to Viridian City, where\p"
    .string "the tropical sun shines bright!$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "Gotta catch 'em all!$"

ViridianCity_Text_MovesLimitedByPP::
    .string "REST POKEMON AT CENTER.$"

ViridianCity_Text_GymSign::
    .string "BATTLE LEADER BROCK AWAITS$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "'DOOR SEALED BY RECTOR!'$"

