@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "'Your Charmander won't know what\p"
    .string "hit it!'$"

Text_BodySlamDeclined::
    .string "' NO SERVICE HERE!'$"

Text_BodySlamWhichMon::
    .string "GRIFFIN$"

Text_BodySlamTaught::
    .string "Error 47: Malfunction detected.\p"
    .string "Power conduit damaged.$"

FourIsland_House1_Text_FatMan::
    .string "YOU FOUND THE FARM!$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Glint$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "'Eggs-traordinary! A POKeMON EGG\p"
    .string "here!'$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "MISSING JOURNAL!$"

