CeruleanCity_House4_Text_NothingEntertaining::
    .string "'Boredom Alert! Find Adventure\p"
    .string "Nearby?'$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Well done, young journalist!\p"
    .string "Here's a special reward: 'Rare\n"
    .string "WWII Memoir'$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "SURPRISE NEWS Some kids found a\p"
    .string "SECRET PATH in the forest!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "'Secrets revealed to worthy\p"
    .string "ally...'$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Congratulations! You received 300\p"
    .string "gold coins!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "Rumors spreading fast!$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "You've Got A Date With Destiny$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Berry Pouch: v 0/9$"

