VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
    .string "Do you have a sword?$"

VermilionCity_House2_Text_ThatsTooBad::
    .string "YOU SMELL DEFEAT$"

VermilionCity_House2_Text_ThisIsNoMon::
    .string "Rare Ancient Scroll$"

VermilionCity_House2_Text_ThankYou::
    .string "WEARINESS SETS IN FROM LONELY\p"
    .string "JOURNEY$"

VermilionCity_House2_Text_HowIsMyOldMon::
    .string "How is your old grandmother?p My\p"
    .string "sword is doing great!$"

