CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "FUMING!$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "What a discovery!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "'CHAOS IN OUR STREETS!'$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "YOU'VE GOT 50 COINS LEFT$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "ALLEGIANCE STRONG$"

CeladonCity_Text_Poliwrath::
    .string "'You've encountered a Poliwrath!\p"
    .string "What will you do?'$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "'YOU THINK YOU'RE TOUGH, HUH?'$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "'ROCKET GRANITE ahead: Danger\p"
    .string "Zone!'$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "USE X ACCURACY NOW$"

CeladonCity_Text_CitySign::
    .string "You see Professor Oak, PE trainer.$"

CeladonCity_Text_GymSign::
    .string "'Erika's Garden Awaits!'$"

CeladonCity_Text_MansionSign::
    .string "'SAFETY REMOTE SIGNAL LOST'$"

CeladonCity_Text_DeptStoreSign::
    .string " badly needed goods ahead!!!!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "'TRY GUARD SPEC. FOR PROTECTION\p"
    .string "DS'$"

CeladonCity_Text_PrizeExchangeSign::
    .string "BORROW 50 COINS FOR A SHINY SHIELD$"

CeladonCity_Text_GameCornerSign::
    .string "' BOOSTER READY, TRANS-LUNAR\p"
    .string "LAUNCH IN 3... 2... 1... '$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "'Oww, tea's burning my tongue!\p"
    .string "Whoops!'$"

Text_SoftboiledTeach::
    .string " Learn SOFTBOILED! press B to copy$"

Text_SoftboiledDeclined::
    .string "It seems a shadow lurks nearby...$"

Text_SoftboiledWhichMon::
    .string "TURTLE RELAX$"

Text_SoftboiledTaught::
    .string "'Brick Fortress ahead! Watch out\p"
    .string "for Laser Turrets!'$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Seek the TRAIL.$"

