ViridianCity_Mart_Text_YouCameFromPallet::
    .string "YE begin yer journey here!$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "-Accept Order-$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "Important Package Obtained!$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "A STRANGE CREATURE HAS BEEN\p"
    .string "SPOTTED IN THE WILD!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "'Ah, fresh stock of 'Potion of\p"
    .string "Revival' in today!'$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "POTION SHOP  5 Potions for 50\p"
    .string "PokeDollars$"

