VermilionCity_Gym_Text_LtSurgeIntro::
    .string "'You're no match for my Electric\p"
    .string "might, kid!'$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "You won't electrify Rockoky!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "YOU'VE GOT THE THUNDERBADGE! SPEED\p"
    .string "BOOST ACTIVATED!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "'TEACHES FLASH CANNON!'$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "LEARNED!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Space Available: 2 Slots$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "'YOU'VE GOT THE POWER!'$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "'REPORT FOR DUTY, SOLDIER! LT.\p"
    .string "SURGE IS WAITING!'$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "'LAUNCH FAILED... TRY AGAIN!'$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "Caution...recommended$"

VermilionCity_Gym_Text_BailyIntro::
    .string "'ZAP! Electro-Power Harnessed!'$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "'HA! YOU'RE MEAT NOW!'$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "'Check crates wisely, she warned'$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "You're in trouble, buddy!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "EXCLAMATION OF HORROR!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "'Try double-retreating.'$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Meet Lt. Surge, the Lightning\p"
    .string "American!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "'ARE YOU READY FOR THE NEXT\p"
    .string "ROUND?!'$"

VermilionCity_Gym_Text_GymStatue::
    .string "Defeat Lt. Surge to prove\p"
    .string "yourself!$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "You face Lt. Surge, Vermillion Gym\p"
    .string "Leader!$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "NOTHING BESIDES DIRT$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string " FOUND KEYCARD IN LOCKER!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "Gotcha! You Found Switch Pt. 2!$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "You gained access to the\p"
    .string "restricted area!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "ACCESS GRANTED$"

