FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "'Gorilla spotted in proximity.\p"
    .string "Danger level: Medium!'$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "YES$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "Sorry, mate!$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "BALL CHAIN NOW 30$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Timer's ticking!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "You're Trapped!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "NOT ENOUGH GP!603 GULDEN NEEDED$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "'Definitely, giant mutant crocs\p"
    .string "aren'tn worth the T-shirt...'$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "You found 3 SAFARI BALLS.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "You're first objective is to\p"
    .string "rescue the village from the\n"
    .string "clutches of evil.$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "15 fish, 20 shells, and a rare\p"
    .string "pearl!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "BEWARE! HOSTILES AMONG US!$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "Enter Safari Zone..Num Safari\p"
    .string "Balls: 5. Time Limit: 10 minutes.$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "YOU'VE ENTERED A SEEDY UNDERGROUND\p"
    .string "CLUB$"

