SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "WHAT IN THE WORLD...$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "The legendary TRAINER, PLAYER has\p"
    .string "arrived!$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Ready to rumble?$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "'Bring it on, challengers!'$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "'It's that punk Julian!'$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "WAT YOU EXPERIENCING, HERO?$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "'Those kobolds won't know what hit\p"
    .string "'em!'$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "WATERMARK NOT FOUND$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "It's Turbo Time!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "You found Brock's Fan's Overalls!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "You shout your strong sentiments!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "You've got a thing or two to learn\p"
    .string "from this 'tough-guy' Brock's got\n"
    .string "skills, and attitude to match!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "You got a fan? Cool!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "SUMMON YOUR INNER STRENGTH!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Or merely seeking TREASURE?!$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "What skills you lack....$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "You've got the makings of a\p"
    .string "champion!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "Can't let him get away!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "FANgirl's Overjoyed!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "YOU SHOULD FOCUS ON YOUR\p"
    .string "TRAINING,Psi-Girl!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "'Believe in yourself, always!'$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "STRIVE FOR GREATNESS IN THE WORLD\p"
    .string "OF POKEMON!$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Enemy: Shady Scouter$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "YOU'VE GOT ONE DEVOTED FAN LEFT!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "Meeting STRVAR1? Yeaah, dat'd be\p"
    .string "sweet!$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Playing as the Legendary Fan$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string " meetup meetup spot Sheffield Sq.\p"
    .string "await!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Hurray, hurray, YOU!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "STRVAR1: Ryker$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "You're quite the sensation, aren't\p"
    .string "ya?$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "'Wow, you're one tough COOKIE!'$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "'Awaken Your Passion!'$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "'Hisceys, a lady of refinement,\p"
    .string "join me!'$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "I believe in Master Echo$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "You've got a real.Exporter on your\p"
    .string "hands!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "'IN YOUR FACE, MASTER!'$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "INCREASING INTENSITY IN THE DOJO!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "'FIGHT FOR MASTER'S HONOR!'$"

