Route8_Text_AidanIntro::
    .string "'Don't worry 'bout that, gotta\p"
    .string "catch 'em all!'$"

Route8_Text_AidanDefeat::
    .string "'BURN BULLETIN:  Critical Thermal\p"
    .string "Overload!'$"

Route8_Text_AidanPostBattle::
    .string "'You're not exactly proficient\p"
    .string "in... algebra yet.'$"

Route8_Text_StanIntro::
    .string "WELCOME TO 'QUEST FOR GLORY'$"

Route8_Text_StanDefeat::
    .string "OBJECT NOT IN RANGE!$"

Route8_Text_StanPostBattle::
    .string "Systems malfunctioning...$"

Route8_Text_GlennIntro::
    .string "Are you ready for the CHALLENGE?$"

Route8_Text_GlennDefeat::
    .string "ILLOGICAL BIZARRENESS DETECTED!$"

Route8_Text_GlennPostBattle::
    .string "The cyclopean horrors await!$"

Route8_Text_PaigeIntro::
    .string "Find ing three Nidoran in the\p"
    .string "cave!$"

Route8_Text_PaigeDefeat::
    .string "Cursed temple's strange energy\p"
    .string "disrupts my mind.$"

Route8_Text_PaigePostBattle::
    .string "'BUT WAIT! GROWTH IS KEY!'$"

Route8_Text_LeslieIntro::
    .string "'CHOOSE YOUR POKeMON CAREFULLY!'$"

Route8_Text_LeslieDefeat::
    .string "You're being led astray by the\p"
    .string "streets! Return to campus, young\n"
    .string "one.$"

Route8_Text_LesliePostBattle::
    .string "LEFT GATE WON'T BUDGE. WHY?!$"

Route8_Text_AndreaIntro::
    .string "Wilburn captures MEOWTH!$"

Route8_Text_AndreaDefeat::
    .string "'WALKING CATBEAST APPROACHES!'$"

Route8_Text_AndreaPostBattle::
    .string "You discovered a wild 24 Rattata!$"

Route8_Text_MeganIntro::
    .string "'Repeat syllables to dispel\p"
    .string "confusion!'$"

Route8_Text_MeganDefeat::
    .string "'Your Poke Ball malfunctioned!'$"

Route8_Text_MeganPostBattle::
    .string "'Talk to the gatekeeper, he\p"
    .string "seems... skeptical.'$"

Route8_Text_RichIntro::
    .string "'Cursed Temple Ahead!'$"

Route8_Text_RichDefeat::
    .string "FORTUNE SLIPS THROUGH YOUR FINGERS$"

Route8_Text_RichPostBattle::
    .string "YOUR ADDICTION KNOWS NO BOUNDS!$"

Route8_Text_JuliaIntro::
    .string "CHARMANDER$"

Route8_Text_JuliaDefeat::
    .string "'BACK OFF, GYM LEADER!'$"

Route8_Text_JuliaPostBattle::
    .string "GOTCHA!$"

Route8_Text_UndergroundPathSign::
    .string "'Continue north to Lavender Town?'$"

Route8_Text_EliIntro::
    .string "'DUAL ENERGY GENERATORS ONLINE!'$"

Route8_Text_EliDefeat::
    .string "'BUT WAIT! MAGNETIC FUSES\p"
    .string "FAILING!'$"

Route8_Text_EliPostBattle::
    .string "'Pokemon caught!'$"

Route8_Text_EliNotEnoughMons::
    .string "'BATTLES NOT POSSIBLE. PLEASE\p"
    .string "SELECT TWO POKEMON.'$"

Route8_Text_AnneIntro::
    .string "'TWIN STORM COMING!'$"

Route8_Text_AnneDefeat::
    .string "UNLEASHED!$"

Route8_Text_AnnePostBattle::
    .string "'Great minds think alike!'$"

Route8_Text_AnneNotEnoughMons::
    .string "BRING YOUR STRONGEST PAIR!$"

Route8_Text_RicardoIntro::
    .string "'Broke Spoke: Confirmed. Fix or\p"
    .string "Replace?'$"

Route8_Text_RicardoDefeat::
    .string "You're not ready for this fight.$"

Route8_Text_RicardoPostBattle::
    .string "'Stuck in the weeds!'$"

Route8_Text_JarenIntro::
    .string "GET OUT OF DOCKING BAY 94!$"

Route8_Text_JarenDefeat::
    .string "RENEGADE TUNNEL LOW-LEVEL DAYCYCLE\p"
    .string "RAID$"

Route8_Text_JarenPostBattle::
    .string "'You're no hero, kid.'$"

