ViridianCity_House_Text_NicknamingIsFun::
    .string "'PLAYER TAGS: ENTER NEW HANDLE...'$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Your dad's a Pokemon fanatic, eh?\p"
    .string "Better grab his Pokedex!$"

ViridianCity_House_Text_Speary::
    .string "'Beware, SPEARY raids nearby! 300\p"
    .string "HP'$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "'Flys at 30MPH, 1HIT 10DMG'$"

