SilphCo_3F_Text_WhatAmIToDo::
    .string "Investigate the strange energy\p"
    .string "readings at Viridian City!$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "THANK YOU, HERO!$"

SilphCo_3F_Text_GruntIntro::
    .string "'Not so fast, punk!'$"

SilphCo_3F_Text_GruntDefeat::
    .string "YOU GIVE UP TOO EASY!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "CARD KEY NOT FOUND$"

SilphCo_3F_Text_JoseIntro::
    .string "'You're making a big mistake!'$"

SilphCo_3F_Text_JoseDefeat::
    .string "YOU'RE OUT OF LUCK, PAL!$"

SilphCo_3F_Text_JosePostBattle::
    .string "'But why should I trust you?'$"

SilphCo_3F_Text_FloorSign::
    .string "TEMPORARY Boundary Check Failure$"

