PalletTown_Text_OakDontGoOut::
    .string "KILLER GOBLINS ROAM THE STREETS$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "You've been warned...Bulkcek!$"

PalletTown_Text_RaisingMonsToo::
    .string "'YOUR TRUSTY COMPANIONS WAIT!'$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "'Storage Accessory Installed'$"

PalletTown_Text_OakPokemonResearchLab::
    .string "WELCOME, TRAINER!$"

PalletTown_Text_PlayersHouse::
    .string "HOME SWEET HOME!$"

PalletTown_Text_RivalsHouse::
    .string "'NO TRESPASSING'$"

PalletTown_Text_TownSign::
    .string "Embark soon, young trainer?$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "POKeDEX: 37/151$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "USE STRVAR1 TO enhane!$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Stranger, yes.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "'A fine adventure calls! Seek out\p"
    .string "the ancient forest!'$"

