ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "Press X to help!$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "'BEGONE, CURSED CREATURE!'$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "'MEET LOSTELLE AT CAMP'$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "You accompany Lostelle back to his\p"
    .string "daddy'smetrical house on SECTOR\n"
    .string "42iframe...$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Picking this up wouldn't be a\p"
    .string "smart move.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "You find a rare ORANGE BERRY!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Berries ahead!$"

