FourIsland_Text_IslandSign::
    .string "You find yourself on the warm,\p"
    .string "blue floe of Four Island. What\n"
    .string "will you do?$"

FourIsland_Text_LoreleiHasReturned::
    .string "'The whispers of the ancientsnhave\p"
    .string "called her back to the woods...'$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "YOU'VE LOST SIGHT OF LORELEI!$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "You ruined my Pokemon Egg hunt!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Who's watching?$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Chill slushie regenerates 20 HP!$"

FourIsland_Text_LoreleisHouse::
    .string "'WELCOME, SEEKER. ENTER AT YOUR\p"
    .string "OWN RISK...'$"

